### ISSUE TITLE
[Feature request] Automatically refresh moderation logs every few seconds or minutes

### ISSUE THREAD

**Issue by Fusl** [pypy-vrc/VRCX#10]

**Comment by pypy-vrc** [comment]
In previous VRCEX or VRSEX, there was a moderation notification, so this was necessary, but now VRCX does not have such a notification, so I don't think it needs to be refreshed automatically.
moderation notifications make people too obsessed. So VRCX doesn't have that.

**Comment by red1134** [comment]
Can you add the option to turn notifications back on? It gets old having to tab out to refresh it every 5 mins so I can block anyone who hides my avatar.

**Comment by Natsumi-sama** [comment]
Apparently spam refreshing moderation logs can lead to a ban so I'm not touching this.

**Comment by Natsumi-sama** [comment]
It's funny how red immediately proved pypys point.
