### ISSUE TITLE
[Bug - 2020.10.25] Launching VRChat in Desktop mode no longer works.

### ISSUE THREAD

**Issue by Provini** [pypy-vrc/VRCX#100]
It instead will still launch you in VR.

**Comment by TripingPC** [comment]
I think I might know what's going on.
The new Steam launch feature passes a steam protocol URL for rungameid as an argument to the Steam executable.

The issue that causes it to not launch in desktop-mode is that I suspect the space between the world link and the no-vr launch argument isn't being URL encoded into %20, and any spaces in the URL will be considered as anotehr argument for Steam, not VRChat.

After doing some testing on my own, trying to pass both --no-vr and a world ID using URL encoding doesnt work. but using applaunch works.

like this
`"C:\Program Files (x86)\Steam\steam.exe" -applaunch 438100 --no-vr vrchat://launch?ref=vrchat.com&id=wrld_a2ee4876-6560-4a87-bf30-2b7c51fc1792:20564~private(usr_82687b0b-cc65-4807-8f8b-77aff851c4a6)~nonce(8772fc6d-1eb9-4f18-ad05-f4beb7823778)`
