### ISSUE TITLE
Custom Color options for ranks

### ISSUE THREAD

**Issue by lexvi** [pypy-vrc/VRCX#106]
I have a certain set of colors that i prefer over the set colors for dark mode, makes the ranks more visible and easier to recognize who is which rank.

Anyways for eatch update i have to go and edit the app.css and app.dark.css and replace the color codes manually, it would be nice to have in app color pickers for eatch role to easier change the colors for eatch role.

If not an added feature a few updates back the css files were easier to read with row changes between every line, now its just one string of stuff and i have to manually enter it up to make it easier to read and change the stuff i want to change,

**Comment by Natsumi-sama** [comment]
Maybe this is good enough? I had to change this color every time because of the dark theme https://github.com/pypy-vrc/VRCX/pull/108/commits/1cc23526eac1cc7c326090b32e68aa78614c46de

**Comment by lexvi** [comment]
> Maybe this is good enough? I had to change this color every time because of the dark theme [1cc2352](https://github.com/pypy-vrc/VRCX/commit/1cc23526eac1cc7c326090b32e68aa78614c46de)

What i was requesting is custom color input boxes, or even a checkbox for alternative colors.i can provide you with my prefered alternative colors.

OR you know what would be great alternative solution, Seperate .css File for only the Rank Colors.

Or the css's being commented and documented for easier readability like i mentioned earlier.


In addition to the color changes i also like to change the Font sizes and make the sidebar friend list wider for easier readability with OVR-Toolkit

I already pretty much know what im looking for to make these changes at eatch new Version i update to but easier readability and commented css would help.

Like knowing what eatch value and argument changes would be nice

**Comment by Natsumi-sama** [comment]
Because of how the program is built the css files get minified so it's not designed to be human readable unless you edit/compile the source code your self.

With OVR-Toolkit readability you could make your window capture larger or I could maybe create a zoom/DPI option but that would essentially do the same thing.

**Comment by lexvi** [comment]
i guess ill just manually keep making these changes then.

But the in app color change option could be quite usefull for less advanced users.


Thx and consider.

**Comment by GenesisAria** [comment]
Adding a double \r after every close brace } makes it plenty readable.
