### ISSUE TITLE
Missing Credential issues still ongoing. Unable to use VRCX.

### ISSUE THREAD

**Issue by SalaciousBug** [pypy-vrc/VRCX#107]
Unfortunately, the issue I was having before as noted [here](https://github.com/pypy-vrc/VRCX/issues/92) is still ongoing and I am unable to use VRCX. :(

![image](https://user-images.githubusercontent.com/24326270/100670319-4b4b5700-3324-11eb-83e2-ed4a6118702e.png)

**Comment by Natsumi-sama** [comment]
Have you tried a fresh install of VRCX? Try disable antivirus/firewall software. Make sure you details are correct by logging into https://www.vrchat.com/home

**Comment by SalaciousBug** [comment]
> Have you tried a fresh install of VRCX? Try disable antivirus/firewall software. Make sure you details are correct by logging into https://www.vrchat.com/home

I've tried all of that yeah and all of my details are correct but it continues to give me this error. It won't even give me the option to enter my 2FA at all.

**Comment by Natsumi-sama** [comment]
Try change you password to something simple? maybe VRCX is having trouble parsing it.

**Comment by SalaciousBug** [comment]
> Try change your password to something simple? maybe VRCX is having trouble parsing it.

That does nothing sadly. :/

**Comment by Murkur** [comment]
ive noticed that VRCX doesn't support certain characters my friend hordini had this issue and had to change password to one more simple, also HI SAL

**Comment by SalaciousBug** [comment]
> ive noticed that VRCX doesn't support certain characters my friend hordini had this issue and had to change password to one more simple, also HI SAL

Wow, I'm an idiot... Yeah, symbols aren't supported in VRCX it seems. Thanks!

**Comment by TheGP** [comment]
~~Had the same problem with password with special symbols, very weird!~~

**Comment by Natsumi-sama** [comment]
What symbols did you use? I've tried to reproduce this issue in the past but I couldn't.

**Comment by TheGP** [comment]
@Natsumi-sama I used passwords generated by Bitwarden with special characters

~~Thats examples, only 1 of 5 passed before, so one of the below for surely should trigger it (I didn't test it)~~
```
&*Ahwm2c&Cxz&&eHpiH$N77$U81f
G%FTeZpfuRbwTdVI&T3XZLoA*ZOq
H&NHwvEMCOHP7uT*ZO^Fh0HLREPn
AYJnrjcK%XVr1ZdCxc$YLcFzm3o7
0e#SsGh4l%3Ey2rUcc9VKmNL1maA
uM&8cqqG7MMOr#RyGqYyyB&9nXb3
v0Ols832n*xSo#t1DUi^Gv6MKe0c
v8nTk@B6GpkipuH$6Tv&J6zF75rE
```

**Comment by TheGP** [comment]
Small update, I currently have "missing credentials" with 3 passwords without any special characters, will tell how I resolve it after resolving

**Comment by TheGP** [comment]
False alert, it just didnt like that I sign up from different countries IPs that time, not related to password

P.S. And previous comment about special symbols: it was probably wrong time on my PC so it generated wrong OTP and not special symbols in password.
