### ISSUE TITLE
"Show Avatar Author" User Context Menu is Misnamed

### ISSUE THREAD

**Issue by explodingkittns** [pypy-vrc/VRCX#109]
When viewing someone else's profile, there is an option in the context menu titled "Show Avatar Author." However, clicking this button pulls up the entry for the avatar itself, not the author of the avatar. The only case where it pulls up the author of the avatar is when viewing the user's own profile. This label should probably be changed to something else. See attached screenshots:

![1.png](https://i.postimg.cc/0NS2vxsF/1.png)

![2.png](https://i.postimg.cc/pdKx7ZQt/2.png)

**Comment by Murkur** [comment]
just select username?

**Comment by explodingkittns** [comment]
> just select username?

Yes, you can do that to get to the avatar's author- it's just that the text itself for the menu option is incorrect.

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/pull/108/commits/99c55cdd0babe957ebd6149c3b2a2454f91990ab
