### ISSUE TITLE
[Feature request] Display moderation log and friend log as SteamVR overlay notification

### ISSUE THREAD

**Issue by Fusl** [pypy-vrc/VRCX#11]
Moderation log depends on implementation of #10

**Comment by Natsumi-sama** [comment]
Moderation log won't be added for now but friend log has been added.
https://github.com/pypy-vrc/VRCX/commit/3c451e4876ed92b183051ae0b3cb278bc6582adb
https://github.com/pypy-vrc/VRCX/commit/54f7f5154f51077d431304fc320c4146db6529ba
