### ISSUE TITLE
Clicking on a user in Game Log doesnt immediately show the profile

### ISSUE THREAD

**Issue by fwenny** [pypy-vrc/VRCX#110]
If I click on a user in Game Log, it takes me to Search for some reason.
Then if I go back into Game Log and click on the same user again, suddenly it finds him.

Why does it take me to search if it doesnt need my input to find the profile?

Would be great if it opened the profile right away.

**Comment by Murkur** [comment]
This is a limitation, VRCX only loads known profiles into cache, this being your friends as it cant simply just cache the entire userbase you have to search for the user before finding it as vrcx only logs the name compared to logging the usr id and loading it into cache. thats why when you select the user after searching it finds it automatically the same thing happens if you login to vrcx with one account with friends then switch to another account with no friends but it will still find the friends from the first account instantly

**Comment by fwenny** [comment]
Its fine that it doesnt cache the user, I dont expect it to. But I dont see a point of looking at the Search screen after clicking the user. It should just open the profile after finding it.

**Comment by Murkur** [comment]
it doesn't do that because its not 100% accurate duplicate names exist and searching is not very rock solid it would be better to just have vrcx cache usr ids from log actually since they already get grabbed for gamelog and cache it till next restart

**Comment by fwenny** [comment]
I mean it always logs the correct user for me. I just click back to the Game Log and click on the name again. 
The search page servers no purpose in this case.

Anyway if you feel like theres nothing that should be changed, go ahead and close this. I just wanted to streamline a process that right now feels a bit annoying.

**Comment by Murkur** [comment]
thats not what I mean when it goes to the search page it does that so you select who you think that user is after you select the user it caches it and auto completes the search. its a redundant process hopefully in the next version this will be updated.

**Comment by fwenny** [comment]
But thats the thing, I select no one! I just go back and it selects the user automatically. :P

**Comment by fwenny** [comment]
I never interact with the Search page.

**Comment by Natsumi-sama** [comment]
I just had a look and it seems that you can't correlate usernames to user ID's in the log file.

**Comment by fwenny** [comment]
> 
> 
> thats not what I mean when it **goes to the search page it does that so you select who you think that user is** after you select the user it caches it and auto completes the search. its a redundant process hopefully in the next version this will be updated.

Im just saying this does not happen. I do not select anyone. It auto selects a person on its own. Meaning there shouldnt be any issue for the program to show me the profile right away.

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/pull/108/commits/dffe1bdde928c4522c47431f31db0f8146d7d310

**Comment by fwenny** [comment]
Thank you.
The only time it makes sense for me to open the search tab is when it isnt able to automatcially find the user, but like I said that has never happened to me yet.
