### ISSUE TITLE
Add support for increased/expanded favorite avatar groups

### ISSUE THREAD

**Issue by Asovrix** [pypy-vrc/VRCX#112]
As in title, with the release of VRChat Plus all users received an update to 25 favorites from 16 and VRC+ to 4 groups with 25 each. VRCX still displays 16 favorite slots in one group.

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/pull/111

**Comment by kazu0617** [comment]
Ready for review.

in api, avatars/favorites must contains tag such as "avatars1" ~ "avatars4". but line 2906@app.js doesn't have any tag, so load only avatars1. if load correct, must load cyclic.
but if you clicked at once, check correct.
