### ISSUE TITLE
Searching for Avatars and Users gives JSON error

### ISSUE THREAD

**Issue by stayandwait** [pypy-vrc/VRCX#114]
I'm getting a '500 Internal Server Error "Unexpected token } in JSON at position 60' when searching
![VRCX_NN6lgeUmaA](https://user-images.githubusercontent.com/15825041/101536470-46eff100-3957-11eb-9a42-59f84b7161c9.png)

**Comment by stayandwait** [comment]
This actually appears to be an issue with VRChat's servers. So, I am no longer getting this error now.

**Comment by Fusl** [comment]
5xx errors are generally always server-side so you can pretty much ignore those.

(This particular server-side error was caused by VRChat's MongoDB infrastructure being broken at the time you opened the ticket.)
