### ISSUE TITLE
Increase Favorite Avatar Limit to 25

### ISSUE THREAD

**Issue by DarkPower202** [pypy-vrc/VRCX#116]
There's a new VRChat update that increased the favorite avatar limit from 16 to 25, yet VRCX can only hold 16 max.
![image](https://user-images.githubusercontent.com/71892423/101967921-ab60c800-3c57-11eb-8b91-855baacd2e7e.png)

**Comment by DarkPower202** [comment]
Tried refreshing, still giving 16. If you try to favorite more than 16, you can't.

**Comment by Natsumi-sama** [comment]
Already merged, will be in next release https://github.com/pypy-vrc/VRCX/pull/111
