### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by GenesisAria** [pypy-vrc/VRCX#119]
Option to disable VRC+ images in friends list and/or show avatar thumbnail instead.

**Comment by Natsumi-sama** [comment]
My bad, I assumed no one would want that I will add it as a setting then.

**Comment by fwenny** [comment]
Why not? Im way more interested in avatar thumbnails then their icons. Potential to find new avatars!

**Comment by Murkur** [comment]
always make an option a majority of people are not to fond of vrcplus in the first place

**Comment by Natsumi-sama** [comment]
Added as a option https://github.com/pypy-vrc/VRCX/pull/124/commits/2e971bf2554cd56e694dc5b3f0a02816831286d5

**Comment by fwenny** [comment]
Are we able to simply take the changed files and replace them, or do we need to wait for a full release?

**Comment by Natsumi-sama** [comment]
Here's the changes if you can't want to wait for release, just replace your html folder with this one [html.zip](https://github.com/pypy-vrc/VRCX/files/5685246/html.zip)

**Comment by fwenny** [comment]
thank you!

**Comment by fwenny** [comment]
it works great but unfortunately doesnt save between sessions @Natsumi-sama

**Comment by Natsumi-sama** [comment]
Yup whoops didn't test that, fixed here [html.zip](https://github.com/pypy-vrc/VRCX/files/5685534/html.zip)
