### ISSUE TITLE
[Bug] Close to tray doesnt work

### ISSUE THREAD

**Issue by fwenny** [pypy-vrc/VRCX#120]
Latest version.
Whether the option is on or off, it closes once I hit the X.
Minimizing works as normal.

**Comment by Asovrix** [comment]
I don't see it happening in my case. I have upgraded from previous release by simply overwriting files as usual.

**Comment by fwenny** [comment]
Am I understanding correctly that the tray icon that appears with the application simply stays even after you click X?

**Comment by JjTheHusky** [comment]
Having the same issue as well. The app closes completely instead of closing to the tray.
Additionally, the app keeps telling me that an update is available when the latest is installed. (Installed 2020.12.13, but shows 2020.10.25)

**Comment by Kieaer** [comment]
> 
> 
> Am I understanding correctly that the tray icon that appears with the application simply stays even after you click X?

True

**Comment by fwenny** [comment]
then yeah, seems like it doesnt work for everyone for some reason.

**Comment by Natsumi-sama** [comment]
Issue fixed here: https://github.com/pypy-vrc/VRCX/pull/125/commits/43e303ff3856bab90d855848117f7300e6374c8c

@JjTheHusky I'm guessing you used the old html folder I provided if you use this updated one it should remove the update message https://github.com/pypy-vrc/VRCX/issues/119#issuecomment-744074721
