### ISSUE TITLE
Online Users check returns user count as an error notification

### ISSUE THREAD

**Issue by Asovrix** [pypy-vrc/VRCX#122]
Basically this:
![VRCX_2020-12-13_15-34-15](https://user-images.githubusercontent.com/44006686/102014986-06c6af00-3d59-11eb-80ad-89ef140a5a65.png)

Before recent update it used to replace "Click to refresh" with user count instead of showing it that way.

**Comment by Natsumi-sama** [comment]
Fixed here https://github.com/pypy-vrc/VRCX/pull/124/commits/e7fc104125c361ce423b1edbff420373c374b578
