### ISSUE TITLE
[2020.12.13] VRCX loses websocket connection after awhile

### ISSUE THREAD

**Issue by ScruffyRules** [pypy-vrc/VRCX#126]
This only started with 2020.12.13, the feed just stops updating.
2020.10.25 does not do this.
I don't exactly have the best internet but something definitely broke in the latest update.

**Comment by Natsumi-sama** [comment]
Try tick save credentials and enable auto login in settings.

**Comment by ScruffyRules** [comment]
After running VRCX (2021.01.09) for 2 sessions over 2 days with those settings, the feed has continued to update without issue.
Previously it would stop updating after a couple of hours. I'll reopen this if it ever fails again.
Thank you.
