### ISSUE TITLE
No clue but i just get this error on every startup

### ISSUE THREAD

**Issue by Shadxku** [pypy-vrc/VRCX#129]
![image_2020-12-28_172106](https://user-images.githubusercontent.com/76711313/103248628-11746d00-4931-11eb-9ddd-56fc79937dee.png)

**Comment by Natsumi-sama** [comment]
After fresh install or update? Did you extract the entire zip? Seems like a problem with your VRCX.sqlite3 file.

**Comment by Shadxku** [comment]
> After fresh install or update? Did you extract the entire zip? Seems like a problem with your VRCX.sqlite3 file.

fresh extract from the newest release, VRCX 2020.12.13. just extracted it with winrar on a folder

**Comment by Natsumi-sama** [comment]
Try extract again and make sure that all the files are selected in the zip, or right click extract on the zip.

**Comment by Shadxku** [comment]
extracted it using the button, and by just ctrl+a and drag dropping. still same popup either way

**Comment by Natsumi-sama** [comment]
Hmmm I'm not sure then, you could try extract to a different location like your desktop or use an older version or try disabling your antivirus.

**Comment by Shadxku** [comment]
It was the antivirus, thank
