### ISSUE TITLE
[Feature request] disable join/leave from overlay

### ISSUE THREAD

**Issue by rakosi2** [pypy-vrc/VRCX#130]
Could I disable join/leave logs from the SteamVR overlay. I already see the join/leave messages.

**Comment by Natsumi-sama** [comment]
Could you be more specific? are you referring to overlay notifications or wrist feed?

**Comment by rakosi2** [comment]
The wrist feed becomes full of just join leave messages. The overlay already told me that they joined so I don't want to see it again.

**Comment by Natsumi-sama** [comment]
Hmmm alright, if I'm to do that I would create a filter to choose any event to display/hide in the wrist feed, and I would do the same for notifications. I should get around to it eventually.

**Comment by Natsumi-sama** [comment]
Added with feed filters https://github.com/pypy-vrc/VRCX/commit/15c57959e87a64ff6ce7685903ec6bd434cebda9
