### ISSUE TITLE
[Feature request] Advanced notification configurations

### ISSUE THREAD

**Issue by Fusl** [pypy-vrc/VRCX#131]
Some people don't like to see all notifications for all events as VR overlay or on their hand (#130 as example) so something like this to allow a really fine grained control of notifications should address this issue for literally everyone:

![image](https://user-images.githubusercontent.com/2349496/103424587-14779380-4ba5-11eb-83da-ea18b9dd16e3.png)

- 1st column defines the notification type
- 2nd column defines the default notification level for Windows Notifications (which needs to be implemented first)
- 3rd column defines the default notification level for the in-VR hand overlay
- 4th column defines the default notification level for the in-VR notification pop-up
- 5th column defines the possible level options for each particular notification type

**Comment by Arefu** [comment]
I think this would be a great QOL feature to see in this program now the development thanks to @Natsumi-sama  contributing lots, I look forwad to seeing this implimented!

**Comment by Natsumi-sama** [comment]
I have been thinking a lot about how to go about implementing this or something similar but this level of granularity wouldn't be very user friendly or convenient for the average user, I can't think of way of creating this that wouldn't be a massive UI mess. It would also be way too time consuming to implement exactly this. Maybe having set groups of notifications like join/leave or online/offline but I understand that some will only want join/online. Could have a toggle for simple or advanced options but that's just even more work. I'm open for more ideas but still undecided.

**Comment by Natsumi-sama** [comment]
I think this will be sufficient https://github.com/pypy-vrc/VRCX/commit/15c57959e87a64ff6ce7685903ec6bd434cebda9 test and give feedback if you can.
