### ISSUE TITLE
refreshing gamelog too slow

### ISSUE THREAD

**Issue by pypy-vrc** [pypy-vrc/VRCX#133]
In the past, VRChat Log files seem to have been automatically cleaned up, but recently, the files still remain for some reason. 🤔

this resulted in reading all unnecessary log files. so something needs to be done.
(reading only the logs created/modified in the last few days, or improve I/O?)

![Honeycam 2021-01-17 14-50-37](https://user-images.githubusercontent.com/25771678/104832255-6160a700-58d3-11eb-8e84-9e3659349328.gif)

![image](https://user-images.githubusercontent.com/25771678/104832350-d8963b00-58d3-11eb-821d-ce2e7177166e.png)
500MB? 😨

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/commit/ade1de170534f8dc18fc61ab5bb8496d9680b0f7 a easy quick fix but not a great long term one.
