### ISSUE TITLE
[Feature request] Filter avatar list by public and private.

### ISSUE THREAD

**Issue by BLANKE1** [pypy-vrc/VRCX#135]
I'd like to have a way to filter my avatars through my private avatars and public avatars. Would help a lot in counting how many publics I have.

**Comment by pypy-vrc** [comment]
![image](https://user-images.githubusercontent.com/25771678/106459056-a3ddd280-64d4-11eb-9ab3-76851335dcfb.png)
![image](https://user-images.githubusercontent.com/25771678/106459155-cbcd3600-64d4-11eb-8b24-74d12e4692b6.png)

added f81c6220203f714955055a4b8e8f972296b65a93
