### ISSUE TITLE
[Feature] Windows Notification

### ISSUE THREAD

**Issue by rakosi2** [pypy-vrc/VRCX#136]
Could I get Windows Notifications whenever I get a Notification/Invite? I tend to have VRCX running in the background and it shows that I am online. Friends will send me an invite and I sometimes will see the invite hours later.

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/commit/d32c1f9078198a60b044d417765689664e5d164f should be sufficient.
