### ISSUE TITLE
[Feature request] Enable notifications without wrist overlay/general overlay

### ISSUE THREAD

**Issue by Lupsoris** [pypy-vrc/VRCX#139]
Hello!

I would like to be able to enable notifications on the desktop without having to enable the overlay on SteamVR (completely disable all overlays).
But also that it's possible to enable desktop notifications and/or VR notifications without having the overlay on the wrist (or that it's possible to disable this overlay).

Thank you!
Lupsoris

**Comment by Natsumi-sama** [comment]
Hello there, it's not possible to disable the wrist overlay and have desktop notifications at the same time with this current version, it should be possible in the future but will require moving a lot of code around.

**Comment by LilAtomikku** [comment]
I would like to see this fixed as well. Hoping to see it in the future!

**Comment by Lupsoris** [comment]
I hope it will be possible, yes! Because I really like the idea of ​​having desktop notifications (as a priority), but also having them in VR. But I don't use the wrist overlay, and I even find it rather annoying because it's activated with "keys" that I use often, it's rather big ^^`
