### ISSUE TITLE
[Feature Request] Readd lastplatform to online/offline for

### ISSUE THREAD

**Issue by MinerSpark** [pypy-vrc/VRCX#141]
Readd the option to show last active platfom under online/offline for.
Helpful to tell when your quest friend's are online in PC or desktop to know what kind of avatar to use before hand.

**Comment by pypy-vrc** [comment]
![image](https://user-images.githubusercontent.com/25771678/106457038-b99dc880-64d1-11eb-99f4-2241203c9054.png)
sorry re-added as tag (fbebe2bbdcf848b89ece54e8b87806ab94309cbc)
