### ISSUE TITLE
High gpu usage

### ISSUE THREAD

**Issue by Explicitvoid** [pypy-vrc/VRCX#143]
Since version 20201213.1 I've noticed VRCX uses 12-25% of my gpu. This occurs even when not in vr and not using the overlay.

![2021-02-04_02-05-24](https://user-images.githubusercontent.com/1491571/106857422-0f1ed480-668e-11eb-990c-83cc3912c947.png)

System specs:
- Device Model: PowerEdge R710 (Dell Inc.)
- Processor Type: Intel(R) Xeon(R) CPU X5690 @ 3.47GHz
- System Memory Size: 98291MB
- Operating System: Windows 10  (10.0.0) 64bit
- Graphics Device Name: NVIDIA GeForce GTX 980 Ti
- Graphics Device Version: Direct3D 11.0 [level 11.1]

**Comment by pypy-vrc** [comment]
current:
![image](https://user-images.githubusercontent.com/25771678/106863576-0ff64b80-670c-11eb-897f-a4a36e1a6c0f.png)

fixed:
![image](https://user-images.githubusercontent.com/25771678/106863617-1f759480-670c-11eb-8a9d-0ba143621e3c.png)

reduced the GPU usage on commit ed681f4d088e4fb2daca0dc4b17b0360a5792951 but I don't know if the overlay works fine. 😖

**Comment by Natsumi-sama** [comment]
This commit seems to cause input lag opening wrist overlay 😢

**Comment by Explicitvoid** [comment]
> This commit seems to cause input lag opening wrist overlay 😢

Just tried the wrist overlay with this commit and while it does seem to cause a few second delay while initially opening the overlay, opening it again is instant.

**Comment by Explicitvoid** [comment]
This seems to be fixed for me in some of the more recent updates.
