### ISSUE TITLE
Game Log is not working

### ISSUE THREAD

**Issue by Chungryang2** [pypy-vrc/VRCX#144]
![화면 캡처 2021-02-04 205246](https://user-images.githubusercontent.com/78540990/106889340-37a8dc00-672b-11eb-812b-03f93666ce66.jpg)

Game Log doesn't work like this, is there a solution?

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/issues/142#issuecomment-772611396 either wait for next update or (build)[https://github.com/pypy-vrc/VRCX#how-to-build-vrcx] it yourself.
