### ISSUE TITLE
[Feature Request] Export all friends discord names

### ISSUE THREAD

**Issue by Bluscream** [pypy-vrc/VRCX#146]
It would be neat if there was an button that scrapes all your friends statuses (and maybe bios) for discord names and allows you to export that as a list so you can more easily add people from the game on discord without needing to click every friend

Example (c#): https://github.com/Bluscream/VRChatLauncher/blob/master/UI/Main/Users.cs#L761
Example 2 (c#): https://github.com/vrchatapi/VRCAPIdotNet/blob/master/VRCAPIdotNet.Example/Program.cs#L180-L196

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/commit/5fb5052857b3e3a90c82d65257eb622c72986132
