### ISSUE TITLE
[Feature Request] Detailed friends table

### ISSUE THREAD

**Issue by Bluscream** [pypy-vrc/VRCX#147]
I would love if there was an extra table that lists all friends no matter the status and that you can actually sort by available values, something like this:

![image](https://user-images.githubusercontent.com/3318223/107008397-07e1ee80-6794-11eb-9059-c5e885eed789.png)

this will help for example if you want to unfriend people that haven't logged in for quite some time. And lets you quickly find your no. 1-3 friends for example.

Other fields like user id and maybe something else i forgot can also be added.

And because i understand that fetching every friend's info one by one is gonna take a shitton of server requests i would say make it only use data that has already been cached by VRCX

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/commit/3aff3d4318692cb6dbac1da49ffe12140069bf1c
