### ISSUE TITLE
Friends list doesn't update sometimes

### ISSUE THREAD

**Issue by ShaunDreclin** [pypy-vrc/VRCX#153]
For some reason the list doesn't always stay updated, I usually have to hit ctrl-f5 to refresh the whole app when I want to see if anyone has come online or not.

Possibly related to losing internet connection, I do see errors popping up when that happens so maybe it's just not recovering gracefully from a loss of connection

**Comment by Natsumi-sama** [comment]
Enable save credentials and auto login if you haven't already.

**Comment by ShaunDreclin** [comment]
Yep both of those are enabled
