### ISSUE TITLE
App hangs, stops refreshing/reacting to any user input

### ISSUE THREAD

**Issue by GotoFinal** [pypy-vrc/VRCX#154]
I build the app from last commit (https://github.com/pypy-vrc/VRCX/commit/4347da4fa70e1b0ab0325c6220986d9f245ed0d2) (and few other ones before) and im constantly experiencing this issue when application just stops responding to anything and i need to restart it. And this also often corrupts my save file.

**Comment by Natsumi-sama** [comment]
I believe this is due to https://github.com/pypy-vrc/VRCX/commit/97a4dbf4d30294f77d3f7c4fe89663d95f752396, it's a work in progress commit. You could revert it, build from source before the commit or use my fork till next release.
