### ISSUE TITLE
vrchat update broke some of the endpoints 

### ISSUE THREAD

**Issue by sophia1000** [pypy-vrc/VRCX#160]
![image_2021-03-04_181113](https://user-images.githubusercontent.com/61364377/110048201-01a04d00-7d15-11eb-98c2-066c210f68e6.png)
this message just gets spammed and moderations doesn't get updated so my guess they changed the endpoint for that

**Comment by sophia1000** [comment]
ok it was just the endpoint to check playermoderations

**Comment by Micafira** [comment]
I can confirm this.

**Comment by SalaciousBug** [comment]
> ![image_2021-03-04_181113](https://user-images.githubusercontent.com/61364377/110048201-01a04d00-7d15-11eb-98c2-066c210f68e6.png)
> this message just gets spammed and moderations doesn't get updated so my guess they changed the endpoint for that

Yeah, they disabled the 'CheckPlayerModerationsAgainstYou' endpoint for added privacy.

**Comment by sophia1000** [comment]
its not as much for privacy as the web api still has access to it they either renamed or removed it for the client api. now this gets spammed to idk what they disabled this time
![image_2021-03-06_153839](https://user-images.githubusercontent.com/61364377/110221463-05a5a980-7e92-11eb-9835-96b36c1fb685.png)

**Comment by Natsumi-sama** [comment]
503 seems to occur every second attempt fetching `auth/user/friends` so uhhhh yup...

**Comment by sophia1000** [comment]
oof is that what they blocked

**Comment by Murkur** [comment]
> oof is that what they blocked

I doubt it, the reason player moderation was removed was because its now handled by Photon through game client making Friends handled by photon aswell would break the parts of the vrchat website

**Comment by Naraenda** [comment]
> 
> 
> 503 seems to occur every second attempt fetching `auth/user/friends` so uhhhh yup...

503 seems to happen whenever the socials endpoint gets overloaded. See the last few announcements in the discord:
>  In times where issues arise, we're able to preserve instances and ongoing sessions by temporarily reducing friends list functionality.

**Comment by GenesisAria** [comment]
They've been messing with stuff lately trying to fix/compensate/upgrade, but it's turned into a mess.

**Comment by Natsumi-sama** [comment]
It seems VRChat have fixed the 503's, for now...
