### ISSUE TITLE
503 spam

### ISSUE THREAD

**Issue by GenesisAria** [pypy-vrc/VRCX#161]
When vrchat is messing with the api or server response is hindered by whatever causes, and http errors start showing up, these don't seem to go away.  There have been times recently where i wake up and have to either click through dozens of 503's or restart vrcx.  It would be ideal if these errors timed out or there was a clear all notifications option.

**Comment by Murkur** [comment]
Just CTRL R VRCX as right now vrchat only gives up a notification of the apis being disabled to mitigate server crashes about an hour before it happens

**Comment by Natsumi-sama** [comment]
I previously did a commit to hide these but thought it was best to leave them there so you know why your friends list isn't updating I think changing how they are displayed would be best https://github.com/pypy-vrc/VRCX/commit/009ce76fc1bfd9e4f2636fc19de2547174bd0452
