### ISSUE TITLE
Rnadom freezing/hanging of the application

### ISSUE THREAD

**Issue by KeruAvali** [pypy-vrc/VRCX#162]
During use, specifically in VR/in VRChat, once in a while the app hangs/freezes. I have no set steps to reproduce this bug (if one can call it a bug), but if you need to, try to launch it in VRChat while it's open and invite yourself to a world.

EDIT: Forgot to include, the reason there isn't any steps to reproduce is because it happens randomly! However, it's quite frequent for me.

EDIT 2: Happens when you join instances with a large or decent amount of users.

**Comment by ScruffyRules** [comment]
Usually happens when you join an instance with lots of players, I'd really like this fixed ASAP because it happens so often.

**Comment by KeruAvali** [comment]
> Usually happens when you join an instance with lots of players, I'd really like this fixed ASAP because it happens so often.

I can confirm that these are the steps to reproduce this bug. Seems to happen every single time I join a big instance. Adding it to the main post.

**Comment by Belphagore** [comment]
Mine will happen when VRChat crashes from a large instance. If I close SteamVR, it'll always re-launch SteamVR until I kill the frozen VRCX application.

I will try to collect more details and the error when it happens again from the event viewer.

**Comment by Natsumi-sama** [comment]
Are you able to compile the latest version or try my fork and tell me if it fixes it?
