### ISSUE TITLE
Friend No. is no longer accurate

### ISSUE THREAD

**Issue by ScruffyRules** [pypy-vrc/VRCX#164]
GitHub freaked out and made me post it before I had a chance to finish typing :)))
Friend No. is no longer accurate now that the API returns a sorted list

**Comment by Natsumi-sama** [comment]
Yup https://github.com/pypy-vrc/VRCX/commit/d1b95b180570d3eeea0e1320bd67fbb9ca28226a

**Comment by ScruffyRules** [comment]
API is now returning to what I can see, the same order as before this issue, IDK if you want to still drop the friend number or return it,

**Comment by Natsumi-sama** [comment]
Already returned https://github.com/pypy-vrc/VRCX/commit/0f366c278521e8cc80c741162ba8e5d5bb931cff
