### ISSUE TITLE
[Feature Request] bulk friend removal and other features.

### ISSUE THREAD

**Issue by xal3xhx** [pypy-vrc/VRCX#167]
i have well over 400 friends and almost none on them come online anymore and most i dont even want to talk to anymore. i would love to have a way to be able to select multiple friends and perform actions on them, ie remove, invite, favorite. it would also be really cool to be able to sort by the last time they were online. and finally being able to invite everyone in my favorites or that is online to my would we be sweet. (might already be a feature)

**Comment by Natsumi-sama** [comment]
Side Pannel Sorting Options > Offline by state will sort last online, I don't think the API will let you bulk unfriend will probably error out, you can bulk invite by clicking the instance id then clicking the invite button.

**Comment by xal3xhx** [comment]
it appears that sorting by state is not sorting my last online.

**Comment by xal3xhx** [comment]
and for the bulk friend removal what not add a delay to it and show a progress window?

**Comment by Natsumi-sama** [comment]
works for me, if it's limited the delay would need to be huge something like 5mins seems impractical.

**Comment by Natsumi-sama** [comment]
Should be sufficient https://github.com/pypy-vrc/VRCX/commit/3aff3d4318692cb6dbac1da49ffe12140069bf1c
