### ISSUE TITLE
Friends constantly switching between online / offline, spams feed

### ISSUE THREAD

**Issue by SalaciousBug** [pypy-vrc/VRCX#170]
So I'm pretty sure this has to do with the recent server changes but lately my feed has been getting spammed and ends up looking like this at times. 
![image](https://user-images.githubusercontent.com/24326270/112653856-d513b880-8e1c-11eb-901f-44c5e6d5ebd7.png)

**Comment by Murkur** [comment]
Nothing to do with VRCX this is because of recent API changes inplace they said it should be fixed soon

**Comment by SalaciousBug** [comment]
> Nothing to do with VRCX this is because of recent API changes inplace they said it should be fixed soon

That's what I figured as well, but was suggested about posting it here anyway.
