### ISSUE TITLE
403 Forbidden appears when I try to log in 

### ISSUE THREAD

**Issue by Ela2234** [pypy-vrc/VRCX#172]
I tried to log in with my vrc account, but when i press login 403 Forbidden appears and it doesnt log me in (it also says "username is required" and "password is required" even though i typed it in before)

**Comment by RheaAyase** [comment]
Duplicate https://github.com/pypy-vrc/VRCX/issues/171

**Comment by Natsumi-sama** [comment]
> 
> 
> Duplicate #171
