### ISSUE TITLE
Avatar Image Upload Not Working

### ISSUE THREAD

**Issue by Miner28** [pypy-vrc/VRCX#173]
Title says it all pretty much… It shows as uploading forever.

**Comment by Natsumi-sama** [comment]
Can you press Ctrl + Shift + I click on the console tab and run `$app.debug = true;` then try upload again and see what output you get in the console.

**Comment by Miner28** [comment]
![image](https://user-images.githubusercontent.com/1560327/113520551-23028c00-9594-11eb-98cb-07cd247d0251.png)
File not found 🤔

**Comment by Natsumi-sama** [comment]
Whoops, I forgot a dependency https://github.com/pypy-vrc/VRCX/commit/cbe8f38f1515f425cc8676b1bdcaf6c2e4382fc1 just copy that dll to your VRCX folder and that should fix it.
