### ISSUE TITLE
[Feature Request] Possible to add VRC+ management menu?

### ISSUE THREAD

**Issue by OptoCloud** [pypy-vrc/VRCX#176]
Is it possible to add shortcuts to manage VRC+ subscription from VRCX?
Thanks!

**Comment by Murkur** [comment]
VRCX Runs through the games API, VRCPlus subscriptions are run through the games internal SteamAPI so its possible

**Comment by OptoCloud** [comment]
Which SteamID type does it use? i can figure out how to fetch it myself if you know how to get the link

**Comment by OptoCloud** [comment]
REGKEY: Computer/HKEY_CURRENT_USER/SOFTWARE/Valve/Steam/ActiveProcess/ActiveUser
This is the Active Users Steam32 ID

**Comment by OptoCloud** [comment]
Or you can get the current logged in username:
Computer/HKEY_CURRENT_USER/SOFTWARE/Valve/Steam/AutoLoginUser

**Comment by Natsumi-sama** [comment]
Currently isn't possible but will be in the future once steam isn't required.
