### ISSUE TITLE
Cannot open the program without an error showing up

### ISSUE THREAD

**Issue by kutiel** [pypy-vrc/VRCX#177]
I tried using older versions but it wouldnt let me log in so i constantly tried redownloading the newest one but i keep getting an error that won't allow me to open it https://prnt.sc/116xyyx

**Comment by Natsumi-sama** [comment]
Duplicate https://github.com/pypy-vrc/VRCX/issues/151 https://github.com/pypy-vrc/VRCX/issues/129#issuecomment-751898884 older versions wont work anyway due to https://github.com/pypy-vrc/VRCX/issues/171

**Comment by Murkur** [comment]
> Duplicate #151 [#129 (comment)](https://github.com/pypy-vrc/VRCX/issues/129#issuecomment-751898884) older versions wont work anyway due to #171

uhh you might wanna read the rest of there message 

> so i constantly tried redownloading the newest one but i keep getting an error that won't allow me to open it https://prnt.sc/116xyyx

**Comment by Natsumi-sama** [comment]
yea misread, oh well still applies

**Comment by Murkur** [comment]
not really they tried using "NEWEST" version so might want go fix that error since there getting it on the "NEWEST" version

**Comment by Natsumi-sama** [comment]
that's what the first two links are for, other people having the same issue and the last link explaining why older versions don't work
