### ISSUE TITLE
[Feature Request] Use favicons for bio link icons

### ISSUE THREAD

**Issue by OptoCloud** [pypy-vrc/VRCX#179]
Could you grab the favicon for a website and set that as the icon in the bio?

Example link:
https://www.github.com/favicon.ico

![image](https://user-images.githubusercontent.com/26223094/114249812-f687af00-999b-11eb-97f9-b309fb48e83d.png)

**Comment by Natsumi-sama** [comment]
No, because then your IP will be exposed to unknown websites, here is the current code for fetching favicon's https://github.com/pypy-vrc/VRCX/blob/master/html/src/app.js#L7456-L7463
