### ISSUE TITLE
HiDPI 미지원

### ISSUE THREAD

**Issue by crestudio** [pypy-vrc/VRCX#18]
영어를 못 해서 한글로 남깁니다

제가 4K 모니터를 쓰고 있는데, 데스크톱 화면이 HiDPI를 미지원해서 글씨가 흐리게 보이고 요새 눈이 침침해서 그런지 스케일이 작은 글씨가 잘 안 보이네요,,, 쿨,,, 럭,,, 다른 프로그램도 스케일 150%에서 200% 정도 쓰는데 HiDPI와 더불어 스케일 조정 옵션이 생기면 쓰기 좋을거 같습니다

항상 VRC 할 때마다 꼭 쓰고 있습니다, 감사합니다

**Comment by pypy-vrc** [comment]
안녕하세요.

v2019.11.18 버전을 올려두었으니 확인해보시고, 불편한 점이 있으시다면 다시 이슈로 등록해주세용. 😆😆

감사합니다.
