### ISSUE TITLE
[Bug - 2021.04.10] Disabling Overlay Notifications breaks the SteamVR Overlay toggle

### ISSUE THREAD

**Issue by Janni9009** [pypy-vrc/VRCX#181]
Using the Natsumi-sama fork, version 2021.04.10 released yesterday at the time of writing this.

**Expected behaviour:** Disabling the SteamVR Overlay Notifications toggle should not deactivate the whole Overlay, and only disable the Notifications bound to it.
**Current behaviour:** Disabling SteamVR Overlay Notifications deactivates the SteamVR Overlay toggle with no way of re-enabling either setting in-GUI.

**Comment by Natsumi-sama** [comment]
Woah you're right whoops, to fix for now for now press _Ctrl + Shift + I_ then in the console tab run `$app.overlayNotifications = true; $app.overlayWrist = true; $app.openVR = true;`

**Comment by Provini** [comment]
> Woah you're right whoops, to fix for now for now press _Ctrl + Shift + I_ then in the console tab run `$app.overlayNotifications = true; $app.overlayWrist = true; $app.openVR = true;`

Also want to mention the XSOverlay Notifications seem to not be working and it is enabled. (XSDiscord and XSOverlay VRChat Parser seem to notify fine.) I was going to report this on your fork but it appears you didn't have an issues tab.

**Comment by Natsumi-sama** [comment]
I just tried a fresh install and had no such issue, notifications are only displayed when VRChat is running and notification filters are applied to XS as well, could you open your console to see if there are any errors?

**Comment by Provini** [comment]
> I just tried a fresh install and had no such issue, notifications are only displayed when VRChat is running and notification filters are applied to XS as well, could you open your console to see if there are any errors?

Console is completely blank for me currently. Some of my other friends that tried this build also had issues getting XSOverlay Notifications to work.

**Comment by Natsumi-sama** [comment]
Hmmm I'm not sure what it could be, try send a test notification with this `AppApi.XSNotification('VRCX', 'test', 5, false);`

**Comment by Provini** [comment]
Okay it suddenly decided to work but portal notifications are failing. Join/Leaves seem to work.

**Comment by Natsumi-sama** [comment]
Any console error? I'm guessing the notifications are visible in game log/wrist feed? could be something to do with displaying the notification image.

**Comment by Provini** [comment]
No errors. Didn't pop up in wrist feed either.

**Comment by Natsumi-sama** [comment]
Hmmm only things I can think of is filter being disabled or maybe `--enable-sdk-log-levels` launch parameter being required, I forgot to test without it.

**Comment by Provini** [comment]
Hmm, the XSO VRChat Parser is able to get it without that launch param.

**Comment by Natsumi-sama** [comment]
I'm using a different log line that includes the user's username.
