### ISSUE TITLE
Error 400 and Error 401 (List Own Avatars/Public Avatars)

### ISSUE THREAD

**Issue by Murkur** [pypy-vrc/VRCX#182]
VRChat has now started blocking requesting to see your own avatars aswell as seeing other avatars without a direct UUID or using the Content Manager from the SDK

![image](https://user-images.githubusercontent.com/20288698/114494834-034e1200-9beb-11eb-9a5d-f70b063407f9.png)

![image](https://user-images.githubusercontent.com/20288698/114494807-f9c4aa00-9bea-11eb-8b54-e1a367f145dc.png)

**Comment by Natsumi-sama** [comment]
What the hell? haha

**Comment by Murkur** [comment]
> What the hell? haha

Just started getting it now and nope its just just me

**Comment by Natsumi-sama** [comment]
I'm getting it too

**Comment by Murkur** [comment]
> I'm getting it too

well getting your own avatar ids seems to be possible using the SDKs content manager but "show avatar author" is no longer working nither is reloading the list of your public avatars or others avatars

**Comment by Murkur** [comment]
only way to see others avatars public or not is through direct UUID in direct access

**Comment by stayandwait** [comment]
It would appear that vrchat just killed the ability to view other peoples public avatars

**Comment by Natsumi-sama** [comment]
> 
> 
> It would appear that vrchat just killed the ability to view other peoples public avatars

you would be correct

**Comment by Natsumi-sama** [comment]
it is what it is https://github.com/pypy-vrc/VRCX/commit/524c8dee79a2e6073988e4298bbeed8abfe32831

**Comment by Murkur** [comment]
Gonna leave this open till the next release so less of a chance to get duplicate posts

**Comment by blubbll** [comment]
rip

> > I'm getting it too
> 
> well getting your own avatar ids seems to be possible using the SDKs content manager but "show avatar author" is no longer working nither is reloading the list of your public avatars or others avatars

https://vrchat.com/api/1/avatars?user=me

**Comment by Murkur** [comment]
its already been fixed @blubbll 

> it is what it is [524c8de](https://github.com/pypy-vrc/VRCX/commit/524c8dee79a2e6073988e4298bbeed8abfe32831)

**Comment by ipoopedmypantsuups** [comment]
Looks like VRChat fucked their API. 😐 I was going to update one of my own avatars but now I can't even do that.

**Comment by Murkur** [comment]
> Looks like VRChat fucked their API. 😐 I was going to update one of my own avatars but now I can't even do that.

been fixed has yet to be released derp

**Comment by fxckedup** [comment]
This is the first time I encounter such a problem, could you please explain in more detail which files you need to download for replacement? after clicking for that link 524c8de I still did not understand :( it would be nice to get a direct link to download them

**Comment by Murkur** [comment]
> This is the first time I encounter such a problem, could you please explain in more detail which files you need to download for replacement? after clicking for that link [524c8de](https://github.com/pypy-vrc/VRCX/commit/524c8dee79a2e6073988e4298bbeed8abfe32831) I still did not understand :( it would be nice to get a direct link to download them

you cant just "download and replace" the files changed are internal Uncompiled files the error is caused by vrchat updating there API which disabled the ability to view others public avatars the way private avatars were requested for your own avatars used t he same way thats why its also broken if you want to fix these errors either you build VRCX yourself using an IDE like Visual studio with the new source code or wait for next release

**Comment by fxckedup** [comment]
> > This is the first time I encounter such a problem, could you please explain in more detail which files you need to download for replacement? after clicking for that link [524c8de](https://github.com/pypy-vrc/VRCX/commit/524c8dee79a2e6073988e4298bbeed8abfe32831) I still did not understand :( it would be nice to get a direct link to download them
> 
> you cant just "download and replace" the files changed are internal Uncompiled files the error is caused by vrchat updating there API which disabled the ability to view others public avatars the way private avatars were requested for your own avatars used the same way that's why its also broken if you want to fix these errors either you build VRCX yourself using an IDE like Visual studio with the new source code or wait for next release

got it,thx,have a good day =)

**Comment by Murkur** [comment]
@pypy-vrc think you could pin this issue till next release?

**Comment by Joanpixer** [comment]
Just go to the vrchat website
get the avtr id 
![getting avtr id](https://user-images.githubusercontent.com/54076370/114907535-73db7580-9e1b-11eb-8c5b-43fcb161da30.png)
the go to vrcx User Category and click avatar
![Getting to Avatar](https://user-images.githubusercontent.com/54076370/114907794-bc932e80-9e1b-11eb-8b52-f0464375d20a.png)
paste the avtr id
![Avatar](https://user-images.githubusercontent.com/54076370/114907936-e187a180-9e1b-11eb-9213-2c8a79dfc79e.png)
and there you have
![Avatar](https://user-images.githubusercontent.com/54076370/114908216-2b708780-9e1c-11eb-8a8d-a7b216480b8e.png)

**Comment by Joanpixer** [comment]
Just go to the vrchat website
get the avtr id 
![getting avatar](https://user-images.githubusercontent.com/54076370/114908477-6d99c900-9e1c-11eb-801f-3fff4cfbe79d.png)
the go to vrcx User Category and click avatar
![Getting to Avatar](https://user-images.githubusercontent.com/54076370/114907794-bc932e80-9e1b-11eb-8b52-f0464375d20a.png)
paste the avtr id
![Avatar](https://user-images.githubusercontent.com/54076370/114907936-e187a180-9e1b-11eb-9213-2c8a79dfc79e.png)
and there you have
![Avatar](https://user-images.githubusercontent.com/54076370/114908216-2b708780-9e1c-11eb-8a8d-a7b216480b8e.png)

**Comment by Joanpixer** [comment]
Just go to the vrchat website and get the avtr id 
![getting avatar](https://user-images.githubusercontent.com/54076370/114908637-90c47880-9e1c-11eb-8794-aba25c622330.jpg)
then go to "VRCX" User Category and click avatar
![Getting to Avatar](https://user-images.githubusercontent.com/54076370/114907794-bc932e80-9e1b-11eb-8b52-f0464375d20a.png)
paste the avtr id
![Avatar](https://user-images.githubusercontent.com/54076370/114907936-e187a180-9e1b-11eb-9213-2c8a79dfc79e.png)
and there you have
![Avatar](https://user-images.githubusercontent.com/54076370/114908216-2b708780-9e1c-11eb-8a8d-a7b216480b8e.png)

**Comment by blubbll** [comment]
@Joanpixer interesting, i didnt know there was a direct access button though. But when you have the avtr id you already have it anyway. I'd rather have it clickable from the feed or user profiles. Also you should remove that one screen, the censoring isnt done right there.

**Comment by Joanpixer** [comment]
i know i just made a new xD
my mistake

**Comment by Cranbaerry** [comment]
> Just go to the vrchat website and get the avtr id ![getting avatar](https://user-images.githubusercontent.com/54076370/114908637-90c47880-9e1c-11eb-8794-aba25c622330.jpg) then go to "VRCX" User Category and click avatar ![Getting to Avatar](https://user-images.githubusercontent.com/54076370/114907794-bc932e80-9e1b-11eb-8b52-f0464375d20a.png) paste the avtr id ![Avatar](https://user-images.githubusercontent.com/54076370/114907936-e187a180-9e1b-11eb-9213-2c8a79dfc79e.png) and there you have ![Avatar](https://user-images.githubusercontent.com/54076370/114908216-2b708780-9e1c-11eb-8a8d-a7b216480b8e.png)

This solution is giving me a weird error upon selecting the avatar.
![image](https://user-images.githubusercontent.com/16867718/168585802-80e1c1be-109c-40c6-aad7-fe5bc1a749fd.png)

**Comment by Joanpixer** [comment]
I've noticed that there's a space between the /select and the avatar id,
that may be the issue
