### ISSUE TITLE
Public avatars are no longer listable

### ISSUE THREAD

**Issue by TheCreeperCow** [pypy-vrc/VRCX#185]
Due to changes in VRC's API you can no longer view avatar details nor can you request a list of public avatars from others you can still request your own list however you need to change the implementation to no longer specify userID of yourself

**Comment by TheCreeperCow** [comment]
Closing duplicate #182

**Comment by Murkur** [comment]
Already been reported and fixed [Issue 182](https://github.com/pypy-vrc/VRCX/issues/182)
commit [commit/524c8dee79a2e6073988e4298bbeed8abfe32831](https://github.com/pypy-vrc/VRCX/commit/524c8dee79a2e6073988e4298bbeed8abfe32831)

**Comment by Murkur** [comment]
God damn just beat me to it

**Comment by ipoopedmypantsuups** [comment]
Waiting for the next release
