### ISSUE TITLE
Built VRCX using .NET Visual Studio but there's an issue

### ISSUE THREAD

**Issue by stayandwait** [pypy-vrc/VRCX#186]
I built VRCX using .NET Visual Studio from source as instructed in description.

For some reason I can't get past this. Program just displays blank screen after being opened.

What do I do to fix this? I am 
Using the current .NET 4.7.2 
OS: Windows 10 x64

![image](https://user-images.githubusercontent.com/15825041/114699010-46a1a100-9d0f-11eb-8172-66395c9f9f0d.png)

**Comment by Murkur** [comment]
Blank screen means you didnt build the HTML properlyhttps://github.com/pypy-vrc/VRCX#how-to-build-vrcx-from-source

**Comment by stayandwait** [comment]
I followed exactly how it was suppose to be built I did the .NET route and that was the result. No errors were detected when building the .exe Not sure how I would be doing it wrong.

**Comment by Murkur** [comment]
> I followed exactly how it was suppose to be built I did the .NET route and that was the result. No errors were detected when building the .exe Not sure how I would be doing it wrong.

did you copy the HTML folder to the build location?

**Comment by Natsumi-sama** [comment]
The Node.js build instructions are not optional, all build steps listed are necessary.

**Comment by stayandwait** [comment]
@Natsumi-sama ok that makes sense now.

**Comment by stayandwait** [comment]
So I followed every step and I still have the same result. Not sure what I should be doing differently. I have provided a video. 
https://www.filemail.com/d/fdzxkqfjebxjofp Has anyone else been able to successfully create the compiled version release?

**Comment by Murkur** [comment]
> So I followed every step and I still have the same result. Not sure what I should be doing differently. I have provided a video.
> https://www.filemail.com/d/fdzxkqfjebxjofp Has anyone else been able to successfully create the compiled version release?

in the Folder VRCX Master there is a HTML Folder, you need to copy this folder to the build location or else vrcx wont have any HTML to load

**Comment by Natsumi-sama** [comment]
Okay I just saw why make-junction.cmd was failing, update that and run it again. https://github.com/pypy-vrc/VRCX/commit/b716f5c6767d0b5f0931a5ba33b71e202541c610

**Comment by stayandwait** [comment]
That fixed the problem. Thank you!

**Comment by stayandwait** [comment]
Closing this
