### ISSUE TITLE
Refresh option is missing in avatars menu

### ISSUE THREAD

**Issue by stayandwait** [pypy-vrc/VRCX#187]
I am trying to see a users avatars and I don't see the refresh/reload option anymore. I usually have to hit that to make the avatars show up. Is this intentional now or just a bug?

It's here in Worlds next to total 0
![image](https://user-images.githubusercontent.com/15825041/114710736-99825500-9d1d-11eb-98fe-7aeca91a0073.png)

But not listed here in Avatars next to all checkbox
![image](https://user-images.githubusercontent.com/15825041/114710801-af901580-9d1d-11eb-9c08-8c411dd1901d.png)

**Comment by Murkur** [comment]
Please refer to [Issue 182](https://github.com/pypy-vrc/VRCX/issues/182)
