### ISSUE TITLE
Error 404 Requesting other users avatars

### ISSUE THREAD

**Issue by Murkur** [pypy-vrc/VRCX#189]
Direct access now outputs a 404 while trying to request users avatars, Favorite avatars still function fine 

![image](https://user-images.githubusercontent.com/20288698/115479367-4412e000-a216-11eb-8284-b281b0710039.png)

**Comment by Natsumi-sama** [comment]
Not sure if bug or feature lol my favorites aren't fine maybe you are just seeing cache, also seems website doesn't work either only loads own avatars

**Comment by Murkur** [comment]
its definably load cache

**Comment by blubbll** [comment]
rest in peace, /avatars endpoint

**Comment by Murkur** [comment]
> rest in peace, /avatars endpoint

Yap we will see if any workaround is possible but I don't expect much to be done for vrcx only for clients imo

**Comment by blubbll** [comment]
actually you can still request info for favorited public avatars. itll just popup a 404 but thats it, the json option still works

**Comment by Chayotea** [comment]
Does that mean if VRCX can simply favorite a avatar ID then display its info when using direct access? I guess it could do this transparently by just replacing the first avatar in favorites then grabbing the info then just automatically undo the favorite.  Or just simply add to option to favorite using a avatar ID. I can confirm you can still add favorites using other apps so it should work for public avatars at least.

**Comment by Natsumi-sama** [comment]
Well yes that would work, but no I'm not going to do that.

**Comment by blubbll** [comment]
sheeesh they even killed their own website with the change https://vrchat.com/home/avatar/avtr_363f8c35-0e3e-41fb-849e-f5e66d53d8d6

**Comment by DubyaDude** [comment]
> sheeesh they even killed their own website with the change https://vrchat.com/home/avatar/avtr_363f8c35-0e3e-41fb-849e-f5e66d53d8d6

I'll tell ya that they didn't kill it as they stated it was intentional don't expect a rollback on this one ;)

**Comment by Murkur** [comment]
> > sheeesh they even killed their own website with the change https://vrchat.com/home/avatar/avtr_363f8c35-0e3e-41fb-849e-f5e66d53d8d6
> 
> I'll tell ya that they didn't kill it as they stated it was intentional don't expect a rollback on this one ;)

Wont be a rollback thats for sure im just leaving these two issues open till theres another vrcx release that can address it in the change log.

**Comment by red1134** [comment]
This was a dumb decision on vrchat's part as some of us use this feature for genuine issues, not for ripping avatars. Like when I had a hard drive failure, I was able to recover some data to continue updating my avatars.

**Comment by Murkur** [comment]
> This was a dumb decision on vrchat's part as some of us use this feature for genuine issues, not for ripping avatars. Like when I had a hard drive failure, I was able to recover some data to continue updating my avatars.

kinda dumb to say that, you can still request your OWN avatars you cannot request OTHERS

**Comment by stayandwait** [comment]
Is there anyway public avatars can be stored differently like archived under said username? With less reliance on vrchats api to see these avatars. Does this make sense? For example someone uses an avatar by said username and they use vrcx, it is then archived and can be later discovered again in vrcx database by that username. This is just an idea.

**Comment by Murkur** [comment]
> Is there anyway public avatars can be stored differently like archived under said username? With less reliance on vrchats api to see these avatars. Does this make sense? For example someone uses an avatar by said username and they use vrcx, it is then archived and can be later discovered again in vrcx database by that username. This is just an idea.

Idea has already been thought of but doing it would require running In game mods to do so aswell as a avatar database, Mods like EMMVRC keep a record of all avatars that have been favorited by emmvrc and add it to there database which allows searching but other then that its not possible as the API no longer allows you to request avatars directly

**Comment by blubbll** [comment]
@stayandwait i dont think we need another illegal crowdsourced avatar metadata database. Theres too much already and currently you still are able to get all data you need from any avatar id you want. The game logs all downloaded avatars and you could parse their info if you really wanted, but im strongly against the idea of having another emmvrc like db that avatar creators cannot control

**Comment by Murkur** [comment]
> @stayandwait i dont think we need another illegal crowdsourced avatar metadata database. Theres too much already and currently you still are able to get all data you need from any avatar id you want. The game logs all downloaded avatars and you could parse their info if you really wanted, but im strongly against the idea of having another emmvrc like db that avatar creators cannot control

illegal? emmvrc markets itself as a "wholesome" client they dont feature any malicious uses and they even force disable certain aspects of the mod like noclip teleport and flight in worlds tagged with "Game" optionally a world creator can add a empty gameobject to the root of there world scene to disable emmvrc features regardless, and ontop of that avatar creators can request removal of there avatars from there database now that vrchat has finally shown a stance of how public avatars should be share they will be a lot more likely to listen

**Comment by Murkur** [comment]
> @stayandwait i dont think we need another illegal crowdsourced avatar metadata database. Theres too many of them already and currently you still are able to get all data you need from any avatar id you want. The game logs all downloaded avatars and you could parse their info if you really wanted, but im strongly against the idea of having another emmvrc like db that avatar creators cannot control

*currently you still are able to get all data you need from any avatar id you want. * uhhh? no your not vrchat doesn't use the API anymore for sharing avatar data they never did avatar data was shared over photon unity network on RPC event 40 and 254, the only thing that is shared is the avatars asset url and its identifier on AWS which you can only get from someone using the avatar avatar IDS no longer work as they are now in a closed endpoint

**Comment by blubbll** [comment]
@Murkur yeah but nothing about the client and the database is "wholesome". Creators have no control whether their avatars stay in their database or not. I tried it. Also most emmvrc users seem to discriminate players eg for their low fps, noclip the shit around and destroy the fun of others, theres malisciously preconfigured and cracked configs as well. And you still are able to switch into an avatar, fav it and then read their data.

**Comment by Murkur** [comment]
> @Murkur yeah but nothing about the client and the database is "wholesome". Creators have no control whether their avatars stay in their database or not. I tried it. Also most emmvrc users seem to discriminate players eg for their low fps, noclip the shit around and destroy the fun of others, theres malisciously preconfigured and cracked configs as well. And you still are able to switch into an avatar, fav it and then read their data.

what they do is wholesome as they activly stop users from trying to abuse the tools shared they are even partnered on discord, vrchat even started a huge shite storm with the entire modding community by banning mod creators in a ban wave. they ended up undoing that ban aswell as lifting perminant bans on the discord owner of EMMVRC and VRCModGroup whos was banned for over a year now.

**Comment by Murkur** [comment]
> @Murkur yeah but nothing about the client and the database is "wholesome". Creators have no control whether their avatars stay in their database or not. I tried it. Also most emmvrc users seem to discriminate players eg for their low fps, noclip the shit around and destroy the fun of others, theres malisciously preconfigured and cracked configs as well.
> And you still are able to switch into an avatar id, fav it and then read their data. How does the forcecloning work then on clients? This method still knows the avatar id from local players.

Force cloning litterally just enables the button. vrchat doesnt do anything serverside or api side to stop force cloning they just set to button to a button type that cannot be used a mod just bypasses that and allows it to be pressed and EMMVRC doesnt have forcecloning if you even say "forceclone" in there discord a bot will auto respond to you and say its considered malcious to them and they wont add it

![image](https://user-images.githubusercontent.com/20288698/116642822-b170f000-a93d-11eb-903e-ddc5f13ca716.png)

**Comment by Murkur** [comment]
there stance has not changed but they are at least now trying to work with the community community to make the game playable because how it is now its hard for a lot of long time vrchat players to continue playing the game with the issues it has which basically require mods to fix even something as simple as fixing the asset bundle manager from crapping out after its queue fails has been fixed by a mod [VRC Download Fix](https://github.com/gompocp/DownloadFix) or something more complicated like the games Inverse kinematics solver? vrchat previously said it would be impossible to fix or improve without a "full recode of the avatar descriptor" and yet that was one by one person [IK Tweaks](https://github.com/knah/VRCMods/tree/iktweaks-1.0.0#iktweaks)

**Comment by Natsumi-sama** [comment]
I am working on integrating [FavCat](https://github.com/knah/VRCMods#favcat)'s local avatar database into VRCX https://github.com/Natsumi-sama/VRCX/commit/2830667bf21ff2737f16a8b0dc26d7b52ef0f4dd

**Comment by Murkur** [comment]
> I am working on integrating [FavCat](https://github.com/knah/VRCMods#favcat)'s local avatar database into VRCX [Natsumi-sama@2830667](https://github.com/Natsumi-sama/VRCX/commit/2830667bf21ff2737f16a8b0dc26d7b52ef0f4dd)

Aye pog I was going to do that myself but with my own Cassandra based System

**Comment by blubbll** [comment]
>Fully searchable database of everything you have ever seen
@Natsumi-Sama does this mean this implementation may be able to store other users avatars full metadata they switched to from the feed or even from public user profiles (where vrcx only currently only supports seeing the avatars name, creator amd thumbnail)?

**Comment by Murkur** [comment]
> From Favcats description:
> 
> > Fully searchable database of everything you have ever seen
> 
> @Natsumi-sama does this mean this implementation may be able to store other users avatars full metadata they switched to from the feed or even from public user profiles (where vrcx only currently only supports seeing the avatars name, creator amd thumbnail)?

pretty sure it would vrcx usually fills in the blanks and auto fills avatars a user has if its been cached so that would include json as public avatars still DO use the api as its required for pedestals to work

**Comment by Natsumi-sama** [comment]
FavCat has been updated since then it used to log everything but now it ONLY logs avatar pedestals and avatars you have switched to https://github.com/knah/VRCMods/commit/333a140d2d15fd314e7dd713cd2144737366c334

**Comment by Murkur** [comment]
> FavCat has been updated since then it used to log everything but now it ONLY logs avatar pedestals and avatars you have switched to [knah/VRCMods@333a140](https://github.com/knah/VRCMods/commit/333a140d2d15fd314e7dd713cd2144737366c334)

"wholesome"

**Comment by Murkur** [comment]
![yvEimJXVLf](https://user-images.githubusercontent.com/20288698/116644099-7cb26800-a940-11eb-85e8-bf93976e752e.gif)
I meant this 

> > From Favcats description:
> > > Fully searchable database of everything you have ever seen
> > 
> > 
> > @Natsumi-sama does this mean this implementation may be able to store other users avatars full metadata they switched to from the feed or even from public user profiles (where vrcx only currently only supports seeing the avatars name, creator amd thumbnail)?
> 
> pretty sure it would vrcx usually fills in the blanks and auto fills avatars a user has if its been cached so that would include json as public avatars still DO use the api as its required for pedestals to work

**Comment by Natsumi-sama** [comment]
The only avatar cache data VRCX can fetch is avatars stored in your favorites and your own avatars.

**Comment by Murkur** [comment]
> The only avatar cache data VRCX can fetch is avatars stored in your favorites and your own avatars.

ahh damn that explains why it still has favorites

**Comment by red1134** [comment]
> > This was a dumb decision on vrchat's part as some of us use this feature for genuine issues, not for ripping avatars. Like when I had a hard drive failure, I was able to recover some data to continue updating my avatars.
> 
> kinda dumb to say that, you can still request your OWN avatars you cannot request OTHERS

1: Idk why you have to be such an asshole about it
2: requesting my own avatars on the latest release ALSO doesn't work

**Comment by Murkur** [comment]
> > > This was a dumb decision on vrchat's part as some of us use this feature for genuine issues, not for ripping avatars. Like when I had a hard drive failure, I was able to recover some data to continue updating my avatars.
> > 
> > 
> > kinda dumb to say that, you can still request your OWN avatars you cannot request OTHERS
> 
> 1: Idk why you have to be such an asshole about it
> 2: requesting my own avatars on the latest release ALSO doesn't work

1. assuming that im being an asshole over a text chat internet 101 failed.
2. it does work but that's only for the unbuilt versions your going to have to wait for the next release of VRCX or you can try building it yourself with Visual Studio [Build Instructions](https://github.com/pypy-vrc/VRCX#how-to-build-vrcx-from-source)
