### ISSUE TITLE
[Feature Request] Cache instance ids

### ISSUE THREAD

**Issue by blubbll** [pypy-vrc/VRCX#192]
so you can join ones that are full

**Comment by Natsumi-sama** [comment]
I don't this will be useful because if the instance isn't being reported by the API then player count will be inaccurate, so it will just end up being a large list of likely dead instances.

**Comment by blubbll** [comment]
Well, most of the instances in my case were full for some more hours. If i wanted to visit them i always had to write down their ids and use the create new instance button and enter the id then send myself an invite to those

**Comment by Murkur** [comment]
aint this basically what reading output log does? just  find the instance in vrcx game log and just invite yourself back?
