### ISSUE TITLE
synchronisation bug in VRCX

### ISSUE THREAD

**Issue by borrougagnou** [pypy-vrc/VRCX#193]
Hello,
I see a weird synchronisation bug into VRCX this 2 week
(same after a VRCX reboot)
I see people disconnect in VRCX but connected in "Private" world
or people in private world but offline in VRCX

or some "feed" who aren't showed, so weiiirdly... (like people begin online but not appear on "feed" list)

I don't know if you have the same problem as me

**Comment by Murkur** [comment]
This is vrchat itself its API has been a bit spotty recently its not an issue caused by VRCX its an issue caused by VRChats own servers

**Comment by borrougagnou** [comment]
ok, thank you for your answer ^^

it was just for know if I were alone with this problem or not.
