### ISSUE TITLE
Any way to define the large image key for rich presence?

### ISSUE THREAD

**Issue by BreadDoesStuff** [pypy-vrc/VRCX#195]
I'm trying to define a large image for the discord rich presence but no matter what I did my rich presence always shows up without an image. Any idea how I can go about adding in my own images for the rich presence?

**Comment by Natsumi-sama** [comment]
Set app id here https://github.com/pypy-vrc/VRCX/blob/master/Discord.cs#L81 
Add line here https://github.com/pypy-vrc/VRCX/blob/master/html/src/app.js#L5858 `Discord.SetAssets('largeImageName', `hoverText`, 'smallImageName', 'hoverText);`

**Comment by BreadDoesStuff** [comment]
> Set app id here https://github.com/pypy-vrc/VRCX/blob/master/Discord.cs#L81
> Add line here https://github.com/pypy-vrc/VRCX/blob/master/html/src/app.js#L5858 `Discord.SetAssets('largeImageName', 'hoverText', 'smallImageName', 'hoverText);`

Thank you so much! It works.
