### ISSUE TITLE
Launch

### ISSUE THREAD

**Issue by Chayotea** [pypy-vrc/VRCX#199]
Launching an instance with VRCX no longer works. Copy and pasting the link to the browser launches properly.

Seems the recent update and the "installer tool" that makes VRChat urls work have changed something.

**Comment by Natsumi-sama** [comment]
Already fixed will be in next release. https://github.com/pypy-vrc/VRCX/commit/133368a326aec397449e3ca733631df7d7a70978

**Comment by Chayotea** [comment]
Oh I see that the update for normal releases went from 1078 to 1088 so the bug would only surface recently.
