### ISSUE TITLE
[Feature Request] Implement 2fa directly inside vrcx

### ISSUE THREAD

**Issue by blubbll** [pypy-vrc/VRCX#200]
Since it's a mathematical feature only, it could also be implemented on the clientside to bypass the need to enter the code every time. While this may compromise the local security of your computer, it adds a lot of comfort while still keeping the account safe from remote attacks that bypass the "you logged in from another location" prompt.

**Comment by Natsumi-sama** [comment]
This completely defeats the point in having 2FA and you could use a password manager many have this feature already built in.
