### ISSUE TITLE
New update 

### ISSUE THREAD

**Issue by fxckedup** [pypy-vrc/VRCX#201]
when extracting and opening vrcx, the file is deleted and a virus is found that forces you to restart PC =(

**Comment by Natsumi-sama** [comment]
What anti virus?

**Comment by fxckedup** [comment]
> What anti virus?

Avast, problem name - cefsharp.browser subprocess

**Comment by Natsumi-sama** [comment]
["Not the first time CefSharp has been flagged, probably won't be the last."]https://github.com/cefsharp/CefSharp/issues/1922#issuecomment-276279577
[Relevant Video](https://www.youtube.com/watch?v=bKgf5PaBzyg)
