### ISSUE TITLE
[Feature Request] Windows 'toast' notifications.

### ISSUE THREAD

**Issue by Curtis-VL** [pypy-vrc/VRCX#202]
Hi PyPy,

It'd be great to see VRCX support pushing Windows toast notifications, this way it would support OVR Toolkit's notifications displaying as well as that of XSOverlay.

(OVR Toolkit simply uses a Windows notifications listener and displays all notifications of type 'toast', this is basically any that appear in the bottom right of Windows)

**Comment by Natsumi-sama** [comment]
It already does and has for a long time...
![Untitled](https://user-images.githubusercontent.com/11171153/117528669-70589a00-b027-11eb-8b7f-c0328958919e.png)
