### ISSUE TITLE
Wrist overlay and notifications do not work in latest release

### ISSUE THREAD

**Issue by Demez** [pypy-vrc/VRCX#203]
Had to rollback to the previous release to get the wrist overlay and notifications working again, which is a very nice feature.

**Comment by Natsumi-sama** [comment]
I just tested this with no suck issues makes sure these options are enabled and that you have adjusted the filters.
![Untitled](https://user-images.githubusercontent.com/11171153/117529096-bca4d980-b029-11eb-9f06-7821b4ce410b.png)

**Comment by Demez** [comment]
Yeah it's still not working for me, even on a fresh extract of it, not overwriting the previous version, and I definitely have all the same settings applied.

**Comment by Demez** [comment]
does it not work on older versions of Steam VR anymore maybe? im still using Steam VR 1.15.12 on the oculus_win7and8 branch (i am on windows 10, just never updated the oculus software yet lmao), though i should really just update it, might do that tomorrow.

**Comment by Natsumi-sama** [comment]
Hmmm maybe, I did update the OpenVR SDK but I haven't had time to test a fresh install yet.

**Comment by Demez** [comment]
Ok apparently the oculus software did update a while ago apparently and i never noticed, so i switched to the normal Steam VR beta branch and now the overlay works fine lol
