### ISSUE TITLE
Config.json editor doesn't appear at all

### ISSUE THREAD

**Issue by Asovrix** [pypy-vrc/VRCX#204]
Might be an issue only on my end, but pressing the newly added **VRChat config.json** button doesn't do anything for me (no window of any kind appears, as if I did nothing).
I tried running VRCX as admin, running a new installation (unpacking contents of VRCX archive to a new folder and running it there). None of these change the behavior in any way.

How can I gather more info to help figure out what's going on?

**Comment by Natsumi-sama** [comment]
Any errors in the console when you press Ctrl + Shift + I?

**Comment by Asovrix** [comment]
![VRCX_2021-05-09_12-33-39](https://user-images.githubusercontent.com/44006686/117568815-d6462f80-b0c2-11eb-98fc-63d294a02f1f.png)
Only this upon pressing that button.

**Comment by Natsumi-sama** [comment]
Oh your Config.json might be invalid JSON, try copy the contents of your Config.json into this website and click Validate JSON https://jsonlint.com/

**Comment by Asovrix** [comment]
Ohhhh...😅 Turns out I was missing commas at ends of multiple lines which I have added myself.
Wasn't aware that it was invalid JSON, since VRChat app accepted them and any other changes after them just fine.
After updating my config.json editor in VRCX appears as it should, so this has been solved.

**Comment by Natsumi-sama** [comment]
Nice 👌 I will add an error message to inform the user of invalid JSON.
