### ISSUE TITLE
Token auth error, any solution?

### ISSUE THREAD

**Issue by Rezoseansstudios** [pypy-vrc/VRCX#206]
Tried running administrator, and since the error pops up, it won't let me use login with steam 
![image](https://user-images.githubusercontent.com/24687503/119172855-6a55b680-ba34-11eb-8dc9-c0ea4bf34e6b.png)

**Comment by Natsumi-sama** [comment]
If you haven't already I recommend making VRChat account on their website and then linking it to your steam and sign in with that.
