### ISSUE TITLE
Notifications issue since latest vrcx update

### ISSUE THREAD

**Issue by fwenny** [pypy-vrc/VRCX#207]
Since last vrcx update, no matter where i am, even private, i keep getting "friendname is joining error"

i think its because they joining last map i was, but thats not consistent.

**Comment by Natsumi-sama** [comment]
Can you send a screenshot of your notification filters also which error are you getting and is the error in a separate notification or the same one?

**Comment by fwenny** [comment]
hello. i have them all on the last value.
![image](https://user-images.githubusercontent.com/44194453/119353457-97f86500-bcab-11eb-982f-bc97e308e481.png)

and im not getting any errors. im simply getting the notification message "FriendName is joining...", because i have OnPlayerJoining enabled. problem is, im in a private, and i believe they are joining the last world i was in.
but like i said, its not consistent. i dont get the notification for every friend.

**Comment by fwenny** [comment]
heres the notification filters as well if that matters
![image](https://user-images.githubusercontent.com/44194453/119353667-d68e1f80-bcab-11eb-897b-194ea6693e90.png)

**Comment by Natsumi-sama** [comment]
Hmmm it should work regardless if you are in a private world or not, does your gamelog stop updating?

**Comment by Natsumi-sama** [comment]
Being in a private world makes zero changes the functionally of this area of the program. I'm asking you if the game log continues to update when this happens, meaning are new Location/OnPlayerJoined logs being listed in either the main window gamelog tab or the wrist feed, because if they aren't that will be the cause.

**Comment by fwenny** [comment]
I havent checked too closely, but Im assuming that yes.
Checking my own profile says that Im in the correct world, so it shouldnt pop any player joining notificaitons.
