### ISSUE TITLE
Failed to process file

### ISSUE THREAD

**Issue by untuned** [pypy-vrc/VRCX#208]
When downloading a world asset to my cache, it fully downloads and then errors out with the message "Failed to process file".
My VRCX is on the latest commit, ec1e42245f37e0af3d5d4d63a9bb7f5d18996fc5.

`$app.debug = true;` shows no errors as well?

**Comment by Natsumi-sama** [comment]
Have you recompiled both .NET and node.js after updating?

**Comment by untuned** [comment]
> Have you recompiled both .NET and node.js after updating?

Yes, I run the build script to make the zip file and overwrite my old directory.

> Could try revert this commit: [b65131a](https://github.com/pypy-vrc/VRCX/commit/b65131a207472beaa158ff4fa62e4bb37dae5182)

I went to commit 17b8b1b29e2d2d5ba2f4c79022f75a877b4e2c97, and it still failed to process.

> Could also try download https://github.com/ZettaiVR/AssetBundleCacher/releases and overwrite the AssetBundleCacher folder in VRCX

This worked, but the file `UnityPlayer.dll` is in the folder now. This might be why?

**Comment by Natsumi-sama** [comment]
``UnityPlayer.dll`` _should_ get copied from your VRChat game folder on first download, might be something wrong with the xcopy command either way I will look into it.

**Comment by untuned** [comment]
Tried a fresh copy of the latest release, and it did not get copied unfortunately. The difference is that my VRChat install isn't on the C drive, instead a hard disc on D.

**Comment by Natsumi-sama** [comment]
Can you run `install.exe` from inside your VRChat installation folder and see if that fixes it?

**Comment by untuned** [comment]
> Can you run `install.exe` from inside your VRChat installation folder and see if that fixes it?

Running it doesn't show a pop-up or anything... but *seemed* to have fixed it? Might have just been something on my end.
