### ISSUE TITLE
400 Bad request when using Notifications + Recieving blank incoming notifications

### ISSUE THREAD

**Issue by Legoman99573** [pypy-vrc/VRCX#209]
Using VRCX build from the master branch as of commit ``de8aee5bc05955c44cd4375c693ba657fbb0c5e4``

When going to the notification tab, I am greeted with a 400:
![VRCX_fgGhIIYPix](https://user-images.githubusercontent.com/7460704/119592325-df5f1e00-bd9d-11eb-9c7e-85ce429a5643.png)

Also when getting a notification, they are just blank:
![VRCX_plbciRy8OV](https://user-images.githubusercontent.com/7460704/119592355-f0a82a80-bd9d-11eb-941f-7af6ff8afa65.png)

**Comment by Murkur** [comment]
ahaha fkn fusl

**Comment by pypy-vrc** [comment]
fixed by commit 1efb88acb080f4f5aa4a0f4faac6279b00ae9ad0
