### ISSUE TITLE
Where do I put the html folder/where is the path for the executable to put it?

### ISSUE THREAD

**Issue by akmat420** [pypy-vrc/VRCX#21]
I have the same problem as the other person, when I run it in visual studio the vrcx window pops up but it’s just white. I’m new to this sort of stuff so I don’t know where/what the path for the executable is so I’m confused as to where to put the html folder. If you could help that would be great because this seems really useful but I just can’t figure it out.

**Comment by Murkur** [comment]
that means you currenty dont have a HTML folder inside of the main folder there is a folder called HTML copy this folder into (depending on your build settings) \bin\x64\Debug
or \bin\x64\Release

**Comment by akmat420** [comment]
thank you so much! Got it working now. (:
