### ISSUE TITLE
Trying to cache a world manually or automatically errors out with "VRChat can't be located"

### ISSUE THREAD

**Issue by OctoFloofy** [pypy-vrc/VRCX#210]
I'm not sure why this is happening. I've both the Steam and Oculus version of VRC installed.

**Comment by Natsumi-sama** [comment]
Try download https://github.com/ZettaiVR/AssetBundleCacher/releases/download/v1.1/AssetBundleCacherBuild_1.1.zip and overwrite the AssetBundleCacher folder in VRCX, it only needs to locate the game to fetch ``UnityPlayer.dll`` but you can put it there manually instead.

**Comment by OctoFloofy** [comment]
Ok thanks, that fixed it! Seems some files were missing.
