### ISSUE TITLE
On trying to launch, an error occurs.

### ISSUE THREAD

**Issue by Flicker-Fall** [pypy-vrc/VRCX#211]
when trying to launch VRCX.exe after unzipping it, the following error occurs:

code = CantOpen(14), message = 
System.Data.SQLite.SQLiteException (0x800007FF): unable to
open database file 
 System.Data.SQLite.SQLite3.Open(String strFilename, 
String vfsName, SQLiteConnectionFlags connectionFlags, 
SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, 
Boolean usePool) 
 at System.data.SQLite.SQLiteConnection.Open() 
 at VRCX.Program.Run() in 
C:\Work\VS2019\VRCX\Program.cs:line 40 
 at VRCX.Program.Main() in 
C:\Work\VS2019\VRCX\Program.csline 25

This looks to happen regardless of the version being used (or at least that's what we understand so far after attempting to use both versions 20210507 and 20210404_1).

**Comment by Natsumi-sama** [comment]
This error is normally due to anti virus or lack of permissions, try run it from your desktop.

**Comment by Flicker-Fall** [comment]
Looks like it was anti-virus, thanks for your help.
