### ISSUE TITLE
VRCX HAS RANSOMWARE, DO NOT DOWNLOAD

### ISSUE THREAD

**Issue by Tazaur** [pypy-vrc/VRCX#212]
Update  v2021.05.26
VRCX trying to create a backdoor here: HKLM\SOFTWARE\Microsoft\Windows Media Player NSS\3.0\Servers\A20D59A1-82AD-4340-A4AB-FBFC460800A5\FriendlyName

![IMG_20210530_030635_319](https://user-images.githubusercontent.com/78064135/120096990-d77fe080-c0f3-11eb-93e8-0ae45626eafa.jpg)

**Comment by Natsumi-sama** [comment]
Baseless accusation with zero proof, feel free to reopen if that changes.

**Comment by pypy-vrc** [comment]
https://www.virustotal.com/gui/file/aa82e38613d4fb6234914318d975eb462a933e05ee94c0cbbca8a2769184c498/detection
🤷

**Comment by Legoman99573** [comment]
When you download from a random person without using releases or compiling the master branch yourself 🤣🤣🤣
