### ISSUE TITLE
Orange status remains for yourself regardless if you change it

### ISSUE THREAD

**Issue by Legoman99573** [pypy-vrc/VRCX#213]
This seems like a visual bug, but when you change your status, it seems regardless it shows as orange in the VRCX application. When checking in game and on the website, it shows correctly and will show correctly in VRCX when preparing to change your status, but remains to stay orange still.

VRCX side:
![image](https://user-images.githubusercontent.com/7460704/120124411-093b8a80-c17a-11eb-9971-4a84470a2236.png)

Website side:
![image](https://user-images.githubusercontent.com/7460704/120124449-240dff00-c17a-11eb-9d6c-c8a31a6f7e62.png)

**Comment by Natsumi-sama** [comment]
This is yellow status not orange, meaning VRCX thinks your active not online, are you using an alt account or is this instance of VRCX running on a second computer?

**Comment by Legoman99573** [comment]
Running on the same computer on the same account.
