### ISSUE TITLE
[Feature request] Use a Primary Password to protect stored passwords

### ISSUE THREAD

**Issue by GizmoOAO** [pypy-vrc/VRCX#219]
Use a Primary Password to protect stored passwords.
It removes the risk of a data breach.

**Comment by GizmoOAO** [comment]
![](https://user-images.githubusercontent.com/20385106/121334749-86ba8400-c94c-11eb-95d7-c4125b1e7043.png)
stored passwords in plaintext is disturbing

**Comment by Natsumi-sama** [comment]
I agree but that's why it's off by default it was originally added just to fix the auth cookie constantly expiring.
