### ISSUE TITLE
Messaging error

### ISSUE THREAD

**Issue by akmat420** [pypy-vrc/VRCX#22]
I’m probably just a dumbass and did something wrong again lol. But when I try to send a message I get an error saying “501 not implemented. The endpoint you’ve contacted has not been completed, yet.” Do you know how I could fix this?? Thanks again for the help earlier btw

**Comment by Fusl** [comment]
The messaging endpoint has been shut off by the VRChat team. There are two PRs, #12 and #19, that discuss the further development of a workaround using invites to send messages.

**Comment by akmat420** [comment]
Oops didn’t see that, thanks. I just had to replace the new app.js
