### ISSUE TITLE
[Feature request] Infinite feed/game logs

### ISSUE THREAD

**Issue by Kieaer** [pypy-vrc/VRCX#220]
I think it might be better to use file save...

**Comment by Kieaer** [comment]
한글로 적어도 되나..?
이걸로 친구가 예전에 찾아왔던 날짜 또는 아바타 복사 핵을 사용하는 유저를 찾아낼 수 있습니다. 있으면 좋겠어요!

**Comment by geshii** [comment]
You mean, saving the logs to a file?

**Comment by Kieaer** [comment]
@geshii Yeah.

**Comment by OptoCloud** [comment]
Maybe dont do it by default, but have a toggle to write to external log files?
I prefer having everything neatly in a DB.

**Comment by Natsumi-sama** [comment]
It will be stored in SQLite.

**Comment by Kieaer** [comment]
3일밖에 가지 않는 로그... 엉엉
