### ISSUE TITLE
vrcx making me look like i am offline

### ISSUE THREAD

**Issue by cr1ptik** [pypy-vrc/VRCX#221]
whenever I have vrcx open while I am playing vrchat, my friends all see me as offline, this is only a problem with vrcx as I have tried with and without it running and it is definitely causing problems not anything else.

**Comment by cr1ptik** [comment]
![unknown](https://user-images.githubusercontent.com/68492220/121477826-2b54ba00-c97d-11eb-92db-a750d50512e9.png)

**Comment by Natsumi-sama** [comment]
Are you a Quest user?

**Comment by cr1ptik** [comment]
> Are you a Quest user?

no

**Comment by Natsumi-sama** [comment]
I have no idea then I have never had this issue myself or heard of anyone having it, VRCX does nothing more than what the website does while its running so if this problem only occurs while VRCX is running it should also occur while the website is open and if that's the case it's a VRChat bug. But I'm betting this will be a classic case of the VRChat social menu not updating.

**Comment by cr1ptik** [comment]
no, i tried with vrchat with an alt running on a laptop and it only happened with vrcx, also they fixed the social menu bug for now with the identity update.

**Comment by Georninja** [comment]
I had this issue with an older version of VRChat. Now I don't run into this problem anymore.
