### ISSUE TITLE
Max Favorite slot count to match latest update

### ISSUE THREAD

**Issue by slord399** [pypy-vrc/VRCX#223]
According to latest release note,
Favorite slot for world and avatar has been increased to 64 instead 32 which is great.

On VRCX, it is still limited to 32 only and cannot assign 33rd favorite at the moment.

(Non-urgent patch to work on but just as issue tracker for showing here.)
[Ref](https://docs.vrchat.com/docs/latest-release)

**Comment by Natsumi-sama** [comment]
It's been in the code for a while now just not a release for it yet. https://github.com/pypy-vrc/VRCX/commit/8198d2a4fc6bd2ba2df9bb30bc6b25aa5b5fa8d2

**Comment by slord399** [comment]
ahh, I thought that but thank you for letting me know. (anyway, opened for case track so be fine.)
