### ISSUE TITLE
[Feature Request] Auto-accept friend requests

### ISSUE THREAD

**Issue by Realmlist** [pypy-vrc/VRCX#228]
Hi,

I use a bot account that people can add as friend and join upon to join VRC events we make.
I would be very neat if VRCX could auto-accept friend requests, so I don't have to manually accept them, or even miss them.

**Comment by Murkur** [comment]
that seems kinda useless, (hi you need to be accepted to join our event "accepts everyone regardless")

**Comment by Realmlist** [comment]
It's a friends+ instance, but not everyone has friends in the instance, so they join on the bot...
We don't do public instances for various reasons.

**Comment by geshii** [comment]
Auto-accepting friend requests isn't against the TOS ?
(Sorry for bad english btw)

**Comment by ScruffyRules** [comment]
Honestly this could just be done by writing your own tool in any language you like, I don't think it should be added to VRCX.

**Comment by GizmoOAO** [comment]
Maybe add plugin support for VRCX, But it's not easy.

**Comment by Realmlist** [comment]
> Honestly this could just be done by writing your own tool in any language you like, I don't think it should be added to VRCX.

I would if I could, hah.

**Comment by geshii** [comment]
> 
> 
> > Honestly this could just be done by writing your own tool in any language you like, I don't think it should be added to VRCX.
> 
> I would if I could, hah.

There are already bots that can do that iirc, like this one https://github.com/AsafRosen/VRChatActiveInstancesBot

**Comment by Natsumi-sama** [comment]
This would be easy to add but I also don't think it should be added especially when there are other tools more fitting for the job.

**Comment by geshii** [comment]
> 
> 
> This would be easy to add but I also don't think it should be added especially when there are other tools more fitting for the job.

Yes, and also the fact that it may be considered as botting

**Comment by Realmlist** [comment]
> This would be easy to add but I also don't think it should be added especially when there are other tools more fitting for the job.

If you know any of them, please let me know! I'm looking for this kind of functionality.

**Comment by geshii** [comment]
You can use this : 
https://github.com/AsafRosen/VRChatActiveInstancesBot
It's a Discord VRChat bot used for seeing the active instances, but it also auto-accepts the friend requests

Let me explain how to use it. 
So First of all, you need NodeJS on your computer. Install it here : https://nodejs.org/en/
Then, you need Git : https://git-scm.com/

Open a command prompt and type `git clone https://github.com/AsafRosen/VRChatActiveInstancesBot.git`
You can then go in the folder created by doing `cd VRChatActiveInstancesBot`
Create a file named `.env` and type the following inside of it : 
```env
DISCORD_CLIENT_TOKEN=
DISCORD_ACTIVITY_STATUS_CHANNEL=

VRCHAT_BOT_USERNAME=
VRCHAT_BOT_PASSWORD=
```
Put your info in there. To get a bot token head to https://discord.com/developers and create an application, then go on Bot and click enable. To invite your bot to your server you'll have to copy the Client ID and head to https://discordapi.com/permissions.html (click on Admin, then put your ID and click on the link that it will generate)

Then to install the dependencies in your cmd type `npm install` and wait
Then to start the bot type `npm run start`

Hope this will help ^^' Tell me if you have questions and if you need help

**Comment by Realmlist** [comment]
Thank you for the explanation @geshii !
I'll set it up and remove the Discord part later.
