### ISSUE TITLE
[feature request] add regions defaults

### ISSUE THREAD

**Issue by Fapo39** [pypy-vrc/VRCX#229]
Add a region defaults in settings or on this tab 
![image](https://user-images.githubusercontent.com/46174638/122779345-71cbe200-d2b6-11eb-8e91-24aac827de67.png)
Where you can choose between NA/EU/JP regions that got recently introduced, from what I saw from normal strings it's ~region(jp) // ~region(na) // ~region(eu) in between master user ID and nonce

**Comment by Natsumi-sama** [comment]
Already done just isn't a release for it yet https://github.com/pypy-vrc/VRCX/commit/afe7fa98aaeef7196138449abbdff696860cee61
![Screenshot_1](https://user-images.githubusercontent.com/11171153/122780860-59ce7f80-d303-11eb-97d5-83fcaa0a9b3d.png)
