### ISSUE TITLE
Legendary User rank issues and a possible suggestion

### ISSUE THREAD

**Issue by abbeybabbey** [pypy-vrc/VRCX#232]
### <p align="center">The Issue</p>
I've recently noticed that vrcx can show some people who haven't even reached "system_trust_legend" or a "Veteran User" rank for short as a "Legendary User" since I assume you only check for a string "system_legend" in tags[] array to determine if a user is "legendary". 
![image](https://user-images.githubusercontent.com/61197745/123841831-55602300-d910-11eb-98d9-747f330cd760.png)
This finding came to me when I've used in game boolean to determine if user has a legendary rank (Veteran User) + "system_legend" tag and noticed that one of my friends doesn't meet this criteria,
![image](https://user-images.githubusercontent.com/61197745/123841969-80e30d80-d910-11eb-866d-f17ec71bcea6.png)
but they're being shown as a legendary user on VRCX.
![image](https://user-images.githubusercontent.com/61197745/123841999-88a2b200-d910-11eb-9bda-ea12dc1e1016.png)
### <p align="center">The Suggestion</p>
Making the requirements for "Legendary User" more stricter like in this case above, checking for other tags for example like this:
```csharp
if (user.tags.Contains("system_legend") && user.tags.Contains("system_trust_legend") && user.tags.Contains("system_trust_trusted"))
{
    return TrustRanks.Legendary;
}
```

> I know this issue is little bit over too top since the game itself doesn't use "system_legend" at all and it's not even broadcasted through the APIUser class in game (meaning unless you manually fetch the user in game, you can't even see the tag). But since they still haven't removed these tags from people's accounts, probably because they were auto assigned to people when trust system was in development by the API itself. I think this would be quite the nice addition to it in overall.

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/commit/7f2acf69ff1b8d392ea912faa47a5f8a938ef043
