### ISSUE TITLE
Sign Languages not shown on VRCX

### ISSUE THREAD

**Issue by Float3** [pypy-vrc/VRCX#234]
![image](https://user-images.githubusercontent.com/86748455/124036692-b108da00-d9fe-11eb-8fb6-44422d7d7029.png)
![image](https://user-images.githubusercontent.com/86748455/124036704-b49c6100-d9fe-11eb-82d5-0bcb3af85f29.png)

none of the sign languages are currently supported on vrcx

![image](https://user-images.githubusercontent.com/86748455/124036803-e31a3c00-d9fe-11eb-95c9-e9d74f2fd474.png)

**Comment by Natsumi-sama** [comment]
Yes it has since been added and will be in next release.

**Comment by Float3** [comment]
ah thank you.
sorry i should have checked the code release first.
