### ISSUE TITLE
Prevent blocking VRChat devs

### ISSUE THREAD

**Issue by daalta** [pypy-vrc/VRCX#237]
The functionality to ban devs via VRCX should be removed to prevent users from getting themselves banned.

# Description

Currently it is possible to block (or mute) VRChat devs with VRCX.

This is not possible in VRChat, as the mute and block buttons will be grayed out.

Blocking a dev via VRCX may thus lead to an in-game ban, manually or automatically. Which, uh, is bad! That functionality should probably be removed to protect users.

**Comment by ScruffyRules** [comment]
You should have tried, I just tested and it doesn't allow you to block them, it throws an error.

**Comment by Murkur** [comment]
yeahhh just because the button is there doesn't mean its possible API response says otherwise 
![image](https://user-images.githubusercontent.com/20288698/124858065-61d12500-df7b-11eb-876b-81b6f454142b.png)

**Comment by daalta** [comment]
Ah, perfect! Didn't have the bravery to try that button myself.

That that case, how about hiding the button for users which cannot be blocked? Should I open a new issue for this, or re-name this one?
