### ISSUE TITLE
Sort Private to Bottom doesnt update properly

### ISSUE THREAD

**Issue by fwenny** [pypy-vrc/VRCX#238]
When turning sort to private on, it sorts all privates to the bottom.
But when a person exits private, they stay at the bottom instead of being sorted back up into non-private fields.

I think sort GPS to top has an issue as well. Im not a 100% sure what it suppose to do, but when a person moves to a different world, it seem to sort them to the bottom with the privates rather to top.

**Comment by Natsumi-sama** [comment]
Hmmm are you using sort by alphabetical or online for?

**Comment by fwenny** [comment]
Heres my settings:
![image](https://user-images.githubusercontent.com/44194453/125072056-c2b74500-e0c2-11eb-98f5-fb1b7ce8ccc1.png)

**Comment by Natsumi-sama** [comment]
ah okay as a temporary fix I think online for should work fine.
