### ISSUE TITLE
tts voices

### ISSUE THREAD

**Issue by FoxFireVR** [pypy-vrc/VRCX#239]
up untill i did the latest updat i could use my ivona sapi5 voices , but since update i can only use micosoft voices , is there a workaround or am i missing something ?? i kinda would like to e able to use them again if at all possible

**Comment by Natsumi-sama** [comment]
Wow I had no idea those even worked... nothing changed apart from cef/chromium version 90.6.50 to 91.1.210, maybe by digging around the change logs might be able to find the cause.

**Comment by FoxFireVR** [comment]
Maybe I'm not updating it properly but like it worked I did update and then the only options were Microsoft ones and I was quite sad cause there horrible voices

**Comment by Natsumi-sama** [comment]
Can you test if the previous version still has the ivona sapi5 voices?

**Comment by FoxFireVR** [comment]
Yes I will in a few moments

**Comment by FoxFireVR** [comment]
have tested and can confirm worked in previous version
![4oIgFOs](https://user-images.githubusercontent.com/87218872/125163486-bdf69d80-e163-11eb-821f-f96c059ef937.png)

**Comment by Natsumi-sama** [comment]
Okay I think I have mostly figured it out it seems to be due to this commit https://chromium.googlesource.com/chromium/src/+/5411d7bd073a64b5f6b7c98d038744b7a1061d19%5E%21/#F0
Chromium 90 lists SAPI voices but Chromium 91 lists OneCore voices. Looks like this commit was supposed to allow for SpeechSynthesis to use both but for some unknown reason it doesn't.

**Comment by FoxFireVR** [comment]
U are so much smarter than me , I spent 6 hours trying to figure out avatar stuff that u could do in ur sleep lol ,

**Comment by Natsumi-sama** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/2767959/2..4/content/browser/speech/tts_win.cc#b501
Ah looks like OneCore is supposed to return SAPI voices additionally but doesn't. Nah this bug is way over my head haha.

**Comment by Natsumi-sama** [comment]
Okay I got it! I found a script that adds all OneCore voices to SAPI and reversed it to add all SAPI voices to OneCore and it somehow worked... so if you run this powershell script as admin then restart VRCX it should show all previously installed SAPI voices as well as the current OneCore voices, this has been quite the rabbit hole.
https://gist.github.com/Natsumi-sama/5b73622158b32ad56460865d38c7e19e
