### ISSUE TITLE
Messages Are Broken

### ISSUE THREAD

**Issue by Controser** [pypy-vrc/VRCX#24]
Every time I try and send a message (whether to friends or random individuals) I get an error message which states "501 Not Implemented - The endpoint you've contacted has not been completed yet." as shown in the pictures attached below. Is there a fix for this? Being able to send people messages in VRChat without having to be in game was extremely useful for me.

![MessageAttempt](https://user-images.githubusercontent.com/46281978/71482509-f5b52300-2813-11ea-9fee-7c8d8538d010.png)
![MessageFail](https://user-images.githubusercontent.com/46281978/71482510-f5b52300-2813-11ea-9a19-53063898228e.png)

**Comment by Murkur** [comment]
messages dont work as the endpoint was removed by VRCHAT because they suck please refer to my pull request [https://github.com/pypy-vrc/VRCX/pull/19](url)

**Comment by pypy-vrc** [comment]
It was provided as an unofficial feature, but it is now obsolete. An alternative is to modify the invite message, but I, personally, don't recommend it.
