### ISSUE TITLE
feature suggestion: have an option to display status and gps together in feed

### ISSUE THREAD

**Issue by aqocyrale** [pypy-vrc/VRCX#242]
rationale: when the user goes into gps(private) it can have one of multiple reasons
1. the user changed to orange(ask me) or red(busy) status
2. the user joined a friends(from not friend) / invite+ / invite instance
those are inherently different pieces of information

for example if a user changes from green(online) to orange(ask me) while in a public/friends+ instance, you can assume the user is still there for a while, whereas if a user changes from green(online)/friends+ to green(online)/private you know 100% that the user left to a different instance

so, the suggestion is:
have an option in the settings (boolean) so that in the vrcx Feed section, status and gps display together instead of on separate lines

current:
![image](https://user-images.githubusercontent.com/17656189/125198168-7eb27480-e269-11eb-9f27-424ff734536d.png)

new (after suggestion):
![image](https://user-images.githubusercontent.com/17656189/125198175-84a85580-e269-11eb-8069-7bed870a63ab.png)

**Comment by Natsumi-sama** [comment]
This would require separating status and status description into their own types, I will look into this some other time but it may not be worth the amount of work it would require to achieve.

**Comment by aqocyrale** [comment]
do you accept merge requests if I were to submit the code for this kind of change?

**Comment by Natsumi-sama** [comment]
Depends on many things, but for the most part if I think it's an improvement I will merge it.

**Comment by aqocyrale** [comment]
fair enough, got it
