### ISSUE TITLE
[Bug? Feature?] "assetUrl" no longer exists for public avatars

### ISSUE THREAD

**Issue by Lupsoris** [pypy-vrc/VRCX#244]
Hello,

I noticed that the "assetUrl" is no longer present for public avatars.
Is this normal? Is it a bug? Is it possible to have it back?

Thank you,
Lupsoris

![image](https://user-images.githubusercontent.com/29005043/125288206-24bfb680-e31e-11eb-8b1e-57f964d5080b.png)

**Comment by Foorack** [comment]
This has been removed by VRChat. From now on you can only see the assetUrl for your own avatars.

**Comment by Lupsoris** [comment]
> This has been removed by VRChat. From now on you can only see the assetUrl for your own avatars.
Okay, thanks.
If pypy finds a new way to get the assetUrl, will it be available again in VRCX?

**Comment by Natsumi-sama** [comment]
If it return's (which it won't) it shouldn't have been there in the first place it would be displayed again, but other than that an alternative method wont be used.

**Comment by Foorack** [comment]
> > This has been removed by VRChat. From now on you can only see the assetUrl for your own avatars.
> 
> Okay, thanks.
> If pypy finds a new way to get the assetUrl, will it be available again in VRCX?

This was removed by VRChat to prevent avatar theft. The API has ways of detecting if a requests originates from inside or outside the game. Even though it is in theory possible to still obtain the assetUrl for other's avatars, attempting to download the asset file yourself will be detected as ripping, and may likely lead to account termination.

If you have a legitimate use-case, contact the author and ask if you can get or buy the avatar.

**Comment by Lupsoris** [comment]
I used it mainly for my commissions, to know the sizes of my avatar, etc. I didn't use it for anything else.

But thanks for your answers! :)

**Comment by Murkur** [comment]
size of your avatar? you can still see the assetURL and the sizes of your own avatars as long as they are on your account. just enable crunch compression in unity and most size issues are solved.

**Comment by ScruffyRules** [comment]
> size of your avatar? you can still see the assetURL and the sizes of your own avatars as long as they are on your account. just enable crunch compression in unity and most size issues are solved.

and things like stop using 8k & 4k for everything lol

**Comment by Murkur** [comment]
> > size of your avatar? you can still see the assetURL and the sizes of your own avatars as long as they are on your account. just enable crunch compression in unity and most size issues are solved.
> 
> and things like stop using 8k & 4k for everything lol

Crunch compressor even if your using completely unessacary sizes like 8k and 4k crunch compressor will usually taken them down  by more then 3 quarters inside 30MB > 500KB

**Comment by ScruffyRules** [comment]
> > > size of your avatar? you can still see the assetURL and the sizes of your own avatars as long as they are on your account. just enable crunch compression in unity and most size issues are solved.
> > 
> > 
> > and things like stop using 8k & 4k for everything lol
> 
> Crunch compressor even if your using completely unessacary sizes like 8k and 4k crunch compressor will usually taken them down by more then 3 quarters inside 30MB > 500KB

Yeah but my VRAM will still be eaten by those sizes.

**Comment by Murkur** [comment]
> > > > size of your avatar? you can still see the assetURL and the sizes of your own avatars as long as they are on your account. just enable crunch compression in unity and most size issues are solved.
> > > 
> > > 
> > > and things like stop using 8k & 4k for everything lol
> > 
> > 
> > Crunch compressor even if your using completely unessacary sizes like 8k and 4k crunch compressor will usually taken them down by more then 3 quarters inside 30MB > 500KB
> 
> Yeah but my VRAM will still be eaten by those sizes.

Your Vram is gonna get eaten either way :)

**Comment by ScruffyRules** [comment]
> > > > > size of your avatar? you can still see the assetURL and the sizes of your own avatars as long as they are on your account. just enable crunch compression in unity and most size issues are solved.
> > > > 
> > > > 
> > > > and things like stop using 8k & 4k for everything lol
> > > 
> > > 
> > > Crunch compressor even if your using completely unessacary sizes like 8k and 4k crunch compressor will usually taken them down by more then 3 quarters inside 30MB > 500KB
> > 
> > 
> > Yeah but my VRAM will still be eaten by those sizes.
> 
> Your Vram is gonna get eaten either way :)

😢

**Comment by Lupsoris** [comment]
> size of your avatar? you can still see the assetURL and the sizes of your own avatars as long as they are on your account. just enable crunch compression in unity and most size issues are solved.

I often upload directly to their account. So with the avatarid I upload the assetUrl and I see the exact size. This is especially useful for Quest avatars that I need to compress, but not too much.

**Comment by Murkur** [comment]
> > size of your avatar? you can still see the assetURL and the sizes of your own avatars as long as they are on your account. just enable crunch compression in unity and most size issues are solved.
> 
> I often upload directly to their account. So with the avatarid I upload the assetUrl and I see the exact size. This is especially useful for Quest avatars that I need to compress, but not too much.

you could still check the size of the generated bundle after upload in your temp directory if I remember right it goes somewhere in the temp folder for the project / also if the avatar is AV3 you can generate a build and test avatar which goes to vrchats appdata folder the sizes are basically identical minute 1 or 2 kilobytes for script refrences.

**Comment by Lupsoris** [comment]
> you could still check the size of the generated bundle after upload in your temp directory if I remember right it goes somewhere in the temp folder for the project / also if the avatar is AV3 you can generate a build and test avatar which goes to vrchats appdata folder the sizes are basically identical minute 1 or 2 kilobytes for script refrences.

A temp directory? Do you know where?

**Comment by Murkur** [comment]
> > you could still check the size of the generated bundle after upload in your temp directory if I remember right it goes somewhere in the temp folder for the project / also if the avatar is AV3 you can generate a build and test avatar which goes to vrchats appdata folder the sizes are basically identical minute 1 or 2 kilobytes for script refrences.
> 
> A temp directory? Do you know where?

Depends If your building a test avatar it goes to `%AppData%\..\LocalLow\VRChat\VRChat\Avatars`
if you just want to see the uploaded avatar it goes to `%localappdata%/Temp/DefaultCompany/ProjectName/.vrca`
the vrca name depends on the avatars id

**Comment by Lupsoris** [comment]
> Depends If your building a test avatar it goes to `%AppData%\..\LocalLow\VRChat\VRChat\Avatars`
> if you just want to see the uploaded avatar it goes to `%localappdata%/Temp/DefaultCompany/ProjectName/.vrca`
> the vrca name depends on the avatars id

Okay, thank you :)

**Comment by Murkur** [comment]
you can also use the inspector tool from the preview packages in package manager https://docs.unity3d.com/Packages/com.unity.build-report-inspector@0.1/manual/index.html
which generates a in-depth inspect able log of all assets and there sizes
![Unity_hdQbmwIXxh](https://user-images.githubusercontent.com/20288698/125295115-e9f45900-e2f2-11eb-8000-cbf4cdece854.png)
