### ISSUE TITLE
Ignored Friend Requests feature integration

### ISSUE THREAD

**Issue by Rikketh** [pypy-vrc/VRCX#248]
_Not an issue, but rather a feature request._

Hi. Apparently, VRC's website now has a feature called Ignored Friend Requests. You can check it out [here](https://vrchat.com/home/messages). It is supposed to stop requests from going through if you decline them, by the looks of it, since there is no way to decline a request without adding the person to that ignore list.

Which is the issue here, since the feature seems to be retroactive. Any declined request is automatically ignored now, and there is no way to search/filter through said list, unless I'm missing something. Couldn't find any mention of said feature either, not yet.

It also seems to be in development or generally bugged, as removed people still count as ignored people, thus suppressing their friend requests after they are removed. Not sure if it is a one-off; warrants some testing.

Cheers.

**Comment by Murkur** [comment]
The Ignore and delete notification button are the same thing, they both call to the same endpoint with the same request

https://api.vrchat.cloud/api/1/auth/user/notifications/[NOTIFCATION ID]/hide

this would be adding a feature that already exists under another name

**Comment by Murkur** [comment]
till vrchat actually makes that button do something different the best way to ignore friend requests is to simple not decline them, they cannot send a new friend request if one has already been delivered and has not been accepted or declined then they actaully go to this 
![image](https://user-images.githubusercontent.com/20288698/125607530-27e5dee1-7843-47ad-b38e-84c0ee87440c.png)

**Comment by Murkur** [comment]
nevermind I am completely incorrect the unofficial docs seem to be a bit out of date still 😆

**Comment by Rikketh** [comment]
Seems like the notification row button indeed does call to /hide endpoint, but the [burger menu subitem called "Delete friend request"](https://github.com/pypy-vrc/VRCX/blob/395777b2713aef43bd74bba191d13fe21ee802f9/html/src/app.js#L1910) both does remove the request and the ignore entry. The website, however, still doesn't provide any way to request the latter endpoint at all.

**Comment by Murkur** [comment]
> Seems like the notification row button indeed does call to /hide endpoint, but the [burger menu subitem called "Delete friend request"](https://github.com/pypy-vrc/VRCX/blob/395777b2713aef43bd74bba191d13fe21ee802f9/html/src/app.js#L1910) both does remove the request and the ignore entry. The website, however, still doesn't provide any way to request the latter endpoint at all.

yeahh thats why I was a bit confused i got like 40 or so requests still standing so ill do some debugging
