### ISSUE TITLE
More favorite avatars stored locally

### ISSUE THREAD

**Issue by GotoFinal** [pypy-vrc/VRCX#25]
It would be nice to have separate (stored locally) list of favorite avatars, each favorited avatar would be saved to it but not removed automatically when removed from official vrchat list. And option to move given avatar to vrchat list.
That would easily allow to store more favorite avatars and manage them using vrcx, maybe even it could store history of used avatars by you.

**Comment by Murkur** [comment]
that could be made possible by using a file with avatar ids 1 per line that how some clients do it

**Comment by pypy-vrc** [comment]
I had the same idea. but, this is a sensitive part that can be a problem, so I'll consider it a bit more. sorry

**Comment by Arion-Kun** [comment]
Would be a cool idea!

**Comment by Murkur** [comment]
I think we just met in vrchat with ladle, eastbon and mizuz @GotoFinal

**Comment by Fusl** [comment]
Created a new request for this feature with a basic idea how it can be done and theoretically implemented: https://github.com/pypy-vrc/VRCX/issues/47

**Comment by Natsumi-sama** [comment]
Not needed/possible anymore because of VRChat Plus.
