### ISSUE TITLE
[BUG] SteamVR Overlay not working (AMD GPU driver crash?)

### ISSUE THREAD

**Issue by Crow-tm** [pypy-vrc/VRCX#256]
After AMD RX drivers crash (for god knows what reason), SteamVR asks to be restarted and after it is done, the icon on the SteamVR on the left that shows the wrist overlay inside SteamVR disappears.

Tried disabling the overlay and even forcing it on, but doesnt show up at all.

**Comment by Natsumi-sama** [comment]
Have you restarted VRCX? silly question I know but have to be sure.

**Comment by abbeybabbey** [comment]
I've experienced crashes on 5700XT in vrc with wrist feed too. I never use the vrcx overlay because of this.

**Comment by Crow-tm** [comment]
Actually.. Restarting vrcx fixed it. I didn't try that before, because all the timers reset on restart, good to know it was such an easy fix, thank you.
