### ISSUE TITLE
Error 401 Unauthorised "Missing Credentials"

### ISSUE THREAD

**Issue by Cthuwu** [pypy-vrc/VRCX#257]
![image](https://user-images.githubusercontent.com/46110723/127940986-6cdad10c-c4b7-4d76-b725-7082a59e700c.png)

When i open the program i get this msg and it wont let me log in through steam.

**Comment by Natsumi-sama** [comment]
Save this [VRChatRPC.dll](https://github.com/pypy-vrc/VRCX/blob/master/VRChatRPC/VRChatRPC.dll?raw=true) file to your VRCX folder then restart VRCX and try again.

**Comment by Cthuwu** [comment]
thank you it worked
