### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by aMaZeLeg3nd** [pypy-vrc/VRCX#259]
When I try to login it gives me this error code
401 Unauthorized
"\"Invalid Username or Password\""
"auth/user?apiKey=JlE5Jldo5Jibnk5O5hTx6XVqsJu4WJ26"

**Comment by Natsumi-sama** [comment]
With steam? https://github.com/pypy-vrc/VRCX/issues/257

**Comment by aMaZeLeg3nd** [comment]
> With steam? #257

No, with VRChat account

**Comment by Natsumi-sama** [comment]
Can you login to the website normally? https://vrchat.com/home/

**Comment by aMaZeLeg3nd** [comment]
yea

**Comment by Natsumi-sama** [comment]
Maybe your username or password has a special character in it causing problems try login with your email instead of your username or change your password

**Comment by aMaZeLeg3nd** [comment]
oh, it worked 
thx

**Comment by Natsumi-sama** [comment]
Do you know what special character caused the problem?

**Comment by aMaZeLeg3nd** [comment]
My username is 喀秋莎 | aMaZeLeg3nd, so maybe "喀秋莎 |“ (Simplifed Chinese)

**Comment by Natsumi-sama** [comment]
Yea thanks this will likey be the cause I will look into it.

**Comment by aMaZeLeg3nd** [comment]
np

**Comment by Natsumi-sama** [comment]
I tried VRChat website and VRCX both return the same base64 for that username, closing because can't replicate.
