### ISSUE TITLE
TTS voices again 

### ISSUE THREAD

**Issue by FoxFireVR** [pypy-vrc/VRCX#260]
Just updated to the new version , I can see the all the voices this time (microsoft and ivona) but when I select one of the ivona voices it won't use it , it either uses the previously selected Microsoft voice or plays nothing and I tried using the patch script from the last one that u made and it didn't work either

**Comment by Natsumi-sama** [comment]
Weird, I have the same setup with no issues, does it work on this website? [https://ttsreader.com](https://ttsreader.com)

**Comment by FoxFireVR** [comment]
sorry it took me so long to get back i been super busy , and im not sure what to say , so i made this to show , version i know works , and newest version, i will try to be quick to respond to u.


https://user-images.githubusercontent.com/87218872/133793033-a3f19b22-94ac-4b65-9366-c195f90c78a6.mp4

**Comment by FoxFireVR** [comment]
and yes i knoiw i have a windows update but is the newest one from this week that breaks everything

**Comment by FoxFireVR** [comment]
so with the new update that u just did having the same issure as the others , same one that is in the video

**Comment by Natsumi-sama** [comment]
Can you test the TTS voice on this website? https://ttsreader.com

**Comment by FoxFireVR** [comment]
so everyone there works except the ivona 2 ones
