### ISSUE TITLE
In the new update, the function of adding an avatar by id has disappeared

### ISSUE THREAD

**Issue by shaman-hub** [pypy-vrc/VRCX#261]
The function was very convenient my friend rarely plays but often makes avatars and sent me the avatar id, I could easily add it to my favorites.

**Comment by RequiDev** [comment]
You can look up an avatar by id again if it's public and favorite it there.

**Comment by shaman-hub** [comment]
![2021-08-17 123056](https://user-images.githubusercontent.com/69698632/129668841-898a0c00-cd26-41a8-be7d-792e841b6968.png) i dont see button

**Comment by Natsumi-sama** [comment]
There were three buttons so I deleted that one.
![Screenshot 2021-08-17 173620](https://user-images.githubusercontent.com/11171153/129669455-7f54a0e7-78dc-4fea-afc1-bc6000dbff2c.png)
![Screenshot 2021-08-17 173652](https://user-images.githubusercontent.com/11171153/129669458-065db777-e4fd-47ba-b88c-6e6a547066cb.png)

**Comment by shaman-hub** [comment]
I see. Thanks for the help.
