### ISSUE TITLE
Friend Group List bugged

### ISSUE THREAD

**Issue by wavywavywav** [pypy-vrc/VRCX#269]
If you unfriend a user before unfavoriting them it will break favoriting. You wont be able to favorite/unfavorite anybody. You wont be able to clear your favorites groups. 

404 Not Found
"404 favorites not found"
"favorite/group/friend/group_2/usr_

**Comment by Foorack** [comment]
If you unfriend someone then they are automatically removed from any favorite group.

If you are still seeing them in the list then it is cached, either by VRCX or by VRChat's API.

**Comment by permatrip** [comment]
> 
> 
> If you unfriend someone then they are automatically removed from any favorite group.
> 
> If you are still seeing them in the list then it is cached, either by VRCX or by VRChat's API. If VRCX still displays the favorite after showing 404 then it sounds like a bug with VRCX.

I probably should have mentioned I cleared VRCX cache. I suppose its an issue on VRChat's end.. like always. Just a warning to people who don't want their stuff bugged.
