### ISSUE TITLE
[Feature request] View and edit bios

### ISSUE THREAD

**Issue by Sakuukuli** [pypy-vrc/VRCX#27]
The VRChat website now supports viewing and editing a short bio and links about yourself. It can be viewed in the JSON of a user, but a proper implementation would be helpful.

**Comment by pypy-vrc** [comment]
![image](https://user-images.githubusercontent.com/25771678/72915204-46705b00-3d83-11ea-821b-2adf1716bef1.png)

Now you can see bio. but edit feature need more time. sorry.

**Comment by Sakuukuli** [comment]
Bio links do nothing when clicked, only show the link when hightlighted. I think they should open the link in a browser.

**Comment by pypy-vrc** [comment]
it's available soon (cc3d89a95493640fd56d78776081bca17360efe3 and 2db0d6294c11bf50c9ee45daf6ce2af8eae694f8)
