### ISSUE TITLE
XSOverlay notifications don't work

### ISSUE THREAD

**Issue by realityvrc** [pypy-vrc/VRCX#270]
- Version: VRCX 2021.08.15, Windows 10 Build 19043
- When enabling XSOverlay Notifications in VRCX options, it does not work.
I tried to send notification manually like this from the console
 ```javascript
AppApi.XSNotification('VRCX', 'test', 5, false);
```
and VRCX throws following exception:
> System.IO.FileLoadException: "Could not load file or assembly "System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" or one of it's dependences. The found Assembly's manifest definition does not match the Assembly reference. (Exception from HRESULT: 0x80131040)"

https://stackoverflow.com/questions/62764744/could-not-load-file-or-assembly-system-runtime-compilerservices-unsafe

Recompiling VRCX locally with Visual Studio 2019 & newest node.js fixes the issue for me, but both current releases on pupy-vrc & Natsumi-sama repos throw this error

**Comment by Natsumi-sama** [comment]
Hmmm alright thanks I will keep an eye out for that one

**Comment by MrDj200** [comment]
Is this gonna be fixed?
When I recompiled by myself, vrcx didn't start at all

**Comment by Natsumi-sama** [comment]
yea it's fixed just need to test things before doing a release
