### ISSUE TITLE
Can't see peoples Created Avatars or worlds list anymore!

### ISSUE THREAD

**Issue by slysnake96** [pypy-vrc/VRCX#271]
As mentioned in the title I can't see the list of avatars by a creator anymore, the biggest reason I use VRCX is to be able to browse people who I met in game and see the worlds and avatars they have created so I can visit their worlds and know exactly which avatar I want to use of their public ones.

**Comment by ScruffyRules** [comment]
It's probably not that big of a reason considering you only just made a report several months after VRC disabled the ability to see other's Avatars.

**Comment by Natsumi-sama** [comment]
Listing user avatars is long gone and wont be coming back because VRChat removed it.
https://github.com/pypy-vrc/VRCX/discussions/184
Listing user worlds still works fine.

**Comment by slysnake96** [comment]
Ok thanks for the info I just haven't played VRC in over 8 months until a couple days ago LOL
