### ISSUE TITLE
Default Robot avatar shown as used by anyone using a gallery picture as their avatar thumbnail

### ISSUE THREAD

**Issue by Asovrix** [pypy-vrc/VRCX#275]
This feels like a partial come back of #267 
Present in 2021.10.01 (beta) release.
All VRC+ users who use a picture from their gallery as their thumbnail have this shown in Avatar info instead of just nothing/dash:
![VRCX_2021-10-01_15-31-26](https://user-images.githubusercontent.com/44006686/135628753-c8937d66-bf60-4215-a238-89368b211835.png)

**Comment by Natsumi-sama** [comment]
Ah, they changed the robot imageUrl from https://assets.vrchat.com/system/defaultAvatar.png to https://api.vrchat.cloud/api/1/file/file_0e8c4e32-7444-44ea-ade4-313c010d4bae/1/file
