### ISSUE TITLE
IP roaming breaks autologin

### ISSUE THREAD

**Issue by realityvrc** [pypy-vrc/VRCX#277]
I have mobile & home internet with different white IPs.
- If I change wifi while VRCX is open, "Refresh friends" button go on spinning forever and notifications stop.
- If I re-start VRCX on IP change, I have my account saved but it does not log in automatically, need to click on it to get back in.
- If, instead of restarting on the new IP I re-connect back to my first wifi "Refresh friends" button still spins forever but auto-login on VRCX restart properly works

Guess everyone will have the same issues with dynamic IP.
I know VRChat cookies are tied to IP and there're a few issues on their canny, related to VPN breaking & maximum number of sessions per account and per IP.

Would it be possible to keep multiple sessions in VRCX tied to ip requested via some ip-checker and on request timeout (which now seems to be infinite) if ip changed swap the session? Or just keep only one session and create a new one whenever ip changes?
Guess the first idea will'll require some "log out / clear all sessions" button or a round robin for at least two (user,ip) pairs
and the second idea could leave a lot of open sessions when changing IP a few times which caused in the past a few people (including myself) to be locked out of their account due to maximum active session limit. Idk if this bug is fixed by VRChat, but when I encountered it half a year ago it took all sessions roughly 48 hours to timeout to be able to log back in on the site or VRChat app. Some other users affected by this bug had to contact support.
So yeah.. Would be nice to fix ip roaming if possible, without endangering anyone

**Comment by Murkur** [comment]
Its a limitation of VRChat invalidating a token when its though another IP

**Comment by realityvrc** [comment]
I know. But it's possible to work around it. It'll improve VRCX user experience

**Comment by Murkur** [comment]
> I know. But it's possible to work around it. It'll improve VRCX user experience

uh not really since that's the way the API works its a security measure

**Comment by slord399** [comment]
Yeah, It will simply cause security issue which user don't want more than user experience.
Generally, IP shouldn't change that much unless you are moving so usually not cause issue with it.
(try keep alive network connections, it will usually keep same IP for longer.)

**Comment by Natsumi-sama** [comment]
Are you able to check the console for errors when auto login fails? do you use 2FA or VRCX "Primary Password"?

**Comment by realityvrc** [comment]
I don't use 2fa, only VRCX primary password (not using Steam login either).
Console throws those errors:
```js
app.js:455 Uncaught (in promise) Error: 401: Missing Credentials at app.js:455
app.js:5658 Uncaught (in promise) TypeError: Cannot read property 'username' of undefined at app.js:5658
```
It does not happens instantly, only when I hit "Refresh friends" button after wifi change

**Comment by Natsumi-sama** [comment]
Try disable primary password

**Comment by realityvrc** [comment]
> Try disable primary password
How? Should I log out & unckeck "Save credentials" on VRCX login page?
I tried doing that but it does not change the core behaviour.
If I do that and restart VRCX from another IP I just need to re-enter login information instead on clicking on saved account to get back in

**Comment by Natsumi-sama** [comment]
No just disable the "Use a Primary Password" option in settings
