### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by Grubbiestisgay** [pypy-vrc/VRCX#28]
the program crashes everytime i open it

**Comment by Murkur** [comment]
redownload it could be a corrupted Json file

**Comment by Grubbiestisgay** [comment]
i tried multiple times but it did the same

**Comment by pypy-vrc** [comment]
press ctrl+shift+i, and the developer tools will open. after press ctrl+r will refresh it. then, when an error occurs, the details of the error log in the console. let me know that.

**Comment by Grubbiestisgay** [comment]
its not letting me open the console when i try to open it it crashes the second after i open it
![explorer_mxf2A95Apq](https://user-images.githubusercontent.com/59905550/72676459-58ca5c00-3a46-11ea-83b0-ada35ec4591a.png)

**Comment by Natsumi-sama** [comment]
Closing because issue inactive.
