### ISSUE TITLE
VRCX is getting very slow/freezes when VRC is running

### ISSUE THREAD

**Issue by Hackebein** [pypy-vrc/VRCX#286]
At them same moment when VRC starts (doesn't need to be logged in) any update progress is getting very slow/freezes in VRCX. After closing VRC it's working again.
I noticed this issue for around 3 weeks ago with VRCX (2021.10.02).
I uninstalled VRC and VRCX and deleted every left over and gave both a clean new installation but still the same issue.
I installed beta build (VRCX.PyPyDance.Companion 2021.10.29) yesterday unfortunately with the same issue.

For visualization i recorded a video: https://youtu.be/e_kbGT_YQxk

Sending out an invite to myself or friends is delayed. It takes ~5 Minutes (I haven't measured it with a stopwatch).
I couldn't find any of my friends that is using VRCX that has the same issue.

**Comment by Natsumi-sama** [comment]
Can you press `Ctrl + Shift + I` and check the console tab for any errors?

**Comment by Hackebein** [comment]
When VRC is running the Console opens 5 or 10 minutes delayed. Same for key bind and console button in settings section. Console opens immediately after closing VRC.
When i start VRCX before VRC it works fine and doesn't show any error in console.

**Comment by Georninja** [comment]
Same issue happens to me every once and a while. I'd be clicking "invite me" like a billion times and nothing would show in the game or on VRCX, and then once I close VRChat, I get spammed with a billion invites from myself on VRCX.

**Comment by Hackebein** [comment]
every once in a while sounds better than my always. Any idea how to trigger that issue? Or at least any idea how to see any error/warning/information what happen that VRCX is doing that?

**Comment by ekrom815** [comment]
I have the same issue as well with the lastest release

**Comment by Natsumi-sama** [comment]
Could you test this beta to see if the issue persists?
https://github.com/Natsumi-sama/VRCX/releases/tag/v2021.11.15

**Comment by ekrom815** [comment]
> Could you test this beta to see if the issue persists? https://github.com/Natsumi-sama/VRCX/releases/tag/v2021.11.15

Sure

**Comment by ekrom815** [comment]
> Could you test this beta to see if the issue persists? https://github.com/Natsumi-sama/VRCX/releases/tag/v2021.11.15

i believe the issue no longer exists with this beta
