### ISSUE TITLE
[Feature Request] Change the maximum limits of cached entires

### ISSUE THREAD

**Issue by Miner28** [pypy-vrc/VRCX#287]
It would be nice if it was possible to change the maximum of 5000 feed entries that are cached by default to either something lower or higher.

**Comment by Miner28** [comment]
![image](https://user-images.githubusercontent.com/1560327/140308276-5e7d3d72-3fc2-49f3-b93d-877f68478f92.png)

**Comment by Miner28** [comment]
![image](https://user-images.githubusercontent.com/1560327/140308326-f85be363-2065-4a5e-8d9d-fde1a34c24e2.png)]
I noticed that there are a lot of entries according to SQLite Table Size but they are not displayed

**Comment by Natsumi-sama** [comment]
That's what the max table size option does, also having the table size large will just lag VRCX. Filters and search will now query all of the SQLite entries.

**Comment by Miner28** [comment]
Uh ups, sorry. I was on 1 version late. Didn't see the release today

**Comment by Miner28** [comment]
Changed the maximum table size to 1milion, works amazing. Slightly slower but not really too much.

**Comment by Natsumi-sama** [comment]
lmao check your RAM usage.

**Comment by Miner28** [comment]
![image](https://user-images.githubusercontent.com/1560327/140317135-47cca750-14d9-4123-9787-b9051757acdc.png)
Yea I think I'm fine

**Comment by Miner28** [comment]
15-20% CPU when I'm searching the SQL

**Comment by Natsumi-sama** [comment]
Not as bad as I would expect from JS, but there isn't much point in loading in the entire table because you can still query all of the data without making the table massive.

**Comment by Miner28** [comment]
![image](https://user-images.githubusercontent.com/1560327/140317525-1a470345-8176-4650-a9b7-358be477473a.png)

**Comment by Miner28** [comment]
> Not as bad as I would expect from JS, but there isn't much point in loading in the entire table because you can still query all of the data without making the table massive.

True, that's why I'll be putting it back to 20K. But thank you for implementing the option to change this.
