### ISSUE TITLE
High idle GPU usage

### ISSUE THREAD

**Issue by Explicitvoid** [pypy-vrc/VRCX#288]
With version 2021.11.04 I noticed that idle GPU usage has gone up again. This issue is not present on the previous version.
Looks to be exactly the same issue as before: #143
![2021-11-04_10-52-23](https://user-images.githubusercontent.com/1491571/140337827-926e08cb-f2c2-452e-b240-6636da4c7184.png)

**Comment by Natsumi-sama** [comment]
Could you give this beta a try to see if that fixes it?
https://github.com/Natsumi-sama/VRCX/releases/tag/v2021.11.15

**Comment by Explicitvoid** [comment]
Seems like that fixed it.
