### ISSUE TITLE
[Feature request] Emit "Location" in Game Log as early as possible (using dst set log)

### ISSUE THREAD

**Issue by Fusl** [pypy-vrc/VRCX#29]
VRCX currently uses the `[RoomManager] Joining INSTANCE_STRING` log line to parse the instance ID and show it as location in the Game Log. `[VRCFlowManagerVRC] Destination set: INSTANCE_STRING:` is another line that's logged when switching instances and happens even before the room transition fade effect. Be careful about parsing this line though, it contains a colon at the end (like shown above).

**Comment by pypy-vrc** [comment]
"Destination set" sometimes lacks instance information. but, if the "Destination set" contains both world ID and instance information, we can refer to this, otherwise we can refer to "Joining" as before.

**Comment by pypy-vrc** [comment]
i made patch 30b7791c31b864944ea7a879d3b25de47a4fad35

**Comment by Fusl** [comment]
Patch looks good but I don't see where you're handling and stripping away the colon at the last position of the string which doesn't belong to the instance string. I don't know if the colon on the last position right before the newline character always exists in all cases but it does exist in all of my output log files.

**Comment by pypy-vrc** [comment]
It is checked that is empty (ends with colon) on line 133. and also checked instance infos on line 138. of course, it's not strict, but that's enough.

**Comment by Fusl** [comment]
![image](https://user-images.githubusercontent.com/2349496/73151480-3b8b3280-40c3-11ea-9538-f2d4d9d82562.png)
Instance ID is parsed incorrectly and includes the colon now which is incorrect. The colon should be removed before using that string in the log file for parsing.
