### ISSUE TITLE
[Feature Request] Portable-Aware Updater

### ISSUE THREAD

**Issue by ObscenityIB** [pypy-vrc/VRCX#299]
Just had an update popup this morning and went to go through it.
Previously I would check here and then extract the zip over the old one to update.

The updater only downloaded the installer version and tried to run a setup in a different directory.

If the updater could check if it was a portable install and only download the zip, or at least have a button to do so, would be great.

**Comment by Natsumi-sama** [comment]
I had a portable updater initially but replaced it after creating the installer. Maintaining multiple updaters brings unnecessary complication. Why do you need the portable version? Could switch to the installer or use the notify open to install manually when an update is available.
