### ISSUE TITLE
Opening VRChat while having VRCX open will now spam 429 errors

### ISSUE THREAD

**Issue by Legoman99573** [pypy-vrc/VRCX#301]
I am not sure why opening VRChat and having VRCX now floods with this now. Guess they changed something on their back end that finally broke VRCX as well as VRChat.

![image](https://user-images.githubusercontent.com/7460704/150396723-8b2a2aa4-12b1-45d1-a645-34c00303bbb5.png)

**Comment by Natsumi-sama** [comment]
seems to only be you at the moment.

**Comment by Legoman99573** [comment]
wasn't an issue till last night and waited incase it was a misconfiguration maybe

**Comment by information-redacted** [comment]
> wasn't an issue till last night and waited incase it was a misconfiguration maybe

Can you try accessing https://api.vrchat.cloud/api/1/config via a web browser? The response you're receiving indicates that you have sent too many requests to the API, and that they are now being rejected.

**Comment by Legoman99573** [comment]
it shows fine without anything running. Not sure if it has to do with 100+ online and 1,500+ offline friends online at once and 2k pending friend requests
