### ISSUE TITLE
VRCX freezes shortly after opening

### ISSUE THREAD

**Issue by atomiklan** [pypy-vrc/VRCX#302]
Attempting to use VRCX 2022.02.02 and for some reason, it is once again freezing like it used to do shortly after opening. Once the application launches, I seem to get about 30 seconds and then everything locks up.

**Comment by Natsumi-sama** [comment]
Check the console tab in DevTools you can open it with ``Ctrl + Shift + I`` to see if any errors are occurring, or you could reset VRCX by deleting/renaming the config folder located here ``%AppData%\VRCX``

**Comment by atomiklan** [comment]
Console does not output any information, however, renaming the config folder and letting it regenerate seemed to do the trick. I guess somehow my config folder became corrupt. This all started a week or so ago when Microsoft suddenly labelled VRCX a virus and quarantined it. I reinstalled several times from scratch, but never tried to flush the configs. Hate that I have to reconfigure it, but happy to have everything working again. Thank you!

**Comment by Natsumi-sama** [comment]
It would be nice to figure out the cause you could use [sqlitebrowser](https://sqlitebrowser.org) to try fix it by deleting the config table or parts of it to keep your data if you wanted to.

**Comment by atomiklan** [comment]
Sure, if it would be helpful to you to figure out what caused it, I can do some additional troubleshooting. This has actually happened once before a few of months ago. I forget exactly how it ended up resolving itself, but good to know for the future that config corruption is most likely the culprit of these freezes. Let me know if you would like for me to gather some additional information. Otherwise I am fine just pressing forward. I have already just reconfigured my settings to the best of my knowledge and will just tweak as I go like normal. Thanks again!
