### ISSUE TITLE
Game log search filtering

### ISSUE THREAD

**Issue by Kieaer** [pypy-vrc/VRCX#303]
1달전에 그 방에 같이 있던 친구의 이름을 찾을려고 하는데, 현재 기능으로는 찾을 수 없고 테이블 크기를 10만까지 늘린 후 일일이 찾아내는 수 밖에 없습니다.
필터링 기능이 필요합니다. SQL 문구를 활용하면 될지도...

**Comment by slord399** [comment]
(Transcript)
I'm trying to find the name of a friend who was in that room a month ago, but I can't find it with the current function, and I can only find it one day after increasing the table size to 100,000.
Filtering is required. You can use SQL phrases...

**Comment by Natsumi-sama** [comment]
Thanks Tony,
If the current filters aren't enough and you would like to use a SQLite query you can open your `%AppData%\VRCX.sqlite` file with [sqlitebrowser](https://sqlitebrowser.org) to do so.

**Comment by Natsumi-sama** [comment]
Neither is exposing SQLIte syntax to the enduser.
