### ISSUE TITLE
403 Forbidden "config"

### ISSUE THREAD

**Issue by UiharuKazari2008** [pypy-vrc/VRCX#304]
When attempting to login i get the notification `403 Forbidden "config"`

**Comment by Natsumi-sama** [comment]
Disable your VPN it has been blocked by VRChat temporally.

**Comment by Myrkie** [comment]
> Disable your VPN it has been blocked by VRChat temporally.

asn go brrr

**Comment by UiharuKazari2008** [comment]
I dont have a VPN and I can access the platform like normal

**Comment by Myrkie** [comment]
> I dont have a VPN and I can access the platform like normal

are you using latest version of vrcx?

**Comment by Natsumi-sama** [comment]
have you tried the website?
![unknown](https://user-images.githubusercontent.com/11171153/153997853-afd8da4d-8543-41a2-81a1-ac888a128ea1.png)

**Comment by UiharuKazari2008** [comment]
now that i look trough my rules it is getting passed out a VPN
![image](https://user-images.githubusercontent.com/15165770/154009431-8b4d657c-c9dd-4019-91e7-dd80267072fa.png)

Well im not gonna allow it directly out my WAN so unless they unblock my provider or I change providers
