### ISSUE TITLE
Pop-ups lose focus when releasing mouse outside pop-up

### ISSUE THREAD

**Issue by daalta** [pypy-vrc/VRCX#306]
# Repro
1. Open a pop-up window (i. e. profile, status, etc.)
2. Click and hold your left mouse button inside the window
3. Move your mouse cursor to somewhere outside the window
4. Release

**Expected:** Pop-up stays open, as I did not **click** outside the pop-up
**Actual:** Pop-up closes

# Why is it a problem?
When changing names, users may click and drag their mouse cursor. When they do, they're likely to overshoot and close the pop-up window. Soooo I'm pretty sure this is a bug, I don't think other applications behave this way.

# Proposed solution
Close the pop-up when clicking the mouse, instead of when releasing outside it.

**Comment by Natsumi-sama** [comment]
This issue annoys me as well but it's caused by an upstream library and has been like that forever. https://github.com/ElemeFE/element/issues/15000

**Comment by daalta** [comment]
O- Oh my.
![firefox_RcmKGiDHW3](https://user-images.githubusercontent.com/9169275/155545765-0122923a-be52-4763-94f3-fa14eee46722.png)
!

Well!!! That was quick, thank you for fixing it! Ur very cool, thank you :v
