### ISSUE TITLE
Shows update notification even when no update is available

### ISSUE THREAD

**Issue by Fusl** [pypy-vrc/VRCX#31]
The new version update notification shows up even if I'm on the latest version.

![image](https://user-images.githubusercontent.com/2349496/73795260-18870f80-47a2-11ea-9091-751f3b912e75.png)

**Comment by Murkur** [comment]
the version your on is 2020.01.26 up is for 2020.02.01

**Comment by Fusl** [comment]
@Murkur Yeah, I just noticed that too, even though I just recently downloaded the `VRCX_20200201.zip` but re-downloading.

**Comment by Murkur** [comment]
@Fusl that should fix the issue its just you missed the newest update as it wasn't a very big release this version seems to use a lot less system memory
