### ISSUE TITLE
Overlay Notification vs Wrist Feed

### ISSUE THREAD

**Issue by Chayotea** [pypy-vrc/VRCX#316]
This has to do with the feature request I made a while ago https://github.com/pypy-vrc/VRCX/issues/198
The overlay notifications for blocked or muted joins do not display they only appear in the wrist feed.

I joined a room were the instance creator was someone that I had blocked. I got kicked after a few minutes when he noticed I was there. I was clueless till it was too late. Sucks that we have friends in common and sucks even more that person enjoys being the instance creator.

**Comment by Natsumi-sama** [comment]
If it's on the wrist feed without a notification then you must have all notifications or the filter disabled, Enable "Blocked Player Joins" in Notification Filters.

**Comment by Chayotea** [comment]
Both wrist feed and notification filters look like this 
![image](https://user-images.githubusercontent.com/82981665/158014849-1f38f02c-c809-4754-bf42-7b2b22522a26.png)

**Comment by Natsumi-sama** [comment]
If you receive other notifications fine then the issue must be something else and should also affect wrist feed.
