### ISSUE TITLE
photon id parsing is still broken for me without VRCX companion

### ISSUE THREAD

**Issue by abbeybabbey** [pypy-vrc/VRCX#317]
For some reason the photonId parsing from the output_log is still broken for me. Here is a preview of my output_log text that should get recognized by ParseLogPhotonId method in LogWatcher.cs.
![notepad_jmZpNCLG7x](https://user-images.githubusercontent.com/61197745/158026945-9e0d520c-6473-469f-b0f0-9f24fcff745c.png)
But as seen in the player list it doesn't display: 
![VRCX_kpSzINJBpS](https://user-images.githubusercontent.com/61197745/158026956-6cd844bf-2b1f-469d-a055-5a541b8644ed.png)
I have all debug levels enabled and I am not running VRCX companion, previous stable release was able to parse the photonIds fine (https://github.com/pypy-vrc/VRCX/releases/tag/v2022.02.02). Although I was in in this map: https://vrchat.com/home/world/wrld_4a0ed04a-58d7-48d0-950f-ff57ff645c44 which seems to have some weird "prints" to the output log most likely related to some udon prefabs in the world I presume?.

**Comment by abbeybabbey** [comment]
Oh one thing to note is: I have ``--enable-verbose-logging`` in my launch options, but I had it when I was running previous release as well so I'm not really sure what has changed in detail. Here's a picture of me running the previous stable release and parsing the photon ids fine in the same lobby:
![VRCX_lsWm8CpDVB](https://user-images.githubusercontent.com/61197745/158027383-d48a215a-3bc9-4c54-932c-b756d710059c.png)

**Comment by Natsumi-sama** [comment]
Looks like I broke it, oh well it will be fixed after VRC release current beta.
