### ISSUE TITLE
[Feature request] Finer control for desktop notifcations

### ISSUE THREAD

**Issue by 64766C** [pypy-vrc/VRCX#319]
I like desktop notifications when I'm playing on desktop because I might be alt tabbed. I also like them when the game is not running.

However I don't like them when I'm inside VR because in VR I'm paying closer attention to invites etc. simply because it's harder to multi task. Specifically I don't like the sound that goes off, the toast notification itself is going to be on the desktop and I would miss it anyway.

So I would like to have desktop notifications enabled when the game is not running at all, and also when it's running on desktop mode. But at the same time I would like notifications to be disabled when I'm running the game in VR.

**Comment by SalbugVR** [comment]
I remember there used to be an option for notification display option for 'Outside VR' but unsure why it was removed.

**Comment by Natsumi-sama** [comment]
I removed it because I thought no one used it and I thought that it would confuse people, but I will add it back.

**Comment by Natsumi-sama** [comment]
Yup this was the problem this option looks a bit silly now, any suggestions on making it more user friendly?
![Screenshot 2022-03-15 224015](https://user-images.githubusercontent.com/11171153/158349840-586e8fb6-f278-460f-b3a8-b0911261d5f1.png)

**Comment by SalbugVR** [comment]
> this option looks a bit silly now

I mean that option can still have _some_ use. Perhaps someone wants to get notifications but not while they have the game running in general. As for user-friendliness... currently, nothing is coming to mind to me. Looking at each option in the image, I can see a good clear use case for each~

**Comment by fwenny** [comment]
Why does it look silly? Not sure I understand what is the issue.
I use Game Closed all the time.

**Comment by Natsumi-sama** [comment]
Having such a large amount of options for a basic toggle.

**Comment by Natsumi-sama** [comment]
I agree that's why I added it back, initially it was removed in an attempt to fix the cluttered amount of hardly used or understood toggles but I've since accepted that will never heppen lol.

**Comment by fwenny** [comment]
> 

Yeah, all of those options are used by some % of users, so you wont hear the end of it if you end up removing any of them lol.
But I dont think its a big deal. Just means theres something for everyone.

**Comment by Natsumi-sama** [comment]
Issue is when someone wants to find a quick setting you have to dig through the massive pile of crap, but that's more of a UI problem than anything else.

**Comment by fwenny** [comment]
Hmm. I dont think its massive at all. And worst case, if youre worried about people getting confused, you can add tool tips for the buttons with a short explanation on what each does (though I believe they are quite self explanatory)
