### ISSUE TITLE
[Feature request] Don't close the application when attempting to Auto-Update

### ISSUE THREAD

**Issue by UiharuKazari2008** [pypy-vrc/VRCX#320]
Would be nice if I did not have to fight with the application to cancel a automatic update where every time I open it it was to update, I cancel the UAC prompt, then the app crashes. Repeat forever until you can catch it when it fails to connect

I should not be forced to auto-update and made even harder to disable it

**Comment by Natsumi-sama** [comment]
By default updates are automatically downloaded then applied on next program restart, yes UAC is required by the setup for admin permissions to write to program files. If you need to stop the update from trying to be applied on startup delete all exe files inside `%AppData%\VRCX`.

**Comment by UiharuKazari2008** [comment]
Or you could not exit the application until the installer has actually opened to allow anyone a chance to disable it. The only thing that somewhat gives you a chance to stop it is UAC

I shouldn't have to know the inns and outs of how it works to stop a update especially if it's going to be so intrusive and try to run a installer and not just replace the files in the folder
