### ISSUE TITLE
[Feature Request] Specify VRC executable path

### ISSUE THREAD

**Issue by Float3** [pypy-vrc/VRCX#321]
I usually launch VRC through another application (https://github.com/Float3/VRCLauncher) so I would like to specify what .exe VRCX opens

Alternatively, VRCX could support launch argument profiles for VR and Desktop since the launch prompt has a checkbox for Desktop

**Comment by Natsumi-sama** [comment]
What you could do instead is edit `HKEY_CLASSES_ROOT\VRChat\shell\open\command` to point to your programs exe, this will run your program when launching VRChat from the website or VRCX, depending on what parameters it gets launched with it can then launch any VRChat exe with any parameters you specify or choose to forward along.
