### ISSUE TITLE
dumb question

### ISSUE THREAD

**Issue by Invaliduser81** [pypy-vrc/VRCX#322]
is this app safe I'm mainly asking this because it got blocked from my computer

**Comment by Invaliduser81** [comment]
that was faster than expected and im easily influenced and impatient so one answer if all i need have a good day

**Comment by Invaliduser81** [comment]
actually im not sure anymore seeing how it says it has to be allowed to make changes to my pc

**Comment by ScruffyRules** [comment]
you're asking if an installer wants perms to change stuff?

**Comment by Invaliduser81** [comment]
y'know im starting to think my status is getting more and more accurate as the days go by

**Comment by ScruffyRules** [comment]
Issue solved? (Close it?)
