### ISSUE TITLE
[April fools] Titlebar is reversed (toggle theme to disable)

### ISSUE THREAD

**Issue by LewisTehMinerz** [pypy-vrc/VRCX#328]
I think the title and the following image explains it all:
![](https://discord.coffee/2JcpP8F.png)
![](https://discord.coffee/6fQHjFK.png)
Running Windows 11.
![](https://discord.coffee/8D8wVWk.png)

The titlebar will randomly go back to normal, but for the most part it is completely flipped like this at all times. Even the context menus are flipped:
![](https://discord.coffee/6YQrCKC.png)

I noticed there was a commit that added some custom form UI for themes, so that might be a part of it, but I'd have to look into it a lot more. VRCX is the only app on my PC that does this.

**Comment by LewisTehMinerz** [comment]
I have been informed that this is an April Fool's joke but I also could not find a way of disabling it in the settings. Might be wise to add something like that since this actually broke certain things for me and screwed with my muscle memory. ;^)

**Comment by information-redacted** [comment]
Workaround: Changing your theme (and changing it back) will return the title bar to its original orientation until the next program restart.

**Comment by Myrkie** [comment]
April fool's jokes that break intended function or settings shouldn't be a thing, if your gonna do April fool's jokes add something Instead of changing things that can be perceived as a bug. Make it blatantly obvious that it's a goof or it's going to confuse people.

**Comment by Natsumi-sama** [comment]
Having people guess if it's a bug or a feature is half the fun,
I'll leave this open for visibility.

**Comment by Myrkie** [comment]
> Having people guess if it's a bug or a feature is half the fun, I'll leave this open for visibility.

Your baaka.

**Comment by HugoZink** [comment]
"Jokes" that actually impact usability are too far. I'm all for a sense of humor but this isn't funny, just annoying.

**Comment by Natsumi-sama** [comment]
haha it mirrors OVRToolkit window capture.
![Screenshot](https://user-images.githubusercontent.com/11171153/161300985-e9989fd4-d4da-4d47-ba64-e4dfe4677ad0.png)

**Comment by explodingkittns** [comment]
I kind of want to throw my computer because of this but also thank you for this, it is extremely amusing.
