### ISSUE TITLE
World Location

### ISSUE THREAD

**Issue by HauntedC** [pypy-vrc/VRCX#332]
I have a big issue with how VRCX gets my current world information.
I am logged into VRChat with Account1 and in VRCX I am logged in with Account2 but it shows on VRCX the World / Instance of Account1 which is very unwanted. 

I request a method to either deactivate showing the current world / instance entirely or some way to unchain accounts from each other.

**Comment by Natsumi-sama** [comment]
I could add an option to disable all game log parsing, not much else can be done other than that.

**Comment by HauntedC** [comment]
Please do

**Comment by Natsumi-sama** [comment]
Added toggle in settings give that a try, expect things to break though.
