### ISSUE TITLE
[Report] Veteran and Legend ranks gone in 2022.1.2p4 build 1194?

### ISSUE THREAD

**Issue by KaleidonKep99** [pypy-vrc/VRCX#339]
I noticed that, after the latest VRChat update (`2022.1.2p4 b1194`), most of my Veteran friends got demoted to Trusted.
I also noticed that some Legend map creators got demoted to Trusted as well.

![image](https://user-images.githubusercontent.com/11065274/166886195-2eae7c77-14df-4dc1-bbcf-e6b061387fb6.png)

**Comment by Natsumi-sama** [comment]
Update your VRCX and read the changelog.

**Comment by KaleidonKep99** [comment]
Yeah just noticed that it's a duplicate of #337, I'll close it

**Comment by ScruffyRules** [comment]
Is that all?
