### ISSUE TITLE
VRCX Wrist Overlay doesn't seems to start up?

### ISSUE THREAD

**Issue by LunarstarPony** [pypy-vrc/VRCX#340]
Tried to swap it between VRChat and Steam no luck, is there anyway to start it manually?  I do have the VRCX-Companion on my game so that shouldn't be the issue?

**Comment by Natsumi-sama** [comment]
Do you have these settings enabled?
![Screenshot 2022-05-06 201552](https://user-images.githubusercontent.com/11171153/167093959-78b14568-7dd4-4697-a0a6-5cef5272332a.png)

**Comment by LunarstarPony** [comment]
Any idea why it's not working?

**Comment by tompointexe** [comment]
Hey, are you on a laptop with 2 GPU's ?? 
Make sure vrcx isn't stared on the Integrated GPU of your cpu! that's what caused it for me to not apear in steamvr !

**Comment by LunarstarPony** [comment]
That do seems like the issue Thx!
