### ISSUE TITLE
Previous Instances menu gets you stuck

### ISSUE THREAD

**Issue by imBigo** [pypy-vrc/VRCX#348]
When I go in the "Previous Instances" menu I get stuck in it and can't close out of it.

**Comment by Natsumi-sama** [comment]
Press `Cttl + Shift + I` click the console tab and send a screenshot.

**Comment by imBigo** [comment]
> Press `Cttl + Shift + I` click the console tab and send a screenshot.

I restarted VRCX and can't replicate the issue. If it happens again I'll reopen and send the screenshot.
