### ISSUE TITLE
403 Forbidden "file/file_..." popups

### ISSUE THREAD

**Issue by GODZILLA6337** [pypy-vrc/VRCX#351]
![image](https://user-images.githubusercontent.com/66243273/170850294-f4101e41-0557-41ce-b1dd-ea46f99efa87.png)
Everytime I log in and while I'm using the program it keeps flooding my screen with this error code
403 Forbidden "file/file_..."
I just got ahold of my computer after having it brought to me after 8 months of being away and I updated everything on here including installing a new version of VRCX and It's been doing this since I logged into the new version. Any tips on how to fix it?

**Comment by Natsumi-sama** [comment]
ah okay because your feed is so old it's full of deleted avatars causing some failed API requests they are safe to ignore and will go away with time.

**Comment by SalbugVR** [comment]
Basically what Natsumi said. Also appears you are on a very old version. According to the screenshot, you are on version `2021.08.14`, the latest version of `VRCX.PyPyDance.Companion` is currently on `2022.05.17`.

**Comment by GODZILLA6337** [comment]
I shall install the PyPy update then.
I was a bit concerned with the errors thinking something was wrong so ^^
Will they occur everytime I boot up vrcx or after they are gone will they stay gone?

**Comment by SalbugVR** [comment]
To get the latest version of VRCX the quick way, you should see this in the settings. Just click 'Check for update'

![image](https://user-images.githubusercontent.com/24326270/170852394-deb65d2e-cdd2-4c64-9819-2912a413a5cf.png)

Then either click 'Stable' if you want slower updates but a more stable app; 'Beta' if you want more frequent updates but expect more bugs to pop up.

![image](https://user-images.githubusercontent.com/24326270/170852448-92915789-5820-4842-90bb-d8306e741003.png)

Then select the top most version from the drop-down next to and the rest should be self-explanatory.

![image](https://user-images.githubusercontent.com/24326270/170852496-62f316b3-3766-4b58-bb95-5bc99ce741ed.png)
![image](https://user-images.githubusercontent.com/24326270/170852498-a1b014f5-f2fd-410e-9b31-a05d73d4cef1.png)

**Comment by GODZILLA6337** [comment]
Aight Thank ya!!
Ya'll have a good evening! ^^
