### ISSUE TITLE
Problems with avatar not showing in vrchat list after adding as favorite

### ISSUE THREAD

**Issue by b3lkins** [pypy-vrc/VRCX#352]
I used to be able to add a favorite avatar through vrcx and it will instantly show in my favorites list in vrchat.  It does show in vrcx but wont show up in the avatar list in vrchat instantly.

This last week or so it seemed to stop working and does not update instantly like it used to in my vrchat favorites list. 

I found if i log out of vrchat and log back in it will show the new avatar in the list but only if i do this will it ever show. 

Using latest version VRCX 2022.05.05.1

**Comment by b3lkins** [comment]
Been using it for a while without this ever happening.  Was always instant. Weird it just started now... kinda seems like after the recent vrchat update is when it started happening.

**Comment by Natsumi-sama** [comment]
It's seeming random with who and when people get affected by it, I think you've been lucky or unlucky depending on how you want to look it at.

**Comment by b3lkins** [comment]
Are you talking about the bug that none of the avatars will show in the list? I have had that happen also.  But this bug i am talking about it will show all my avatars in my favorite list but just not the newest one I just added until i log out and back in.

**Comment by Natsumi-sama** [comment]
No I was talking about the bug where newest favorites/uploads aren't shown.

**Comment by b3lkins** [comment]
Okay.  Guess I was lucky then.. =P  Was a nice feature when searching for avatars and trying them out.  Sucks having to log out and then log back in just to try a avatar.  Before I could try as many avatars as i wanted and never had a issue with them showing up instantly.  Thanks for the fast response!

**Comment by Natsumi-sama** [comment]
It might come right in a few days.
