### ISSUE TITLE
(question) Avatar and World tab don't show anything for other users

### ISSUE THREAD

**Issue by AndrewAssassins** [pypy-vrc/VRCX#356]
So I wanted to know why the Avatar and World option of other users don't show anything when using VRCX? if the options were removed in normal VRChat why does VRCX still have it?

**Comment by information-redacted** [comment]
The world option works just fine? (See attached image).

As for the Avatars tab, at this point, it still works for your own user at the very least, and I'm unsure of other cases in which it may work.
![image](https://user-images.githubusercontent.com/87243354/173667263-21208f48-675d-48a0-be54-fd0dd30b5497.png)

**Comment by AndrewAssassins** [comment]
Can You help me then? Because I don't know how to see them.El 14 jun. 2022 3:02 p. m., Natsumi ***@***.***> escribió:
Yup Avatars tab shows own and favorited avatars as well as other users public avatars if you have a remote avatar database provider set.

**Comment by AndrewAssassins** [comment]
Does it only work with public worlds?El 14 jun. 2022 2:56 p. m., "[information redacted]" ***@***.***> escribió:
The world option works just fine? (See attached image).
As for the Avatars tab, at this point, it still works for your own user at the very least, and I'm unsure of other cases in which it may work.

**Comment by information-redacted** [comment]
Yes, you can only view someone else's public worlds. If you go onto _your_ profile, you will also see your private worlds.

**Comment by Natsumi-sama** [comment]
https://gist.github.com/RequiDev/d209f79c6d663dbd5c1428ebbe2c944a

**Comment by AndrewAssassins** [comment]
I’m trying to get his one but can’t Access the file avtr_7aa98c2c-b95f-4cf8-bdf1-23e12d11b35e and a variant which I don’t know who has it because only one model appears in their profile.
Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado: martes, 14 de junio de 2022 3:29 p. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [pypy-vrc/VRCX] (question) Avatar and World tab don't show anything for other users (Issue #356)


https://gist.github.com/RequiDev/d209f79c6d663dbd5c1428ebbe2c944a<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgist.github.com%2FRequiDev%2Fd209f79c6d663dbd5c1428ebbe2c944a&data=05%7C01%7C%7Caf1d13b598f64db5066708da4e3c242c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637908317463445251%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yvfnaLAiwiB2UuuVYbjb4DKHCl2X7MzX1lSF%2BRy0suQ%3D&reserved=0>

**Comment by SalbugVR** [comment]
> I’m trying to get his one but can’t Access the file avtr_7aa98c2c-b95f-4cf8-bdf1-23e12d11b35e and a variant which I don’t know who has it because only one model appears in their profile.

That's because the avatar ID you listed is private.

![image](https://user-images.githubusercontent.com/24326270/173717942-2601cbc6-18d8-43cc-991f-4514711b8056.png)

**Comment by AndrewAssassins** [comment]
> 

so until the model is public, I can't get the file, then why private in vrcx is an option?

**Comment by AndrewAssassins** [comment]
![image](https://user-images.githubusercontent.com/98129486/174619692-70d6fe43-c010-49c5-ad5c-0b5903349feb.png)
Is not working for me

**Comment by SalbugVR** [comment]
Looks like you're viewing your own. If you're looking at your own avatars, none will show up if you don't have any uploaded.

**Comment by AndrewAssassins** [comment]
no I was watching another user profile but none appeared
> Looks like you're viewing your own. If you're looking at your own avatars, none will show up if you don't have any uploaded.

**Comment by SalbugVR** [comment]
Another user's _public_ avatars will only show up if you are using a remote avatar database. To use that, you plug a API url such as this >> (https://requi.dev/vrcx_search.php) into the remote avatar db field in VRCX.

![image](https://user-images.githubusercontent.com/24326270/174681272-54f01aeb-89ea-4f5d-ab70-cd10edbce4cb.png)

**Comment by AndrewAssassins** [comment]
I can’t in this case

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: [information ***@***.***>
Enviado: martes, 14 de junio de 2022 3:21 p. m.
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [pypy-vrc/VRCX] (question) Avatar and World tab don't show anything for other users (Issue #356)


Yes, you can only view someone else's public worlds. If you go onto your profile, you will also see your private worlds.
