### ISSUE TITLE
[Bug] Doesn't register logout, retains location.

### ISSUE THREAD

**Issue by GenesisAria** [pypy-vrc/VRCX#357]
After closing vrchat, recently it doesn't register the logout.  I did not change or update anything it just started always persisting my location after getting out of vrc.  Nobody else sees me online, but it will feed the location data to discord rich presence.

**Comment by Natsumi-sama** [comment]
This info is based on the VRChat.exe process running using `Process.GetProcessesByName("vrchat")` so either VRChat failed to close correctly or you have another process called VRChat running.

**Comment by GenesisAria** [comment]
No such application was running, i even tried closing all of steamvr and steam itself, and anything else that could be interacting with it.

However on further inspection, i did find an instance of VRChat.exe at a ghost process hung and suspended in process explorer, this task was not visible in task manager and was denied access in process explorer as well, required a taskkill /f /pid <pid of hung vrchat process>

**Comment by GenesisAria** [comment]
Yeah somehow my VRChat.exe keeps hanging as a ghost process, and now it's not killable by any means.
![Process_Explorer_-_Sysinternals_www sysinternals  (2022-06-24_06-23-38)](https://user-images.githubusercontent.com/25147974/175545087-9b16bc32-324c-4fd8-a84e-8ed6712095df.png)

**Comment by Natsumi-sama** [comment]
There isn't a simple work around that can be done for this it would be much easier to fix whatever is causing this broken process.
