### ISSUE TITLE
[Question] How to get the id of all players in a world instance?

### ISSUE THREAD

**Issue by Kieaer** [pypy-vrc/VRCX#359]
I'm making a program to find specific users.
It doesn't seem to exist in the VRChat API, how did you do it?

**Comment by Natsumi-sama** [comment]
You can't, VRCX only knows about player userId's in the instance that are your friends with by finding matching displayName from friends list. Only other way is using the player search endpoint to find a user with a matching displayName from the result, the search isn't great and doesn't work all the time also would be a lot of extra API calls.

**Comment by Kieaer** [comment]
So, how was it possible to check the id of non-friend users in gamelog?

**Comment by Natsumi-sama** [comment]
The companion mod has userId's as well as if you have API logging enabled and select the user in-game VRCX will fetch that users details.

**Comment by Kieaer** [comment]
Thanks for answer!
