### ISSUE TITLE
broken active friends list

### ISSUE THREAD

**Issue by pypy-vrc** [pypy-vrc/VRCX#36]
vrc devs did an API patch today. Now we can't get all active friends at once. in other words, we need to get active friends one by one. it's annoying really. :weary:  the more api calls, the more server loads.

**Comment by Murkur** [comment]
yeah you just need to add the new "do not disturb" status from API into vrcx vrchat loves to be inefficient

**Comment by pypy-vrc** [comment]
@Murkur yeah, i was just about to see that. but something unexpected came out. :cry:

**Comment by Murkur** [comment]
Yeah I tried adding it myself but I suck at JS went throught Insomnia REST client just to check the status 

```
{
  "error": {
    "message": "Validation failed",
    "data": [
      "status must be one of [\"active\",\"offline\",\"busy\",\"ask me\",\"join me\"], not ''"
    ],
    "status_code": 400
  }
}
```

**Comment by pypy-vrc** [comment]
![image](https://user-images.githubusercontent.com/25771678/75251618-4d750800-581e-11ea-9cab-c006a3e9cf50.png)
🤔

**Comment by Murkur** [comment]
I get the same error as far as i can tell the Ask Me status has not been implemented completely as seen on https://medium.com/vrchat/upcoming-status-system-changes-ed7f824e96ff
it only lists the Do not Disturb as being live

```
{
  "error": {
    "message": "\"You can't set your status to 'ask me' if you're not whitelisted.\"",
    "status_code": 403
  }
}
```

**Comment by Murkur** [comment]
whats odd is yesterday when I was trying to add do not disturb myself it was listed as being a valid status in the API now its not

**Comment by pypy-vrc** [comment]
the status of friends fetched from "/friends?offline=true" is offline, but fetched from "user/{id}" is active. what the ??
