### ISSUE TITLE
[Feature Request] Hide specific users on feeds

### ISSUE THREAD

**Issue by WTFBlaze** [pypy-vrc/VRCX#360]
**Requested Idea In Depth:**
The ability to right click a friend and toggle blacklisting them from appearing in your feeds.

Example reason why this feature is useful. This friend is funny but this feature is annoying.
![image](https://user-images.githubusercontent.com/35648047/176003087-08b43cdc-cab5-480c-bfd9-7594310738cd.png)

**Comment by Natsumi-sama** [comment]
Dupe https://github.com/pypy-vrc/VRCX/issues/266
