### ISSUE TITLE
Player count in instance isnt shown correctly.

### ISSUE THREAD

**Issue by fwenny** [pypy-vrc/VRCX#362]
Ive seen that often, when clicking a friend, it would say, for example, '2 (1)'. Even after clicking Refresh player count, it says that.
![image](https://user-images.githubusercontent.com/44194453/176553732-b6ff6358-9abd-4545-88cc-acaaeea722f0.png)

But then, when I click the map name, and I see my friends instance, it will say 1 (1)
![image](https://user-images.githubusercontent.com/44194453/176553775-f9d1b2e0-b580-4756-9ce1-5624a2d0dfab.png)

I need to click refresh player count for it to update to 2 (1), which is strange because its suppose to know that there are 2 people already.

Furthermore, existing the map view, and then clicking the map name again, will once again show 1 (1), and I have to click refresh again.

**Comment by Natsumi-sama** [comment]
Hmmm not sure but it will be either one of 2 things, the number only ever updates once when the dialog is opened or because there are 2 different endpoints this value can come from `/worlds` and `/instances` both can return different values because VRChat.

**Comment by fwenny** [comment]
'because vrchat' lol sounds about right.
alrighty, just figured id mention this in the off chance its something you can fix on your end. 

thank you. =)
