### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by GenesisAria** [pypy-vrc/VRCX#366]
I frequently find vrcx using upwards of 3+GB of ram for no conceivable reason, and it progressively increases the longer the program is open.

As time has gone on, the program has taken longer and longer to load at startup each update, making restarting it a chore.

**Comment by Natsumi-sama** [comment]
There are a few options you can set to help with RAM usage, In `Appearance` lower `Max Table Size` and in `Advanced` lower `Auto Clear Cache` timer. Also next release has slightly faster startup times.

**Comment by GenesisAria** [comment]
There's no reason for it to be using 5GB of memory... most of this should be read off of the api or files on disk when needed.

**Comment by Natsumi-sama** [comment]
Hence my previous comment, try lower those values.
