### ISSUE TITLE
VRCX makes me appear offline

### ISSUE THREAD

**Issue by aaSensei** [pypy-vrc/VRCX#370]
Sometimes, while VRCX is running my status will appear as offline in-game, but it will show that I am active on the website instead. Closing VRCX solves the problem, but I'm unsure if there is a setting that causes this.

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/issues/355 It's a known and uncommon bug, Sadly I still have no idea what causes it because I've never had it.
