### ISSUE TITLE
Add local world favorite and categorys

### ISSUE THREAD

**Issue by Kieaer** [pypy-vrc/VRCX#375]
Due to update VRChat security update, most mods aren't work in Open Beta.
It's a fatal problem for world explorers.
I can't put more than 500 favorites into 256 slots again.

What I want is a local world favorite and more category features.

**Comment by Natsumi-sama** [comment]
It has been planned for a long time but it's going to take some time to implement.

**Comment by Kieaer** [comment]
Can you please make it compatible with favcat export?
export format is ``<world id> <world name>``
![image](https://user-images.githubusercontent.com/44261958/180909740-ab4925aa-b703-4f17-9eae-435af0b46457.png)

**Comment by Kieaer** [comment]
![image](https://user-images.githubusercontent.com/44261958/180912772-609c3973-3384-4e28-8b97-0e7c416981c5.png)
categorys export format
useful if there's an import feature for each category

**Comment by pobgithub** [comment]
For avatars as well please :)

**Comment by Aliceto4ki** [comment]
Was going to suggest that as well, please add this. With local world favorites we will also be able to finally favorite private worlds and manage them much easier than just bookmarking in browser.

**Comment by Kieaer** [comment]
Nice update! I checked in Nightly version.
