### ISSUE TITLE
avatar search not working

### ISSUE THREAD

**Issue by Invaliduser81** [pypy-vrc/VRCX#378]
Avatar search recently broke, is this because of vrc's eac?

**Comment by SalbugVR** [comment]
https://requi.dev/avatar.php

> As of 25/07/2022 VRChat announced an Open Beta which includes a kernel anti-cheat known as [Easy Anti-Cheat](https://easy.ac/).
> This is a horrible change and will harm VRChat more than it will help it. VRChat has always had a honestly terrible stance on (even wholesome) modding, but we co-existed without any big problems.
> 
> Now they want to block all Quality of Life mods, all protection mods like [AdvancedSafety](https://github.com/knah/VRCMods#advancedsafety) and [NetworkSanity](https://github.com/RequiDev/NetworkSanity) that prevented you from crashing from common crashing methods.
> All of that, only to prevent a minority of malicious and toxic people in the game that also happen to use mods to be a nuisance around other people.
> 
> With this change people using crashers will be more powerful than before. People using (Photon-)Bots will be more powerful than before. Because YOU won't have any protection due to Easy Anti-Cheat.
> 
> This free service to search for avatars won't be available for the time being. If VRChat decides to stick with EAC I will be shutting it down entirely and maybe release the database to the public.
> 
> If you are subscribed to VRC+ and think this change shouldn't happen, cancel your subscription. That's probably the only way they will listen.
> 
> In the meantime, feel free to check out the private server project which aims at hosting your own VRChat by emulating its services:
> https://discord.gg/bzb6TCfXsr
> 
> To VRChat:
> Come on. You can do better.
