### ISSUE TITLE
[Feature request] Sort friends by number

### ISSUE THREAD

**Issue by GenesisAria** [pypy-vrc/VRCX#38]
Friends are numbered by when they were added in order, would be nice to have a way to sort this.  It is really fascinating writing these all down.

Possibly a date tooltip if date added exists?

**Comment by Fusl** [comment]
> date tooltip
That's unfortunately not possible. We can only figure out the friend nr because VRChat "sorts" an array in a specific API endpoint this way.

**Comment by pypy-vrc** [comment]
sorry, but it is not enough to add this as a feature. 😅 Fortunately, there is a way to find out who the friend with the number is. Just look at the JSON on the more tab. Then expand the friends section, and the user id will be listed. The order of this is the order added. With this, you can search one by one in Direct Access.

**Comment by Natsumi-sama** [comment]
Closing because inactive.
