### ISSUE TITLE
New Instance-Invite-Invite myself, not workin'

### ISSUE THREAD

**Issue by dev0634** [pypy-vrc/VRCX#383]
error when inviting myself from the dialog below
(not 'self invite' button, invite dialog and choose my self.)

![Untitled-1](https://user-images.githubusercontent.com/110243737/181924201-30a4f719-aba2-43cb-9cd9-91c5cb3fc89c.png)

result err msg:
403 Forbidden
"You need to be friends with that user first․"

**Comment by Natsumi-sama** [comment]
Thanks VRChat wew it works for me, maybe because I used to be friends with myself eh either way I'll fix it.

**Comment by Myrkie** [comment]
alright pog thanks for the notice
