### ISSUE TITLE
Unable to view avatars of VRC+ members

### ISSUE THREAD

**Issue by THRM-X** [pypy-vrc/VRCX#385]
When viewing people's profiles off of VRCX, it usually displays "avatar info," however I've noticed that with _most_ vrc+ members, it's just a "-" in place of where the avatar name is. There are some people it doesn't do this for, but it's like this for most.

**Comment by Asovrix** [comment]
https://github.com/pypy-vrc/VRCX/issues/333#issuecomment-1100476276
