### ISSUE TITLE
Lauching the game through VRCX does not use the EAC launcher

### ISSUE THREAD

**Issue by fwenny** [pypy-vrc/VRCX#386]
I am unable to join friends instance via VRCX because it launches the game without EAC, which makes me not load into a world.

**Comment by Natsumi-sama** [comment]
ah yes I forgot about that I'll fix that.

**Comment by Myrkie** [comment]
Might be caused by VRCX calling vrchat.exe?

the new launcher uses start_protected_game.exe.

**Comment by Natsumi-sama** [comment]
Could use "VRChat Path Override" in "Launch Options" to point to that exe instead for now.
