### ISSUE TITLE
Self inviting no longer fuctional

### ISSUE THREAD

**Issue by Myrkie** [pypy-vrc/VRCX#389]
noticed that the self invite button no longer works, VRChat responses with a 404 endpoint not implemented.
```
404 Not Found
"The endpoint you're looking for is not implemented by our system."
"instances/wrld_fac11e5f-1c73-4436-8936-a70b80961c5a:41142~region(eu)/invite"
```
this response happens with every possible instance even ones you have created from the instance creation dialog, possibly it has moved?

**Comment by Natsumi-sama** [comment]
yup fixed on nightly build https://github.com/pypy-vrc/VRCX/issues/383
