### ISSUE TITLE
[Feature Request] Increase Avatar Favoriting Capabilities

### ISSUE THREAD

**Issue by VirtualViolet98** [pypy-vrc/VRCX#390]
Unless this is already in the works, changing the maximum amount of VRCX avatar favorites to reflect the August 4th VRC update (of having 50 avatars in each VRC+ group) would be greatly appreciated. I am trying to add new avatars to my favorites via avatar ID, and I am getting a message telling me that I am unable to do so.

**Comment by Natsumi-sama** [comment]
I don't think VRChat have pushed this update yet, that'll be why you're getting an error.
