### ISSUE TITLE
Adding in Synced User Notes

### ISSUE THREAD

**Issue by Volkor3-16** [pypy-vrc/VRCX#392]
With the introduction of User/Friend Notes, it would be cool to have a way to sync said notes that we've spent a while making in VRCX over to the web!

I've done a bit of digging, and as much as I'd love to work on this myself, im not that much of a programmer

api is https://vrchat.com/api/1/userNotes

request payload is:
```json
{"targetUserId":"usr_id_goes_here",
 "note":"plain text goes here"}
```
and /should/ respond with 200 code, and 
```json
{"id":"unt_removed for privacy i guess",
 "userId":"my own userid",
  "targetUserId":"the person who's text i just set",
  "note":"the note i just set",
  "createdAt":"2022-08-10T13:11:38.590Z"}
```

when emptying the field, it responds with `"User note cleared."` 200 code

additionally, https://vrchat.com/api/1/users/useridhere now returns a "note" value, with the note's text too

**Comment by Natsumi-sama** [comment]
Yup this is known but my todo list is long and my time is limited, the plan is to make a migrate button to move all local notes then use this instead BUT it seemly has a very low character limit of 256 so  it'll have to be optional meaning I'll have to support both and that'll be a pain.
