### ISSUE TITLE
Steam Overlay Features

### ISSUE THREAD

**Issue by AkumaAbaddon** [pypy-vrc/VRCX#393]
So I toggled the steam overlay features 

Notifications -> SteamVR Overlay (on) | Overlay Notifications (on)

Desktop Notifications -> Game Running

In game in the steam overlay I see nothing on VRCX tho

**Comment by Natsumi-sama** [comment]
If you have a iGPU give this a try https://www.windowsdigitals.com/force-chrome-firefox-game-to-use-nvidia-gpu-integrated-graphics/ also make sure to start VRCX before VRChat.

**Comment by AkumaAbaddon** [comment]
Thats not the issue, everything on my system uses my GTX 1060

**Comment by Natsumi-sama** [comment]
Just checking you are in VR right, not using the desktop Steam overlay?

**Comment by AkumaAbaddon** [comment]
Desktop

**Comment by Natsumi-sama** [comment]
The SteamVR feature requires SteamVR and wont work in desktop mode.
