### ISSUE TITLE
Avatar Search third option buttons disabled or now working

### ISSUE THREAD

**Issue by InactiveCoyote** [pypy-vrc/VRCX#395]
i tried to search for avatars but i when i go to by update or the other options i cant click on then not sure they were disable for a reason but it makes it useless finding newer avatars

**Comment by Myrkie** [comment]
Avatar search has not been possible for years now, the buttons existence has been there for use of remote database providers that would allow you to search in these databases, the last known public database was shut down after the official addiction of EAC.
