### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by AndrewAssassins** [pypy-vrc/VRCX#396]
so If I used my steam account with VRCX what can I do If I can't longer log in with steam?

**Comment by Myrkie** [comment]
create an account on vrchat.net and then merge your steam with your vrchat account.

**Comment by Myrkie** [comment]
https://help.vrchat.com/hc/en-us/articles/360062659053-I-want-to-turn-my-Steam-Oculus-or-Viveport-account-into-a-VRChat-account instructions provided here
