### ISSUE TITLE
Alternatives for Asseturl?

### ISSUE THREAD

**Issue by AndrewAssassins** [pypy-vrc/VRCX#397]
So I heard VRChat update that included Zero mods and stuff also remove the assert url of public models, to avoid ripping, is there any alternatives if that option is gone, or vrchat is becoming crappier each time?

**Comment by Myrkie** [comment]
asset urls were removed from public models well over 4-5 months ago, vrchat doesn't respond with an asset url if the origin of the request is not from the game client.

**Comment by Myrkie** [comment]
https://github.com/pypy-vrc/VRCX/issues/189
https://github.com/pypy-vrc/VRCX/issues/182

reported in these 2 issues

**Comment by AndrewAssassins** [comment]
> asset urls were removed from public models well over 4-5 months ago, vrchat doesn't respond with an asset url if the origin of the request is not from the game client.

so even if you have the url for example this model I can't use it? 

![image](https://user-images.githubusercontent.com/98129486/185026582-e99a0281-cf5d-4b40-9961-5e7bbf9f98cb.png)

**Comment by Myrkie** [comment]
if it model is private you cannot see it, if the model is public and you have the avatar ID you can wear it, just add it to your favorites and swap to it ingame. the asset url is only provided to the game client which uses a useragent that allows it to get the response with asseturl (Or else public avatar pedestals would break)

**Comment by AndrewAssassins** [comment]
> if it model is private you cannot see it, if the model is public and you have the avatar ID you can wear it, just add it to your favorites and swap to it ingame. the asset url is only provided to the game client which uses a useragent that allows it to get the response with asseturl (Or else public avatar pedestals would break)

I have the avatar, and is the creator made it public, but the last part confuse me so that's means even if I'm using it I can't get an asset url

**Comment by Myrkie** [comment]
if your using it you can still get the asset url but only if your using it. the question is why do you need it?

**Comment by AndrewAssassins** [comment]
I like seing them in blender and posing them a bit, since I don't have a vr set to move them in anyway

**Comment by Myrkie** [comment]
you are aware that ripping models is very much against the terms of service and can get you banned?

**Comment by AndrewAssassins** [comment]
yes, I know I don't have any intentions on using them as my own or distribution in any site.

**Comment by Myrkie** [comment]
that is still very against the terms of service, redistribution or not.

**Comment by AndrewAssassins** [comment]
how I delete the issue if I'm gonna get this scolding
