### ISSUE TITLE
Just a quick question 

### ISSUE THREAD

**Issue by Invaliduser81** [pypy-vrc/VRCX#399]
hello, to keep it simple i'd like to know what you exactly meant by "it will lead to a wrist slap in the future" in your vrcx 2022.03.31 build, if it means i'd likely to be banned i dont understand how vrchat would be able to detect that

**Comment by Myrkie** [comment]
they can tell by your download headers and activity, if your not in game its obvious.

**Comment by Natsumi-sama** [comment]
It doesn't work anymore so you wont get banned unless you fix it yourself then there will be risk of a ban.

**Comment by Invaliduser81** [comment]
alr then
