### ISSUE TITLE
[Suggestion] Remember login details

### ISSUE THREAD

**Issue by fwenny** [pypy-vrc/VRCX#40]
When my IP changes, VRChat requires a relogin. VRCEX would automatically login, while VRCX requires you to reenter your details.

**Comment by pypy-vrc** [comment]
It was possible because VRCEX stored the user's ID and password. But it is sensitive information. It would be terrible if it leaked. Therefore, VRCX does not store such information. If you are logged out, it will be annoying, but please log in again. 😖

**Comment by fwenny** [comment]
Understandable, thank you. =)

**Comment by Fusl** [comment]
VRChat is considering removing this limitation of the authcookie being treated as invalid when being used from a different IP, the feature request for this is tracked at https://feedback.vrchat.com/feature-requests/p/allow-authcookie-to-be-used-from-a-different-ip-address-extra-features - Once this feature is implemented and authcookies are no longer treated invalid on a different IP, this issue will no longer be present.
