### ISSUE TITLE
New version scrubbed settings

### ISSUE THREAD

**Issue by GenesisAria** [pypy-vrc/VRCX#405]
My login, all my settings, all my log history, are all completely gone.

**Comment by Natsumi-sama** [comment]
Did you close VRCX just after it updated? can you check `%AppData%\VRCX` to see if `VRCX.sqlite3` is still there? the database may have been corrupted and can be repaired.

**Comment by GenesisAria** [comment]
Well i'd logged in and it loaded a bunch of stuff, if that means it's been overwritten then that is a yikes

**Comment by Myrkie** [comment]
The database is located at `%appdata%/../Roaming/vrcx` its the sqlite3 database file

**Comment by Natsumi-sama** [comment]
In the past database corruption would cause an exception stopping the program from loading.

**Comment by GenesisAria** [comment]
No it loaded up normally, it just doesn't have any history in friend log or notifications or feed or anything.  It was completely blank slated.

**Comment by Natsumi-sama** [comment]
What size is your database file?

**Comment by GenesisAria** [comment]
it's 540KB, but it's been open for a couple hours.

**Comment by Myrkie** [comment]
well if you have windows back up or file history enable you could try to recover a "previous" version of the file by right clicking the folder > Properties > Previous versions, and check if one can be recovered, if its already been overwritten nothing can be done without a backup.

**Comment by Natsumi-sama** [comment]
Ouch yup that's fully gone, did you close VRCX after it updated and before it was cleared?

**Comment by GenesisAria** [comment]
No i clicked download, and when it was ready i clicked install.

**Comment by Natsumi-sama** [comment]
If that's the case then I don't think anything specifically in this update caused it (fingers crossed). But that also means I have no idea was caused it my best guess though would be database corruption.

**Comment by GenesisAria** [comment]
I have my VRCX cache folder symlinked onto a different drive, but that shouldn't affect anything.  the symlink folder wasn't replaced with a regular folder, else i would have just put the symlink folder back.

**Comment by Natsumi-sama** [comment]
I've thought about having backups but the issue with that is some people have huge databases and don't have the space on their C drive, I guess I could make it optional but there isn't an easy solution that would work for everyone.

**Comment by GenesisAria** [comment]
> in that case unless a backup exists there is nothing that can be done, might be a wise option to add auto backup to the SQL file say every 3 days? @Natsumi-sama

And/orr have it create a backup prior to updating.

**Comment by GenesisAria** [comment]
> I've thought about having backups but the issue with that is some people have huge databases and don't have the space on their C drive, I guess I could make it optional but there isn't an easy solution that would work for everyone.

Just give an option to pick the cache directory? or at least the backup directory...

**Comment by Natsumi-sama** [comment]
There is a launch parameter for custom config directory `--config` and yes an option for a custom backup directory would make sense.

**Comment by GenesisAria** [comment]
I figured out why this is happening, because it happened again.
I moved the cache into a subfolder inside the VRCX folder to get it out of my appdata folder, and when VRCX updates it deletes everything and overwrites.  I made a copy of that subfolder beside it incase it overwrote my stuff, but it deleted everything.
