### ISSUE TITLE
In the Friends List tab, the unfriend button is off screen

### ISSUE THREAD

**Issue by AshtonSparx** [pypy-vrc/VRCX#407]
In order to unfriend anyone on this tab, I have to stretch the application across my other monitors in order to click the X button

![image](https://user-images.githubusercontent.com/53165730/189519791-0151b862-da74-4ef7-bc41-c39255be36da.png)

**Comment by Natsumi-sama** [comment]
If you scroll to the bottom of the list there is a horizontal scroll bar, or you can middle click to scroll sideways.

**Comment by AshtonSparx** [comment]
> If you scroll to the bottom of the list there is a horizontal scroll bar, or you can middle click to scroll sideways.

ooooh That, I didn't know! I _very_ rarely middle click applications besides browser and discord because it rarely works so I never thought about that. Muh bad! VRCX is pretty awesome and I thank you for it!

**Comment by Natsumi-sama** [comment]
It is a bit of an oversight though I never thought about the table width being different at lower resolutions, as a lazy fix for now I'll left align the button so scrolling wont be necessary to click it.
