### ISSUE TITLE
[Feature Request] Export log lists, especially friends

### ISSUE THREAD

**Issue by GenesisAria** [pypy-vrc/VRCX#410]
Specifically for friend history.  Recently when my logs wiped, the one i feel the most is the loss of the friend log.

**Comment by EpicGazel** [comment]
Consider backups of your VRCX.sqlite3 file (%appdata%/VRCX). Since the file will largely be the same between backups, I'd recommend an incremental backup. I'm familiar with zpaq so I used that and set up a backup every login using task scheduler. Size is 63% rn so should be a problem.
