### ISSUE TITLE
it always logs me out

### ISSUE THREAD

**Issue by Progamer75303** [pypy-vrc/VRCX#411]
it logs me out after about 20 seconds

**Comment by Natsumi-sama** [comment]
Could you press `Ctrl + Shift + I` click the console tab then screenshot any error.

**Comment by Progamer75303** [comment]
> Could you press `Ctrl + Shift + I` click the console tab then screenshot any error.

![image](https://user-images.githubusercontent.com/78344868/190877128-f6633255-a2c7-45e1-9b85-db07531148ba.png)

**Comment by Natsumi-sama** [comment]
Woooooah how many friends do you have?

**Comment by Progamer75303** [comment]
> Woooooah how many friends do you have?

6370

**Comment by Natsumi-sama** [comment]
WOW yea this is a VRChat bug or oversight you'll need to report this to them, I can stop it from logging you out but it will be missing info for all those friends past the 5000 point. I think the last stable version of VRCX wont log you out for this error so you could downgrade for now as a temporary work around.

**Comment by Progamer75303** [comment]
i already have thx

**Comment by Natsumi-sama** [comment]
I've put a fix in the latest nightly, let me know if that works for you.

**Comment by Progamer75303** [comment]
it doesnt work sadly

**Comment by Natsumi-sama** [comment]
Same error in console?

**Comment by Progamer75303** [comment]
![image](https://user-images.githubusercontent.com/78344868/192590584-e6340f3c-d36b-40aa-b6a0-49c77e353561.png)

**Comment by Natsumi-sama** [comment]
I just lowered the limit for myself to test and it worked fine, are you sure you tried the nightly build? In VRCX Settings > General click on check for update then from the drop down select nightly or install it from here https://github.com/Natsumi-sama/VRCX/releases/latest

**Comment by Progamer75303** [comment]
oh i didnt install the nightly

**Comment by Progamer75303** [comment]
now it works
