### ISSUE TITLE
Avatar Search and Cache Working Unexpectedly

### ISSUE THREAD

**Issue by EpicGazel** [pypy-vrc/VRCX#412]
Version: 2022.09.09
Remote Avatar Database: Disabled

When using search for all (public + private, local+remote) with no filter it only shows only avatars created by the user:
![Normal Settings Search](https://user-images.githubusercontent.com/20029624/190882150-4bd66fd2-ce88-415e-8ccd-cd04f21552a3.jpg)

Even filtering to public/private only shows the current account's avatars.

However, if any valid search is entered in the search bar, such as "a", it will list avatars that did not appear before(presumably coming from the cache or user avatar history):
![Single Letter Search](https://user-images.githubusercontent.com/20029624/190882273-e96d25d3-5c4f-49d2-9655-7a4f30e5a997.jpg)
![Single Letter Search Public](https://user-images.githubusercontent.com/20029624/190882298-d46e6ae0-28f8-4338-99fd-79f6f041886f.jpg)

I believe the expected behavior is to be able to sort these results without entering a query. If the search is this way to avoid loading too many avatars at once, please consider adding an option to circumvent this.

**Comment by Myrkie** [comment]
the way the search is returned I based on the remote databases method, such as requidevs search before shutdown wasn't able to return case sensitive avatars because of the SQL query it ran.

**Comment by EpicGazel** [comment]
A carry-over from a deprecated feature then? Still a little confusing that, if I'm understanding this correctly, the local avatar cache is being treated the same as a remote database. Does this mean you agree that this should be corrected?

**Comment by Myrkie** [comment]
as far as im aware you should only get your avatars as a result in the search unless you have a remote database added in Settings > advanced > Remote Database Provider. so if your getting cached results then I would have to agree that is probably unintentional.

**Comment by EpicGazel** [comment]
I agree with you that that appears to be the intention. However, I do believe the ability to search your cached avatars should be preserved.

**Comment by Myrkie** [comment]
agreed

**Comment by Natsumi-sama** [comment]
This was old intended behavior but I'll change it to return all avatars in cache.

**Comment by EpicGazel** [comment]
Noting, as of 2022-09-18T14.06-7abece9, when running a direct access lookup of an avatar, the avatar will show up in search until VRCX is restarted. When searching for the same avatar after a restart, no avatar of the name appears until a direct access lookup is run again. 

Additional notes for the original issue, having to enter a search query is better and avatars in the cache_avatar table (VRCX.sqlite3) don't show up in search. Seemingly only favorites and avatars accessed in the current session appear in the search.

**Comment by Natsumi-sama** [comment]
This is all currently intended behavior.
VRCX only stores avatar history in the cache_avatar database table.
Only the previous 100 avatars from avatar history are stored in JS cache because having a large amount of entries in JS cache occupies a lot of RAM.
VRCX search only queries for avatars from JS cache.

It is planned to have an additional SQLite query to also search through the cache_avatar database table when doing a search.
But this will cause additional problems to solve when avatars become deleted or private.
