### ISSUE TITLE
Self-inviting to an instance you have been in or been invited to is still possible

### ISSUE THREAD

**Issue by 64766C** [pypy-vrc/VRCX#414]
I think previously self-inviting was done using this request https://vrchatapi.github.io/docs/api/#post-/instances/-worldId---instanceId-/invite which got broken in the security update.

Nowadays the same thing can be done with this endpoint instead https://vrchatapi.github.io/docs/api/#post-/invite/myself/to/-worldId---instanceId-

It would be nice if you could reimplement self-inviting within VRCX.

Example request:
```
POST /api/1/invite/myself/to/wrld_4432ea9b-729c-46e3-8eaf-846aa0a37fdd:37056~private(usr_353f05b1-3210-4640-b362-412e4f7c3743)~region(eu)~nonce(ED032C699F638DD986C659A4B18459F9E81E135D2688DDE9) HTTP/2
Host: vrchat.com
Cookie: cookies removed
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
Content-Type: application/json
Content-Length: 16

{"shortName":""}
```

You can already do self-inviting with the help of VRCX but it requires a jump to the VRChat website. Let's say you have received in invitation to a private world.
1. Click the "invite" text in type column of notifications to open instance details
![image](https://user-images.githubusercontent.com/100468852/191479667-8eeaa0d2-50cf-4b56-b5c4-bcf4326b32b7.png)

2. Click the instance ID from the list to open up this popup: 
![image](https://user-images.githubusercontent.com/100468852/191479246-86b25885-87cb-4ccc-8d33-e0112c1772a9.png)
3. Go to the top link and click invite me.
![image](https://user-images.githubusercontent.com/100468852/191479369-d7872bd5-b323-40b8-b8f9-781a7faf43cb.png)

**Comment by SalbugVR** [comment]
I have tested this a bit before as well and I do agree.

![notepad_eENlkeP8cd](https://user-images.githubusercontent.com/24326270/191482495-3fffe77e-34cf-4830-8931-97f5c0c3898e.png)

**Comment by Natsumi-sama** [comment]
Already done in nighty build.
