### ISSUE TITLE
¿Asset Url no longer work?

### ISSUE THREAD

**Issue by AndrewAssassins** [pypy-vrc/VRCX#416]
So checking some random avatars I notice that the Assest url no longer works saying error 401. is this something cause by vrchat or vrcx to stop rippers?

**Comment by Myrkie** [comment]
Asset urls now require authentication of your vrchat account "auth token" aswell as the same useragent from the game, this was done by vrchats API during a security change to make it harder to acquire avatar bundles.

**Comment by Natsumi-sama** [comment]
🐒

**Comment by AndrewAssassins** [comment]
> Asset urls now require authentication of your vrchat account "auth token" aswell as the same useragent from the game, this was done by vrchats API during a security change to make it harder to acquire avatar bundles.

so they add it security keys? if is no longer copying the url

**Comment by Myrkie** [comment]
if you read what I said then you would understand, they added authentication, to download a file you will have to physically show that your account is downloading this file, the user agent is used to verify if the download is coming from the game or another source which would likely get you banned.

**Comment by Myrkie** [comment]
vrcx doesn't download any files from vrchat it only displays its thumbnails, only asset urls so far require authentication.

**Comment by AndrewAssassins** [comment]
> vrcx doesn't download any files from vrchat it only displays its thumbnails, only asset urls so far require authentication.

but is not using the assest url that outside method and is the user agent the person who made the model?

**Comment by Myrkie** [comment]
no, the UserAgent is used for webrequests that's used to verify that the file downloaded came from the game and not from someone's browser or for example someone's ripper, there is no security keys or encryption of any sort, its just basic data denial through required request headers.

**Comment by AndrewAssassins** [comment]
> no, the UserAgent is used for webrequests that's used to verify that the file downloaded came from the game and not from someone's browser or for example someone's ripper, there is no security keys or encryption of any sort, its just basic data denial through required request headers.

ah that's why the error 401. so why let vrcx still show the asset url? if using a browser will be denied and can help stopping a ripper

**Comment by Myrkie** [comment]
vrchat still needs for you to download that avatar while in game, without the asset url how could your own game download the avatar for your to wear? for example public avatars no longer show their asset url but still show other info like thumbnail and avatar ID, this is behind a user agent if you were to use the same user agent that vrchat uses then you would also get a asset URL, you can also see the asset url of the current avatar you are wearing when you select yourself an go to the JSON tab, the field "currentAvatarAssetUrl" shows this as the game needs to be aware of what avatar your using so it can download its asset bundle and cache it.

**Comment by AndrewAssassins** [comment]
> vrchat still needs for you to download that avatar while in game, without the asset url how could your own game download the avatar for your to wear? for example public avatars no longer show their asset url but still show other info like thumbnail and avatar ID, this is behind a user agent if you were to use the same user agent that vrchat uses then you would also get a asset URL, you can also see the asset url of the current avatar you are wearing when you select yourself an go to the JSON tab, the field "currentAvatarAssetUrl" shows this as the game needs to be aware of what avatar your using so it can download its asset bundle and cache it.

but what if you are using the avatar and the url still gives error 401

**Comment by Myrkie** [comment]
it will always return a 401 unless the game itself is requesting this information, you cannot download asset urls without providing the proper auth, that includes your account token and the user agent accepted by the game code.

**Comment by AndrewAssassins** [comment]
so how you get those if you have an account and use the model in that moment?

**Comment by Myrkie** [comment]
> you cannot download asset urls without providing the proper auth, that includes your account token and the user agent accepted by the game code.

see the above response
