### ISSUE TITLE
Change Image on Avatar crash VRCX Release 2022.10.05.1

### ISSUE THREAD

**Issue by ameliendeshams** [pypy-vrc/VRCX#419]
Hello,

When I'm trying to change an avatar image on the latest release [2022.10.05.1](https://github.com/pypy-vrc/VRCX/releases/tag/v2022.10.05), it crashes VRCX.
I've rolled back to release [2022.09.09](https://github.com/pypy-vrc/VRCX/releases/tag/v2022.09.09) and I can upload avatar images again.

I've tested several time switching VRCX versions but the latest seems to only have the problem.

Thanks!

**Comment by Natsumi-sama** [comment]
https://github.com/pypy-vrc/VRCX/issues/418
Version 2022.10.05 has the crash 2022.10.05.1 is fixed.
