### ISSUE TITLE
Avatar local history shows the oldest 100 records instead of the latest one.

### ISSUE THREAD

**Issue by ScrapW** [pypy-vrc/VRCX#421]
Avatar history is stored in the local database successfully and can be searched. It looks like it was just sorted wrong. Local history shows the same 100 avatars constantly.

**Comment by Natsumi-sama** [comment]
Are they your own avatars? since the last update own avatars are no longer added to history but existing entries will remain.

**Comment by Natsumi-sama** [comment]
Ah I'm surprised this went unnoticed till now.
