### ISSUE TITLE
[Feature Request] Search Avi by ID in own Remote Avatar Database Providers

### ISSUE THREAD

**Issue by XenoxUSser** [pypy-vrc/VRCX#424]
Maybe add a feature to search for avis in the own provider ive set via Avi ID cause often even when the avi is logged in that VRCX tends to hang behind to updating it into its database which means the avi is already in the providers database but takes time till it gets to VRCX ones so i cant search it yet

**Comment by Natsumi-sama** [comment]
I'm not entirely sure what your question is but if you're trying to favorite an avatar by ID you can use the direct access button (the compass) at the top right of VRCX.
