### ISSUE TITLE
[Feature Request] Support legacy user ids

### ISSUE THREAD

**Issue by CompletelyUnbelievable** [pypy-vrc/VRCX#425]
Even though [8JoV9XEdpo](https://vrchat.com/home/user/8JoV9XEdpo) is a valid user id, it is not detected when using direct access. It only works when using the entire url. I added a check in [app.js](https://github.com/pypy-vrc/VRCX/blob/master/html/src/app.js#L13190), `/^[A-Za-z0-9]{10}$/g.test(e)`, which allows it to be detected. I have no clue if this causes other issues, for instance if old worlds used the same id system back then and how that would be handled. Though I did go looking around for old worlds that might have used the old id system and I didn't find any that used it.

**Comment by Natsumi-sama** [comment]
There is still the old Direct Access options in the Profile tab for this reason, but this is a better solution and I don't see any reason why not to add this. I've had a look through some databases and couldn't find any non standard world id's, I did find a few avatar Id's but they seem very rare and mutilated on purpose so not worth worrying about.
