### ISSUE TITLE
Avatar Change Doesn't Log For Certain Users

### ISSUE THREAD

**Issue by AshtonSparx** [pypy-vrc/VRCX#426]
I've noticed when certain friends change avatars, they do not appear in the Feed List. I think I rounded down the issue to user names that start with a special character, like ❤or ・

Oddly enough, world switching, status changes gets Logged however. Their avatar info also doesn't appear. Even when I watched them switch avatars in-game

![image](https://user-images.githubusercontent.com/53165730/196797601-46f1cb72-ab63-4cf1-b607-101f25b9bc5c.png)

**Comment by AshtonSparx** [comment]
scratch my initial assumption, i have a friend with out special characters that isn't getting avatar logged

**Comment by Natsumi-sama** [comment]
Avatar names are pulled from avatar images, users with a VRC+ profile image don't have an avatar image. https://github.com/pypy-vrc/VRCX/issues/333
