### ISSUE TITLE
[Feature Request] A button to auto fill in user information in the Player List

### ISSUE THREAD

**Issue by AshtonSparx** [pypy-vrc/VRCX#427]
I would like a button somewhere to auto fills in all the information in the Player List, instead of me having to click on every user
![image](https://user-images.githubusercontent.com/53165730/197439289-803951d4-09c6-420c-8f0a-e2ade883101c.png)

**Comment by Natsumi-sama** [comment]
It's an intentional design decision because the only way VRCX can resolve a displayName to a userId is to do a user search and I'm assuming spamming this action would be an expensive task for the API and VRChat wouldn't be all too happy about that.
A much better solution would be to have VRChat log userId's when a player joins.

**Comment by AshtonSparx** [comment]
> It's an intentional design decision because the only way VRCX can resolve a displayName to a userId is to do a user search and I'm assuming spamming this action would be an expensive task for the API and VRChat wouldn't be all too happy about that. A much better solution would be to have VRChat log userId's when a player joins.

Doesn't the Refresh Friends also spam the API, but instead for a dozen or so users, it could be hundreds, if not thousands? Just curious

**Comment by Natsumi-sama** [comment]
No, the refresh button uses a endpoint that returns your friends list bulk but the other refresh button in the Friends List tab fetches your entire friends list by userId which the game has recently started doing when launched so I consider it relatively harmless. It's not only the amount of requests but the expense of the request, searches are generally a more expensive request.

You can see the web requests VRCX is executing by running `$app.debugWebRequests = true;` in the console with `Ctrl + Shift + I`.

**Comment by AshtonSparx** [comment]
Thanks for the big-brain help and for being so patient!

**Comment by Natsumi-sama** [comment]
No worries, hopefully userId's will be logged in the future to remedy this problem.
