### ISSUE TITLE
[Feature Request] Open the currently running VRCX instance instead of prompting to start a new instance

### ISSUE THREAD

**Issue by Twinki14** [pypy-vrc/VRCX#428]
- Instead of being prompted if you'd like to start a new instance, just open the currently running instance
- Add a toggle to `Application` settings `Allow more than one VRCX instance` default `false`, when toggled `true` it will prompt the user if they want to start a new instance, when toggled `false` never prompt the user and always bring the current VRCX instance to front
- Add a toggle to `Application` settings `Always start a new instance on RCX launch` default `false`, this would rely on the above new toggle to be toggled `true`, when toggled `true` it will never prompt, and instead always start a new instance

**Comment by Natsumi-sama** [comment]
Hmmm I think this would make more sense as a launch option parameter to be used in conjunction with the custom config option, something like this `VRCX.exe --ignore-instance-check --config=C:\VRCX.sqlite3` this way you could have a shortcut per account and run those shortcuts on startup.

**Comment by Myrkie** [comment]
> Hmmm I think this would make more sense as a launch option parameter to be used in conjunction with the custom config option, something like this `VRCX.exe --ignore-instance-check --config=C:\VRCX.sqlite3` this way you could have a shortcut per account and run those shortcuts on startup.

would prefer this, specifically if you use start minimized then clicking taskbar icon just asks for a new instance instead of bringing the existing instance to front

**Comment by Myrkie** [comment]
but someones you want to close it to tray and have it open back up when clicking the taskbar icon.
