### ISSUE TITLE
VRChat's API will stop providing username to users soon

### ISSUE THREAD

**Issue by dtupper** [pypy-vrc/VRCX#429]
The VRChat API will stop providing the `username` field to API users soon. We expect this change to happen within the next 1-2 weeks.

Please ensure VRCX is not using the `username` field for anything vital, such as keying. Instead, you should utilize `id` as the primary user key, as it is guaranteed to be unique and always point at the same user, no matter what they're named.

I have not looked at VRCX's code or how it handles this data. There may be no action required.

**Comment by Myrkie** [comment]
thanks for the early warning and transparency.

**Comment by DubyaDude** [comment]
![809609883603042394](https://user-images.githubusercontent.com/13679909/197668009-1212b533-0b8d-45c4-8855-e5e1589b6787.png)

**Comment by Natsumi-sama** [comment]
Thanks for the early warning this is very much appreciated it gives me plenty of time to test things so I can be certain nothing will break, I do have some small questions regarding the change if you have the time.

Does this mean the endpoint `/api/1/users/{username}/name` will also be removed?
Will the `username` field continue to exist for the users own user account?

**Comment by dtupper** [comment]
Some clarifications as requested:

Users will still be able to see their own usernames, for now. I wouldn't rely on this being present forever.

The `users/{username}/name` endpoint will be going away, yes.

**Comment by Natsumi-sama** [comment]
Ah perfect I had assumed correctly, thanks for the clarifications.

**Comment by ChisVR** [comment]
this means if i want defined user, is it going have to be user id not username. this will break my DiscordBOT to verify if people are friends with me and auto gives them role?

since saw this on Server on one carries VRChat API Docs, not sure even other way pull if user friended me or not without declare username?

i need small update what changes make on VRCX so i roughly know how pull friends without username to verify.

**Comment by Myrkie** [comment]
> 

then you use UserID, vrchat is probably doing it to more or less secure the API as your previous username could also be your oculus / steamID if your account was not created with Vrchat.net

changes to support this in vrcx are located at the nightly git repo https://github.com/Natsumi-sama/VRCX/commit/2218aa00659905740e837e13ba65d9a9eb28176f

**Comment by ChisVR** [comment]
> > 
> 
> then you use UserID, vrchat is probably doing it to more or less secure the API as your previous username could also be your oculus / steamID if your account was not created with Vrchat.net
> 
> changes to support this in vrcx are located at the nightly git repo [Natsumi-sama@2218aa0](https://github.com/Natsumi-sama/VRCX/commit/2218aa00659905740e837e13ba65d9a9eb28176f)

so you saying pulling by user id be alterative do and everything still work as same?

or is there any work rounds get user id by like Display name or something without username?

what my discord bot was temp doing using username grab user id and use user id and loop poll it check they friended and if they unfriended me it updates system.

**Comment by Foorack** [comment]
There will be work to rewrite your Discord Bot, but you should be able to do everything based on UserID rather than usernames.

**Comment by ChisVR** [comment]
ok i look into changes my discord bot so that wont loop crash me.

**Comment by Myrkie** [comment]
the user id is the primary key so it should always be used as a way to identify a user as it will never change at-least not without vrchats intervention.

**Comment by dtupper** [comment]
The `users/{username}/name` is now removed, and we're aiming to remove `username` from non-self user objects early next week.

**Comment by Myrkie** [comment]
thanks for the warning.

**Comment by dtupper** [comment]
This is being deployed right now.

**Comment by Nekromateion** [comment]
![image](https://user-images.githubusercontent.com/43814053/199846937-002b32ae-d3b2-4421-8e24-37ce8af1b3fd.png)

**Comment by DubyaDude** [comment]
F

![image](https://media3.giphy.com/media/fSAyceY3BCgtiQGnJs/giphy.gif)

**Comment by dtupper** [comment]
Deployment complete.

![](https://media.giphy.com/media/qH7J4EXzSCmBy/giphy.gif)

**Comment by Myrkie** [comment]
![anime-boy](https://user-images.githubusercontent.com/20288698/199854182-d467032c-71ae-428b-8ab0-378ed4ccafa0.gif)

**Comment by DubyaDude** [comment]
Me when I can no longer tell what the username of `XxCoomMasterxX` is:

https://user-images.githubusercontent.com/13679909/199855972-551dafcd-1a19-4154-87e2-e9cbf60dd4b1.mp4

**Comment by Georninja** [comment]
oof

**Comment by dtupper** [comment]
This API change was temporarily rolled back because it broke the client in some ways! Turns out we didn’t check everything. Whoops. We’ll get back to it after a client patch.

**Comment by Myrkie** [comment]
Damn, Jim survived.

**Comment by Natsumi-sama** [comment]
Jebaited 😛 No worries.

**Comment by DubyaDude** [comment]
MeMe

https://user-images.githubusercontent.com/13679909/199859113-5aaf495a-a3ce-4cd1-9b87-aafcc09ca23f.mp4

**Comment by AO554** [comment]
![IMG_6804](https://user-images.githubusercontent.com/24486206/199860643-df226a95-53de-4789-9ad5-c63deec38301.jpg)

**Comment by AshtonSparx** [comment]
Does this mean, once it's fully rolled out, we wont be able to see past usernames of users? Especially those who like to frequently change their username for some ungodly reason? Or will there be a way, like on Steam, to see old alias's a user went by so you can be like "Who the fuck is JesusWatching69?" Check and find out it was GangsterBroad420 all along

**Comment by Myrkie** [comment]
> Does this mean, once it's fully rolled out, we wont be able to see past usernames of users? Especially those who like to frequently change their username for some ungodly reason? Or will there be a way, like on Steam, to see old alias's a user went by so you can be like "Who the fuck is JesusWatching69?" Check and find out it was GangsterBroad420 all along

correct, past users usernames will no longer be possible to see, only the account holder can see there own pas username.

**Comment by dtupper** [comment]
> Does this mean, once it's fully rolled out, we wont be able to see past usernames of users? Especially those who like to frequently change their username for some ungodly reason? Or will there be a way, like on Steam, to see old alias's a user went by so you can be like "Who the fuck is JesusWatching69?" Check and find out it was GangsterBroad420 all along

Usernames have never been able to change, save for admin intervention.

You're thinking of `displayNames`.

**Comment by dtupper** [comment]
VRChat accounts have three identifiers:

`displayname` is the name you're thinking of. It can change every 90 days at user discretion. 
`username` is what's going away. It is either the first `displayname` you choose when you make your account, or in the case of platform accounts, `platformname_platformid`
`id` is the user ID, and that is always randomly generated, and will **never** change for a given user. It follows the format `usr_{guid}`.

**Comment by Myrkie** [comment]
> Does this mean, once it's fully rolled out, we wont be able to see past usernames of users? Especially those who like to frequently change their username for some ungodly reason? Or will there be a way, like on Steam, to see old alias's a user went by so you can be like "Who the fuck is JesusWatching69?" Check and find out it was GangsterBroad420 all along

as said by tupper the usr randomly generated ID is the primary key used for identification of a user that will never change, if a users DisplayName is changed though it will be logged by VRCX if they are your friend into the internal SQL database and you can search this through the "friend log" tab in VRCX, so that is an unofficial way to see someones past "alias" if you so desire (thats if they are you friend at the time of DisplayName change)

![image](https://user-images.githubusercontent.com/20288698/199881633-77f6eba4-4a07-48a7-9d28-41225147d771.png)

**Comment by ScruffyRules** [comment]
> It follows the format `usr_{guid}`.

Except for all those really old accounts that go by `/^[A-Za-z0-9]{10}$/g` !

**Comment by Myrkie** [comment]
> > It follows the format `usr_{guid}`.
> 
> Except for all those really old accounts that go by `/^[A-Za-z0-9]{10}$/g` !

oh true totally forgot about the old spicy accounts like `X3zL7U7wLt`
