### ISSUE TITLE
VRCX avatar lookup fail (Solved!)

### ISSUE THREAD

**Issue by HellsAvalanche** [pypy-vrc/VRCX#430]
I tried to search for avatars (yes, I have remote databases, two to be exact) and it gave me the following error
"Avatar lookup failed for (user ID) with (Remote Avatar Database) SyntaxError: Unexpected token 'e', "error code:1020" is not valid JSON"
Any help here? Did the new update to vrc bork vrcx/does vrcx just need an update and I just need to be patient, or is something else going on?
Sorry if this is a waste of time for y'all! I'm still figuring out the program and how it works and I just need a bit of help/clarification

**Comment by Myrkie** [comment]
what is the URL your using for the avatar database?

**Comment by Myrkie** [comment]
not valid Json usually happens if your using the wrong URL `https://avtr.just-h.party/` instead of the proper url `https://avtr.just-h.party/vrcx_search.php`

**Comment by 14anthony7095** [comment]
if you have `nekro-works.de` domain, it's probably the one throwing the error

**Comment by Myrkie** [comment]
> if you have `nekro-works.de` domain, it's probably the one throwing the error. So remove `https://nekro-works.de/vrcx_search.php` if you have it

yeah `https://avtr.just-h.party/vrcx_search.php` is the replacement domain for `nekro-works.de`

**Comment by HellsAvalanche** [comment]
Thank y'all!! I was using nekro, so that was my issue, many thanks for the replacement domain!!

**Comment by Nekromateion** [comment]
smh

**Comment by DubyaDude** [comment]
> smh

nerd

**Comment by Nekromateion** [comment]
> > smh
> 
> nerd

oh fuck you 
you waited just for me to comment didnt you?

**Comment by Myrkie** [comment]
nerdyadude

**Comment by Natsumi-sama** [comment]
nerds

**Comment by DubyaDude** [comment]
no u (to all of u)

**Comment by Myrkie** [comment]
nou nerd

https://user-images.githubusercontent.com/20288698/199857158-aa801041-ed84-438e-981c-df7850b29b41.mp4
