### ISSUE TITLE
Clear Moderations (Block, Show Avatar, Hide Avatar ...)

### ISSUE THREAD

**Issue by AkumaAbaddon** [pypy-vrc/VRCX#431]
Hi, since VRChat now fixed the display avatar glitch we are forced to show peoples avatars completely without any safety I for that reason have to go to the VRChat homepage and clear my Moderations every single day so I would love VRCX having a button for that on the moderation page

**Comment by Natsumi-sama** [comment]
https://ask.vrchat.com/t/developer-update-27-october-2022/14568#show-hide-avatar-player-moderation-local-storage-7
website will no longer be able to clear Moderations anymore, you could delete this file before starting your game instead `%UserProfile%\AppData\LocalLow\VRChat\VRChat\LocalPlayerModerations`

**Comment by AkumaAbaddon** [comment]
Yes, sorry i did not close this issue.
I actually added a function to my launcher that does exactly that!
