### ISSUE TITLE
Two-Factor authentication issue

### ISSUE THREAD

**Issue by HellsAvalanche** [pypy-vrc/VRCX#437]
So, firstly I never even set up Two-Factor
But today when I booted up vrcx, it suddenly began needing one such code, I got one code in my email, but no more. Can anyone help me out here?

**Comment by Natsumi-sama** [comment]
Can you login to the website? you may need to contact VRChat support.

**Comment by HellsAvalanche** [comment]
Indeed I can, I can still log on on vrc website and the mobile app, vrctracker

**Comment by Natsumi-sama** [comment]
Is the dialog title "Email Two-factor Authentication" or something else? any error after entering that 2FA code? because VRChat has done a staged rollout this feature is untested and can't be tested. Worst case you'll need to enable mobile 2FA for now.

**Comment by HellsAvalanche** [comment]
Here's what it said:

Hello, (My username)

Here's your one-time code: (Gave me the code)

This code is only valid for 15 minutes

VRChat staff will never ask you for this code. Never give it out to anyone!

For your own security, only enter this code into the official VRChat website or official VRChat application.

**Comment by HellsAvalanche** [comment]
It just says what my one time code is, there's nothing about an error or anything

**Comment by HellsAvalanche** [comment]
It just asks for the Two-Factor authentication code
"Enter a numeric code from your authenticator app", which doesn't exist because I never set it up-
And asks me to use OTP for an alternative, and of course the verify button
Clicking OTP asks for a saved One-time code, which again, doesn't exist

**Comment by Natsumi-sama** [comment]
Hmmm yup so something wrong with VRCX, are you running the latest VRCX version?

**Comment by HellsAvalanche** [comment]
Should I delete and reinstall the app? I can't check the vrcx version without logging in

**Comment by Myrkie** [comment]
> Should I delete and reinstall the app? I can't check the vrcx version without logging in

might wanna change that natsumi, make the VRCX app information aswell as updater accessible from the login page.

**Comment by HellsAvalanche** [comment]
Apparently I am running the latest version
2022.11.04

**Comment by Natsumi-sama** [comment]
There isn't much more I can do other that put you through a lot of annoying debugging.
Press `Ctrl + Shift + I` run `$app.debugWebRequests = true;` in console, try login, expand json, look for `requiresTwoFactorAuth` and send the contents back here.
Could also force open the correct 2FA dialog with `$app.promptEmailOTP();`

**Comment by HellsAvalanche** [comment]
You weren't lying when you said it was annoying lmao, I'm just trying to look through everything and see what I can do with the commands you provided, I have to go do some chores though, so I'll be taking more advice from others as well, and look to my partner when he's more awake to see if he can help out too

**Comment by HellsAvalanche** [comment]
This is what I have so far
requiresTwoFactorAuth: Array(0)
length: 0
[[Prototype]]: Array(0)
[[Prototype]]: Object

**Comment by HellsAvalanche** [comment]
And trying to run the force open command just gives me "undefined" as a result

**Comment by Natsumi-sama** [comment]
`requiresTwoFactorAuth` being empty makes me think this is a different issue entirely try run `webApiService.clearCookies();` then login again.

**Comment by HellsAvalanche** [comment]
That worked! Thanks a ton Natsumi, you're a lifesaver!
