### ISSUE TITLE
Softlock When removing 2FA

### ISSUE THREAD

**Issue by Denelix** [pypy-vrc/VRCX#442]
I have no clue what to do to stop getting 2FA message I removed the 2FA from my account and my authenticator. It doesn't matter what account I use. I could put random user and pass and it will give me the 2FA message and tell me username and password is required. Redstart doesn't matter reinstall doesn't matter. I have reinstalled repeatedly.

https://user-images.githubusercontent.com/69168805/205367498-5fdddd63-2467-4f83-9dcf-a03d9ebc8d9f.mp4

**Comment by Denelix** [comment]
Okay, solved it Instantly deleting the folder in %appdata% fixes it. But others probably won't know what to do so I will leave this here.

**Comment by Natsumi-sama** [comment]
Ah this bug was fixed in code but no stable release for it yet.
