### ISSUE TITLE
World Information

### ISSUE THREAD

**Issue by AvocadoFemboy** [pypy-vrc/VRCX#443]
VRCX has not been showing me my latest feed for who joins and leaves and it doesn't show what world I'm in.
![image](https://user-images.githubusercontent.com/103474655/205570209-82ab1ffa-4601-4b5e-a7bd-a52862107eac.png)
![image](https://user-images.githubusercontent.com/103474655/205570297-f26911fa-1bdf-4e2c-8be4-26ebdb18e4b8.png)

**Comment by Myrkie** [comment]
as natsumi said above
Quick menu > Settings > Debug > Logging

as set like this.

![image](https://user-images.githubusercontent.com/20288698/205577250-6fc5ac95-3f06-45fa-8520-59c55665353e.png)

**Comment by AvocadoFemboy** [comment]
Alright, that fixed it. Thank you!
