### ISSUE TITLE
[Question] Discord Presence 

### ISSUE THREAD

**Issue by AvocadoFemboy** [pypy-vrc/VRCX#447]
So, I had it turned on. Discord detects VRChat but yet it dosen't show up with a invite if I wanted a server to join or so. I have no clue if its because of VRCX taking on the presence or its on discord side.

**Comment by Natsumi-sama** [comment]
VRCX Discord presence can not support VRChats request to join Discord integration, if you'd like to use this VRChat/Discord feature you'll need to disable VRCX rich presence.
