### ISSUE TITLE
Game-Log doesnt work

### ISSUE THREAD

**Issue by Progamer75303** [pypy-vrc/VRCX#448]
The Game Log stopped working. 
It worked fine until the 10.12.22 at 02:00. 
IDK why i installed another version and also logged out and in and tried a different account. 
The console doesnt show any errors except after some time that it didnt find some users but thats after the friendlist loaded and this error after the user not found error: 
![image](https://user-images.githubusercontent.com/78344868/207128465-d03f3a57-7d17-4473-aeab-cf89f3f8e968.png)

**Comment by Myrkie** [comment]
please verify this is not the cause https://github.com/pypy-vrc/VRCX/issues/443

**Comment by Progamer75303** [comment]
ok it is that thx
