### ISSUE TITLE
Yet again

### ISSUE THREAD

**Issue by XenoxUSser** [pypy-vrc/VRCX#452]
Game Log only logs home world and so does VRCX now display it for no reason website shows it correctly but VRCX doesent anymore

![image](https://user-images.githubusercontent.com/33065711/207699571-f7bcae38-6a10-4e1f-b318-ea39c7842186.png)
![image](https://user-images.githubusercontent.com/33065711/207699598-7ecca8ca-e550-4286-b681-7312f7e0c725.png)

**Comment by Myrkie** [comment]
please verify that this is not the issue https://github.com/pypy-vrc/VRCX/issues/443

**Comment by Myrkie** [comment]
its possible that the log when disabled will still send your home world and no other logs after that point thus making it appear as if your always in home world.

**Comment by XenoxUSser** [comment]
> its possible that the log when disabled will still send your home world and no other logs after that point thus making it appear as if your always in home world.

i did like you said enabled logging in vrchat like i said in last ticket all happened when vrcx reached table size limit of 1000

should i reinstall it maybe

**Comment by XenoxUSser** [comment]
wait figured out one of my programms is blocking the events from vrc to vrcx
