### ISSUE TITLE
[Feature request] Allow saving, loading and swapping locally stored avatar favorite loadouts

### ISSUE THREAD

**Issue by Fusl** [pypy-vrc/VRCX#47]
This would allow storing an infinite amount of avatars compared to the 16 avatar slot limit.

We'd be adding buttons to several places that do different things:

- `Save locally` button on the avatar favorite page, allows you to create a new locally stored loadout with a specific name.
- `Load into favorites` button on each of the locally stored loadouts, this button deletes all avatar IDs from the favorites which are not stored in the selected loadout and puts all avatar IDs into the favorites which are in the loadout but not in the favorites list yet.
- `Save from favorites` button on each of the locally stored loadouts, this allows you to overwrite a specific loadout with a new set of avatar IDs that are currently stored in the favorites.
- `Swap with favorites` button on each of the locally stored loadouts, atomically swaps the avatar favorites IDs and the loadout IDs by saving all avatar favorite IDs into a temporary loadout, does the same as `Load into favorites` and then moves all IDs from the temporary loadout into the selected loadout.

API requests for all of the operations above should be retried with an exponential backoff until completed or failed for 5 retries. If API requests are aborted after 5 times during `Swap with favorites`, the temporary loadout should be saved with the original loadout name but with ` - Failed` added to the name so that the user can decide how to proceed.

**Comment by GotoFinal** [comment]
Would be nice to be just able swap single avatar, like first one with selected one... At least this is how I implemented this in my version.

**Comment by Fusl** [comment]
@GotoFinal Would you mind sharing the changes from your version? I'll take a look at properly implementing this and creating a PR.

**Comment by Natsumi-sama** [comment]
Not needed/possible anymore because of VRChat Plus.
