### ISSUE TITLE
Remove minified version of code in repository...

### ISSUE THREAD

**Issue by GotoFinal** [pypy-vrc/VRCX#49]
That should be part of build process and should be ignored by git, its just making working with repository harder and resolving any merge issues near impossible without just overriding whole file and ignoring it - so it should be ignored by git by default, and resolving issues is already pretty hard due to whole code being in single file.

**Comment by Murkur** [comment]
I asked why he did it yesterday during release its done by Webpack when he bundles the file and pushes the release @GotoFinal he can explain it better

**Comment by GotoFinal** [comment]
Minifying is fine, but minified versions of app should not be in repository, repository should only contain code and configuration needed to build an app.

**Comment by Murkur** [comment]
that is fair yes I didnt notice that the repo code was also minified thats a mess

**Comment by pypy-vrc** [comment]
the built html was removed. that is my mistake. 😅 anyway, I couldn't separate the source files from the beginning. It's late now, but I'll separate them little by little. 😖
