### ISSUE TITLE
Show date in event feed

### ISSUE THREAD

**Issue by EntityReborn** [pypy-vrc/VRCX#52]
Right now, things only show the time a thing happens, but not the date. This leads to confusion on what day a thing happens.

**Comment by Murkur** [comment]
that date is there mouse over the time stamp of something to see its full date
![image](https://user-images.githubusercontent.com/20288698/80407984-7bb1ab00-8894-11ea-83e9-c83f5ee2c222.png)

**Comment by EntityReborn** [comment]
Gotcha. Is it possible to have an option to show this in a second column? There's a lot of space available in how I use VRCX.

**Comment by Murkur** [comment]
would have to wait for PYPY to update the HTML
