### ISSUE TITLE
visitor and legendary user too close in color

### ISSUE THREAD

**Issue by untuned** [pypy-vrc/VRCX#54]
it's hard to distinguish the two when using dark mode

i'd recommend making legendary user a red color, for what it was back in the day

**Comment by Murkur** [comment]
the red color is already used by VRChat Team

**Comment by untuned** [comment]
> the red color is already used by VRChat Team

they use a darker red, which is why legendary would be a lighter red

**Comment by untuned** [comment]
fixed in 75c7b1ee4f320de2711bb5faaa27f633d477bf17
