### ISSUE TITLE
[Feature request] Dark theme

### ISSUE THREAD

**Issue by Fusl** [pypy-vrc/VRCX#6]
As title says. After a long night of VRChat, opening VRCX with its bright theme really burns your eyes, so a dark theme for all of us vampires would be great.

**Comment by Murkur** [comment]
ive added my own to this jusst by editing the HTML but havent touched the actual CSS tables

**Comment by Fusl** [comment]
@Murkur Care to share the modifications so we can put them in a collab PR?

**Comment by Murkur** [comment]
No exactly proud of the method I did it as I just replaced the HTML colors within index.HTML and theirs no toggle for it as I sleep in vrchat and I wouldn't need a light mode

**Comment by Murkur** [comment]
if you want the CSS file that I edited you could just swap it out 
[app.css.txt](https://github.com/pypy-vrc/VRCX/files/3764201/app.css.txt)
just rename app.css.text to app.css and add it to the HTML folder in VRCX tho I only edited it for my own use so i doubt you will continue to use it itts only simple edits you can compare for yourself

**Comment by pypy-vrc** [comment]
I'm sorry to help you. I think it will take more time.

**Comment by Arion-Kun** [comment]
Hi, as an update, I have slowly started working on a Dark Theme in my  spare time, its not completed yet but this is how it currently looks like. 
![image](https://user-images.githubusercontent.com/53127594/71641677-90947e00-2ca8-11ea-8f58-bf283f562a5e.png)
![image](https://user-images.githubusercontent.com/53127594/71641711-07317b80-2ca9-11ea-9b4c-7501146447f9.png)

Its unfinished with things like this still being white in some main areas 
![image](https://user-images.githubusercontent.com/53127594/71641723-1d3f3c00-2ca9-11ea-92c6-6c8c72ec5254.png)
![image](https://user-images.githubusercontent.com/53127594/71641725-24fee080-2ca9-11ea-855d-3ff40dd02534.png)

**Comment by Murkur** [comment]
aye nice ive just been using a simple CSS edit for my darktheme i do plan on adding a data-theme to vrcx when I get the time

**Comment by Fusl** [comment]
Ready to use app.css dark theme replacement: http://xor.meo.ws/KW5sbpwr9ZZu155hgRsK7Z8abBgsn1id/app.css @pypy-vrc feel free to use, only the buttons need to be fixed.

**Comment by Arion-Kun** [comment]
> Ready to use app.css dark theme replacement: http://xor.meo.ws/KW5sbpwr9ZZu155hgRsK7Z8abBgsn1id/app.css @pypy-vrc feel free to use, only the buttons need to be fixed.

![image](https://user-images.githubusercontent.com/53127594/71661447-da3ba200-2d56-11ea-94cb-62831175925c.png)
this area is triggering my ocd XD

its from line 210 (from your app.css Fusl)
`.x-friend-list>.x-friend-group {
	border-bottom: 5px solid #606060;
}`
a fix is just changing the #606060 to #171717 or just removing it entirely.

**Comment by Murkur** [comment]
looking at Index.HTML someone could try adding a button in MORE that just swaps which CSS the app uses
so for 
`<script>
(() => {
	var link = document.createElement('link');
	link.rel = 'stylesheet';
	link.href = `app.css?_=${Date.now()}`;
	document.getElementsByTagName('head')[0].appendChild(link);
	var script = document.createElement('script');
	script.src = `app.js?_=${Date.now()}`;
	document.getElementsByTagName('body')[0].appendChild(script);
})();
</script>`

replace app.css to have it point to another css file with the dark theme settings and have it quick reload Cerfsharp
