### ISSUE TITLE
[feature request] launch options

### ISSUE THREAD

**Issue by AlexViktorAV** [pypy-vrc/VRCX#60]
id like to add my launch options when using vrcx /vrcex
do you have discord?

**Comment by Murkur** [comment]
launch options? like launch arguments like -no-vr?

**Comment by AlexViktorAV** [comment]
yes, like --fps=60

**Comment by AlexViktorAV** [comment]
its usually easy, just adding the commands after the shortcut
"C:\Program Files (x86)\Steam\steamapps\common\VRChat\VRChat.exe" --enable-debug-gui --enable-sdk-log-levels --fps=60
these r just examples

**Comment by AlexViktorAV** [comment]
please add this feature, i beg you 🙏

**Comment by Murkur** [comment]
gonna have to wait for PYPY to respond as its his repo

**Comment by Murkur** [comment]
also that FPS Argument doesn't do anything for higher FPS or FPS lock you need a mod 

https://docs.vrchat.com/docs/launch-options

**Comment by AlexViktorAV** [comment]
well, it works for me ingame, so what? i have no modified client :thinking:Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Murkur <notifications@github.com> Datum: 15.06.20  14:08  (GMT+01:00) An: pypy-vrc/VRCX <VRCX@noreply.github.com> Cc: AlexViktorAV <viktor@vodak.org>, Author <author@noreply.github.com> Betreff: Re: [pypy-vrc/VRCX] [feature request] launch options (#60) 
also that FPS Argument doesn't do anything for higher FPS or FPS lock you need a mod
https://docs.vrchat.com/docs/launch-options

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/pypy-vrc/VRCX/issues/60#issuecomment-644091412",
"url": "https://github.com/pypy-vrc/VRCX/issues/60#issuecomment-644091412",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Murkur** [comment]
ahh im thinking of for VR since when in VR mode FPS is auto locked to your headsets refresh rate without a mod

**Comment by pypy-vrc** [comment]
fps option worked.. maybe it's undocumented 🤔
