### ISSUE TITLE
No longer able to favourite/unfavourite avatars

### ISSUE THREAD

**Issue by Zerioe** [pypy-vrc/VRCX#61]
Recently 2 of my favourited avatars went private so i tried to unfavourite them but couldn't, they just reappeared in my favourites on the app and in game, thought nothing much of it. Though just found out i can't favourite/unfavourite public avatars either. I tried clearing my favourites in the app but they just all reappeared. If anyone has some suggestion as to what to do im willing to listen.

**Comment by pypy-vrc** [comment]
contact support@vrchat.com. they might solve it.

**Comment by Zerioe** [comment]
No clue if the support ticket fixed it or what but all my favourites are removed, so it's fixed
