### ISSUE TITLE
[Feature Request] Android Apk

### ISSUE THREAD

**Issue by Toys0125** [pypy-vrc/VRCX#63]
So I know that this will seem like a tall order since Android has so many different sizes. But, I seen in previous issues you were planning adding cross platform support and android seems to be the easiest to start with since you only need to fix the browser part of the code as well cross-compiling the all for steam login. Hopefully rn you can get it start with logining in with Android and viewing current stats.
Later on adding push notification for favorites when they log on and log off will be cool.

**Comment by Murkur** [comment]
dont see it happening as VS to other platforms is alot of work

**Comment by Natsumi-sama** [comment]
Getting VRCX to run on Android just isn't possible at this time, but I could add push notifications from your desktop instance of VRCX to your phone, create another issue if that's something you would be interested in.
