### ISSUE TITLE
Can't get VRCX to load

### ISSUE THREAD

**Issue by KiraUchiha420** [pypy-vrc/VRCX#65]
this is all i see after building and trying to launch the application

![image](https://user-images.githubusercontent.com/68180298/87241242-97821300-c3e6-11ea-9ef8-e3b3078d10f7.png)

**Comment by pypy-vrc** [comment]
put html folder to your exe's path

**Comment by slord399** [comment]
It become like that even html folder present on same position as exe file present.

For me, unzip again resolve this issue.

**Comment by IsuckAtEverythingYT** [comment]
how do i even launch it?

**Comment by Murkur** [comment]
> how do i even launch it?

run the executable? https://github.com/pypy-vrc/VRCX/releases/tag/v2020.07.13

**Comment by IsuckAtEverythingYT** [comment]
i had a diffrent folder i guess cuz no .exe file in mine

**Comment by Natsumi-sama** [comment]
Closing because inactive.
