### ISSUE TITLE
VRCX 07.12버전 실행시 브라우저 표기 정렬 문제

### ISSUE THREAD

**Issue by YukihoAA** [pypy-vrc/VRCX#66]
![image](https://user-images.githubusercontent.com/20253131/87250254-90b6d700-c49e-11ea-97d7-3e1dc5f2c25c.png)
![image](https://user-images.githubusercontent.com/20253131/87250227-6ebd5480-c49e-11ea-8049-7307e3e9851f.png)

2020.07.12버전 업뎃 이후 실행시 간헐적으로 비정상적으로 정렬되어 출력됩니다.

창 크기 조절을 하면 정상 위치로 돌아옵니다.

**Comment by pypy-vrc** [comment]
띠용 👀

**Comment by YukihoAA** [comment]
@pypy-vrc 10번 실행하면 한번 저럽니다 ㅋㅋㅋ

**Comment by pypy-vrc** [comment]
CEF v81의 버그로 추정이 됩니다만은 CEF v83이 나왔길래 올려보니 또 다른 버그가 있어서 다시 CEF v79로 롤백하였습니다.
2020.07.13 버전을 릴리즈 하였으니 확인 부탁드려용..

**Comment by YukihoAA** [comment]
@pypy-vrc 수정되었습니당
