### ISSUE TITLE
07.12버전 Steam Overlay가 동작하지 않는 문제

### ISSUE THREAD

**Issue by YukihoAA** [pypy-vrc/VRCX#67]
04.07버전에서 잘 동작하던 Steam Overlay 기능이 07.12버전에선 동작하지 않습니다.

0407버전으로 다시 사용하면 정상적으로 동작합니다.

0407버전 Steam Overlay 비활성화 후 0712버전 활성화, 스팀 VR끈 상태에서 0712버전 활성화, 스팀 VR켠 상태에서 0712버전 활성화 전부 실험해보았습니다.

**Comment by pypy-vrc** [comment]
끄아아... 확인해보겠읍니다

**Comment by pypy-vrc** [comment]
해결했읍니당
