### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by ZiggyZong** [pypy-vrc/VRCX#69]
Cant open, getting this error.

![yWniXXC](https://user-images.githubusercontent.com/68216464/87274462-d4630e00-c4a9-11ea-931f-bef50bba4b30.png)

**Comment by ZiggyZong** [comment]
This is on the newest VRCX 2020.07.13 release

Went back to VRCX 2020.07.12 having no issues

**Comment by IsuckAtEverythingYT** [comment]
how do i even launch it?

**Comment by Natsumi-sama** [comment]
Closing because inactive.
