### ISSUE TITLE
[Feature request] Show all instance join/leave VR overlay notifications from all users, not just favorited/VIP friends

### ISSUE THREAD

**Issue by Fusl** [pypy-vrc/VRCX#7]
Optionally, also provide toggle options to configure join/leave notifications:

- VIP joins/leaves non-public instance
- VIP joins/leaves public instance
- Friend joins/leaves non-public instance
- Friend joins/leaves public instance
- Anyone joins/leaves non-public instance
- Anyone joins/leaves public instance

**Comment by Natsumi-sama** [comment]
Added here: https://github.com/pypy-vrc/VRCX/commit/e9d3347ce729162c9d828d1c23cacdf4a8e8356f
