### ISSUE TITLE
[Feature request] Incremental (and in-app) updates

### ISSUE THREAD

**Issue by symant233** [pypy-vrc/VRCX#70]
Hi pypy. I have some suggestions on the VRCX update.

Download a full package of VRCX costs a lot of bandwidth. 
It's better to have an differ pack of modified build files. (compared with previous release)

Then check updates and apply in VRCX with minimal differ pack.

**Comment by pypy-vrc** [comment]
The CEF library is a big part of the app package. If the CEF version is the same when the new VRCX is released, the delta patch will definitely reduce the size.

**Comment by Natsumi-sama** [comment]
Is in-app but not incremental.
