### ISSUE TITLE
Does Not Run In Wine/Proton

### ISSUE THREAD

**Issue by MistieKitteh** [pypy-vrc/VRCX#75]
![image](https://user-images.githubusercontent.com/27728278/89094038-37471700-d37d-11ea-8662-db4e84359a1a.png)
Proton 5.0 running through steam on Ubuntu Budgie

**Comment by Flimsy-Fox** [comment]
Fixed the Mono problem. However, still gives a FileNotFound error.
Steps to reproduce:
- Create a wine64 prefix in the default directory.
- Open a new terminal and run the commands in the code block in [this](https://github.com/Winetricks/winetricks/issues/971#issuecomment-385201948) comment.
- Run `winetricks dotnet472` It might give an error or two. Follow the install buttons and wait until the terminal gets to a new prompt.
- Download VRCX and copy to `~.wine/drive_c/users/[YOUR_NAME]/Downloads/`. Choose a different name for the destination file.
- Run `winetricks winecfg` and ensure that the version is set to "Windows 10", add `version` to the overrides and confirm.
- Run `wine64 wineconsole` You are now in CMD.
- Type into CMD `C:/windows/system32/explorer.exe` and press Enter.
- In the window that pops up, click on "My Computer" and navigate to your Downloads directory in the C drive. Double-click on the VRCX exe file that you have chosen the name for.
- Follow the installation prompts.
- Still in Explorer, navigate to `C:/Program Files/VRCX/` Run `VRCX.exe` The error below should pop up.
![Screenshot from 2022-09-14 11-35-48](https://user-images.githubusercontent.com/29789649/190213368-23839080-9ee5-42c8-92cf-251bf5a7c7e1.png)

**Comment by Natsumi-sama** [comment]
Give this guide a try if you haven't already. https://web.archive.org/web/20220611004115/https://github.com/RinLovesYou/VRChat-Linux/wiki/VRCX

**Comment by Flimsy-Fox** [comment]
Had to fix some configuration issues on my end, and the provided solution worked.
Here's what I had to do:
- Install laptop vendor drivers for Ubuntu
- Set my graphics device in `nvidia-settings` to only the NVIDIA GPU.
- Reboot

Note that the issues I had with creating Wine Windows in 7.0 _should_ appear only if you have a laptop that uses hardware muxing with an Intel iGPU and the iGPU is set to be at least partially used.

**Comment by Foorack** [comment]
@Flimsy-Fox 
/ Off-side comment, but your explanation on how to fix the bug made me think of this https://twitter.com/Iinux/status/1570564762865651713
