### ISSUE TITLE
Cant open the aplication

### ISSUE THREAD

**Issue by Rat2048** [pypy-vrc/VRCX#76]
![Annotation 2020-09-01 231029](https://user-images.githubusercontent.com/70620768/91931212-64525680-eca8-11ea-809f-8ccba0232217.png)

**Comment by pypy-vrc** [comment]
ripper..? 🤔 btw, it seems that some files are missing.

**Comment by Rat2048** [comment]
![Annotation 2020-09-01 233601](https://user-images.githubusercontent.com/70620768/91932491-edb75800-ecab-11ea-9894-a3ed4dd26b2c.png)
well now its not loading

**Comment by illieath** [comment]
I'm getting the same error.

**Comment by Murkur** [comment]
dont really want to help you because of your intentions with vrcx 
![image](https://user-images.githubusercontent.com/20288698/92313660-39b01880-ef9c-11ea-81ea-47525f6ca9e8.png)
