### ISSUE TITLE
[Feature request] Mac port

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [pypy-vrc/VRCX#78]
I don't know how many people would be interested by that but i am,
I'm looking for or to make a mac port of VRCX, i use a mac when i'm not on my vr setup and i now hate the vrchat website since i use vrcx
Thanks for taking a look at this feature request

**Comment by Natsumi-sama** [comment]
It would require a massive rewrite so it's not possible for the time being, look into getting Wine or VMware Fusion, there are several ways of running windows applications on macOS.

**Comment by TomAvecLeVdsl** [comment]
Thanks for looking into the issue ... hope it will be done one day
