### ISSUE TITLE
[Feature Request] Get avatar info by clicking on item in Feed

### ISSUE THREAD

**Issue by fwenny** [pypy-vrc/VRCX#79]
One of the things Feed records is Avatar changes.
It would be great if I could click on an item (for example the text "Avatar" under Type) and it would open up the info for the avatar the person switched into.

Thank you.

**Comment by pypy-vrc** [comment]
![Honeycam 2020-09-29 20-36-57](https://user-images.githubusercontent.com/25771678/94553492-8d5c0c00-0293-11eb-83eb-72158955d46e.gif)

**Comment by fwenny** [comment]
This looks great, thank you.
