### ISSUE TITLE
[Feature Request] Export Friend List

### ISSUE THREAD

**Issue by YukihoAA** [pypy-vrc/VRCX#80]
친구목록을 csv, xls 등의 파일로 추출할 수 있었으면 좋겠습니다

Export Friend List to .csv, .xls, etc.

**Comment by pypy-vrc** [comment]
![image](https://user-images.githubusercontent.com/25771678/94553122-f7c07c80-0292-11eb-9c63-41ef55c17cd3.png)

**Comment by YukihoAA** [comment]
@pypy-vrc 빠른 피드백 감사합니다!

**Comment by Bluscream** [comment]
I had something similar https://github.com/Bluscream/VRChatLauncher/blob/master/UI/Main/Users.cs#L603-L636
