### ISSUE TITLE
Can't launch after compiling from source

### ISSUE THREAD

**Issue by timduru** [pypy-vrc/VRCX#82]
Hello, 
I'm able to compile the VS project fine, but after generation it's missing the html folder

If I copy the html folder from your release into the bin/ directory where it has been compiled it works ok
But not if I copy the html/ directory from your src tree.
I've seen a make-junction.cmd but that links to an html/dist/ directory that is not present

What are the steps to generate the "release" html directory from the html/ directory in your src tree ?
I'd like to run a few tests and add a few features to app.js

Thanks

**Comment by Murkur** [comment]
thats normal as stated by VRCX VRCX 2020.04.07 HTML JS and CSS are now packed (minified) and require you to build them yourselves 
![image](https://user-images.githubusercontent.com/20288698/95010160-1dcc8080-05f5-11eb-9e44-5f363c1e5125.png)

HTML is found at https://github.com/pypy-vrc/VRCX/tree/master/html
maybe try changing the make-junction.cmd to reflect to the correct directory

**Comment by timduru** [comment]
Yeah I have the master tree with the html, 
I tried to link or copy the html/ from the tree to the Debug directory like the make-junction does with or without the /dist part. 
mklink /J "%~dp0\bin\x64\Debug\html" "%~dp0\html\dist"
but it's not working.

I think it's just missing the step to pack it.
That step is what most likely generate the missing /dist directory that the make-junction expects
Not sure what tool is used for that ?

**Comment by Murkur** [comment]
if I remember right WebPack is being used

**Comment by timduru** [comment]
ok thanks, 
Was kinda hoping not to have to install nodejs/npm, 
but got it to work.

For Future reference here are the steps to get a fully working test/release:
* Install nodejs/npm  https://nodejs.org/en/
* Launch CMD and go to the VRCX-master\html directory
* run: npm run development   (or production)
that will generate the /dist directory
* execute the make-junction.cmd to create the link into the bin directory 

* Launch the exe
