### ISSUE TITLE
[Bug?] Opening vrchat through VRCX makes hands unusable

### ISSUE THREAD

**Issue by fwenny** [pypy-vrc/VRCX#89]
Im on Index with Index controllers
If I open a new instance of a world / Join a friend through VRCX and launch in VR, my controller bindings are broken.
I cant use fingertracking and some buttons dont work properly.

**Comment by Fusl** [comment]
This isn not a VRCX issue, this happens when you launch any VR game outside of SteamVR since it doesn't load the actual controller binding profile but a fallback profile.

**Comment by pypy-vrc** [comment]
Running vrchat through Steam will solve it I think, but I don't know how to run it through Steam. 😅

**Comment by Murkur** [comment]
steams game shortcuts use the steams game app ID to launch them so maybe `steam://rungameid/438100// --no-vr` as an example starting vrchat with no vr

**Comment by Murkur** [comment]
yep just tested that by pasting it into my web browser but it does ask for confirmation 
![image](https://user-images.githubusercontent.com/20288698/97101904-8dbfab00-1677-11eb-881a-9081e1ca1ca6.png)

**Comment by fwenny** [comment]
question is can pypy change it so launching vrchat uses the steam:// method, but also able to pass parameters to vrchat like what world to join, with what instance privacy, etc.

**Comment by Murkur** [comment]
seems its possible using a vrchat launch link `vrchat://launch?Id=wrld_3259761f-5dee-4b86-80e1-00f9178da209&instanceId=24330~private(usr_f4495a87-599d-41e4-96c9-b88e419befcc)~nonce(7d5918b1-5ff5-4ceb-ea17-8fb293cbff77)~canRequestInvite`

but doesnt work well as that requires its own intergration protocol from vrchat which is added when you first install vrchat steam doesnt understand this protocol so it wont recognize it as a parameter

**Comment by Murkur** [comment]
the protocol im speaking off is the vrchat first time installer that asks for install when you first install the game `install.exe`

**Comment by pypy-vrc** [comment]
it seems possible
```
[My Computer\HKEY_CLASSES_ROOT\steam\Shell\Open\Command]
"C:\Program Files (x86)\Steam\steam.exe" -- "%1"
```

**Comment by Murkur** [comment]
there you go

**Comment by pypy-vrc** [comment]
also check this one
https://developer.valvesoftware.com/wiki/Steam_browser_protocol
