### ISSUE TITLE
[Feature request] Allow setting VR overlay notification time and position

### ISSUE THREAD

**Issue by Fusl** [pypy-vrc/VRCX#9]
Because the current timeout for the notification to disappear again is too long for some people and too short for some other people to read.

**Comment by Natsumi-sama** [comment]
Added with these: https://github.com/pypy-vrc/VRCX/commit/9eb6dd777bfc33052cc7e90b5cdd12e6e3a56932 https://github.com/pypy-vrc/VRCX/commit/9589a708e306854cae50e236247662dcdaa59fb9
