### ISSUE TITLE
Missing Credentials Issue

### ISSUE THREAD

**Issue by SalaciousBug** [pypy-vrc/VRCX#92]
So for some reason, VRCX is not letting me login anymore, citing 'missing credentials' even though I have all of my info correct. I have no idea why I'm having this issue all of a sudden. I thought it was related to 2FA but apparently not or at least it doesn't seem to be though the login page doesn't give me the option to enter my 2FA code.

Is anyone able to help me out here?

**Comment by Provini** [comment]
Try logging in using your email instead of your username.

**Comment by SalaciousBug** [comment]
> Try logging in using your email instead of your username.

Tried that, but still gave me the same issue. :/

**Comment by SalaciousBug** [comment]
Does anyone have a way to fix this issue, please? I have not been able to use VRCX since it started.

**Comment by pypy-vrc** [comment]
i'm sorry for too late 😖

**Comment by SalaciousBug** [comment]
> i'm sorry for too late 😖

No worries! I’m not able to test if this is fixed on my end currently as my PC is away for repairs but thank you for acknowledging and commiting to the issue!
