### ISSUE TITLE
Many questions

### ISSUE THREAD

**Issue by Kilowog01** [pypy-vrc/VRCX#93]
What is the difference between logging in with steam and without steam? And why when I try to login with steam I get an error "It only works when VRChat is running." While I have VRchat open. How do I install the steam DLL? Where do I find it? Why isn't there a tutorial with all this explained? How do I sort my friends by trust level, time without login, etc? Why doesn't my friends list even appear on VRCX?

**Comment by Murkur** [comment]
Logging in with steam logs you in with your steam account if a steam account exists, logging in regularly logs you in with your vrchat.net account. a steam vrchat account is linked with your steam account while a vrchat.net one is standalone

**Comment by Murkur** [comment]
if your friends list doesn't appear your probably in the wrong account, and to sort by friends you do that from the MORE tab. you shouldn't really be asking questions on basic usage since its all self explanatory or straight forward to learn

**Comment by Kilowog01** [comment]
I wasn't in the wrong account. I really shouldn't be asking questions in basic usage, apparently you don't want anyone using your software at all. So I proceeded to the official Vrchat website and solved my problem. Thanks for nothing.

**Comment by Murkur** [comment]
okay? goodbye don't let the door hit you on the way out you can close this ticket now
